
'''

Ntuple branch template sets for topological variables (MT, etc)

Each string is transformed into an expression on a FinalStateEvent object.

Author: Evan K. Friis

'''

from FinalStateAnalysis.Utilities.cfgtools import PSet

mtToMET = PSet(
    #objectMtToPfMet_type1   = 'mtMET({object_idx}, "", ""     )',
    #objectDPhiToPfMet_type1 = 'deltaPhiToMEt({object_idx}, "", ""     )',
    ##MVA MET
    #objectMtToMVAMET     = 'mtMET({object_idx}, "", "mvamet", "", 0)',
)

# these things break if you pass a shifted met
shiftedMtToMET = PSet(
    ## Raw means no MET corrections
    #objectMtToPfMet_Raw = 'mtMET({object_idx}, "", "raw")',

    ##PF Type1 MET (and systematics)
    #objectMtToPfMet_JetResUp          = 'mtMET({object_idx}, "", "jres+")',
    #objectMtToPfMet_JetEnUp           = 'mtMET({object_idx}, "", "jes+" )',
    #objectMtToPfMet_MuonEnUp          = 'mtMET({object_idx}, "", "mes+" )',
    #objectMtToPfMet_ElectronEnUp      = 'mtMET({object_idx}, "", "ees+" )',
    #objectMtToPfMet_TauEnUp           = 'mtMET({object_idx}, "tesUpTaus", "tes+" )',
    #objectMtToPfMet_UnclusteredEnUp   = 'mtMET({object_idx}, "", "ues+" )',
    #objectMtToPfMet_PhotonEnUp        = 'mtMET({object_idx}, "", "pes+" )',

    #objectMtToPfMet_JetResDown        = 'mtMET({object_idx}, "", "jres-")',
    #objectMtToPfMet_JetEnDown         = 'mtMET({object_idx}, "", "jes-" )',
    #objectMtToPfMet_MuonEnDown        = 'mtMET({object_idx}, "", "mes-" )',
    #objectMtToPfMet_ElectronEnDown    = 'mtMET({object_idx}, "", "ees-" )',
    #objectMtToPfMet_TauEnDown         = 'mtMET({object_idx}, "tesDownTaus", "tes-" )',
    #objectMtToPfMet_UnclusteredEnDown = 'mtMET({object_idx}, "", "ues-" )',
    #objectMtToPfMet_PhotonEnDown      = 'mtMET({object_idx}, "", "pes-" )',

    #objectDPhiToPfMet_JetResUp          = 'deltaPhiToMEt({object_idx}, "", "jres+")',
    #objectDPhiToPfMet_JetEnUp           = 'deltaPhiToMEt({object_idx}, "", "jes+" )',
    #objectDPhiToPfMet_MuonEnUp          = 'deltaPhiToMEt({object_idx}, "", "mes+" )',
    #objectDPhiToPfMet_ElectronEnUp      = 'deltaPhiToMEt({object_idx}, "", "ees+" )',
    #objectDPhiToPfMet_TauEnUp           = 'deltaPhiToMEt({object_idx}, "", "tes+" )',
    #objectDPhiToPfMet_UnclusteredEnUp   = 'deltaPhiToMEt({object_idx}, "", "ues+" )',
    #objectDPhiToPfMet_PhotonEnUp        = 'deltaPhiToMEt({object_idx}, "", "pes+" )',

    #objectDPhiToPfMet_JetResDown        = 'deltaPhiToMEt({object_idx}, "", "jres-")',
    #objectDPhiToPfMet_JetEnDown         = 'deltaPhiToMEt({object_idx}, "", "jes-" )',
    #objectDPhiToPfMet_MuonEnDown        = 'deltaPhiToMEt({object_idx}, "", "mes-" )',
    #objectDPhiToPfMet_ElectronEnDown    = 'deltaPhiToMEt({object_idx}, "", "ees-" )',
    #objectDPhiToPfMet_TauEnDown         = 'deltaPhiToMEt({object_idx}, "", "tes-" )',
    #objectDPhiToPfMet_UnclusteredEnDown = 'deltaPhiToMEt({object_idx}, "", "ues-" )',
    #objectDPhiToPfMet_PhotonEnDown      = 'deltaPhiToMEt({object_idx}, "", "pes-" )',
)

# Variables based on pairs of objects
pairs = PSet(
    object1_object2_Mass = 'subcand({object1_idx}, {object2_idx}).get.mass',
    #object1_object2_Mt = 'subcand({object1_idx}, {object2_idx}).get.mt',
    #object1_object2_collinearmass = 'collinearMassMET({object1_idx}, "", {object2_idx},"","")',
    #object2_object1_collinearmass = 'collinearMassMET({object2_idx}, "", {object1_idx},"","")',
   
    #object1_object2_Mass_TauEnUp = 'subcand({object1_idx}, "",{object2_idx},"tesUpTaus").get.mass',
    #object1_object2_Mass_TauEnDown = 'subcand({object1_idx}, "",{object2_idx},"tesDownTaus").get.mass',
    #object1_object2_Mt_TauEnUp = 'subcand({object1_idx}, "",{object2_idx},"tesUpTaus").get.mt',
    #object1_object2_Mt_TauEnDown = 'subcand({object1_idx}, "",{object2_idx},"tesDownTaus").get.mt',
 
    #object1_object2_Pt = 'subcand({object1_idx}, {object2_idx}).get.pt',
    #object1_object2_Eta = 'subcand({object1_idx}, {object2_idx}).get.eta',
    #object1_object2_Phi = 'subcand({object1_idx}, {object2_idx}).get.phi',
    object1_object2_DR = 'dR({object1_idx}, {object2_idx})',
    #object1_object2_DPhi = 'dPhi({object1_idx}, {object2_idx})',
    #object1_object2_SS = 'likeSigned({object1_idx}, {object2_idx})',
    #object1_object2_PZeta = 'pZeta({object1_idx}, {object2_idx})',
    #object1_object2_PZetaVis = 'pZetaVis({object1_idx}, {object2_idx})',
    #object1_object2_CosThetaStar = 'abs(subcand({object1_idx}, {object2_idx}).get.daughterCosThetaStar(0))',

    #object1_object2_collinearmass_JetEnUp = 'collinearMassMET({object1_idx}, "", {object2_idx},"","jes+")',
    #object2_object1_collinearmass_JetEnUp = 'collinearMassMET({object2_idx}, "", {object1_idx},"","jes+")', # for now we only need m_t_coll
    #object1_object2_collinearmass_JetEnDown = 'collinearMassMET({object1_idx}, "", {object2_idx},"","jes-")',
    #object2_object1_collinearmass_JetEnDown = 'collinearMassMET({object2_idx}, "", {object1_idx},"","jes-")',
    #object1_object2_collinearmass_UnclusteredEnUp = 'collinearMassMET({object1_idx}, "", {object2_idx},"","ues+")',
    #object2_object1_collinearmass_UnclusteredEnUp = 'collinearMassMET({object2_idx}, "", {object1_idx},"","ues+")',
    #object1_object2_collinearmass_UnclusteredEnDown = 'collinearMassMET({object1_idx}, "", {object2_idx},"","ues-")',
    #object2_object1_collinearmass_UnclusteredEnDown = 'collinearMassMET({object2_idx}, "", {object1_idx},"","ues-")',
    #object1_object2_collinearmass_TauEnUp = 'collinearMassMET({object1_idx}, "", {object2_idx},"tesUpTaus","tes+")',
    #object1_object2_collinearmass_TauEnDown = 'collinearMassMET({object1_idx}, "", {object2_idx},"tesDownTaus","tes-")',
    #object1_object2_collinearmass_EleEnUp = 'collinearMassMET({object1_idx}, "", {object2_idx},"","ees+")',
    #object1_object2_collinearmass_EleEnDown = 'collinearMassMET({object1_idx}, "", {object2_idx},"","ees-")',
    #object1_object2_collinearmass_MuEnUp = 'collinearMassMET({object1_idx}, "", {object2_idx},"","mes+")',
    #object1_object2_collinearmass_MuEnDown = 'collinearMassMET({object1_idx}, "", {object2_idx},"","mes-")',

    #object1_object2_collinearmass_JetCheckTotalUp = 'collinearMassMET({object1_idx}, "", {object2_idx},"","jesTotal+")',
    #object2_object1_collinearmass_JetCheckTotalUp = 'collinearMassMET({object2_idx}, "", {object1_idx},"","jesTotal+")', # for now we only need m_t_coll
    #object1_object2_collinearmass_JetCheckTotalDown = 'collinearMassMET({object1_idx}, "", {object2_idx},"","jesTotal-")',
    #object2_object1_collinearmass_JetCheckTotalDown = 'collinearMassMET({object2_idx}, "", {object1_idx},"","jesTotal-")',
    #object1_object2_collinearmass_CheckUESUp = 'collinearMassMET({object1_idx}, "", {object2_idx},"","checkUES+")',
    #object2_object1_collinearmass_CheckUESUp = 'collinearMassMET({object2_idx}, "", {object1_idx},"","checkUES+")',
    #object1_object2_collinearmass_CheckUESDown = 'collinearMassMET({object1_idx}, "", {object2_idx},"","checkUES-")',
    #object2_object1_collinearmass_CheckUESDown = 'collinearMassMET({object2_idx}, "", {object1_idx},"","checkUES-")',

    ##Pairs + MET
    #object1_object2_ToMETDPhi_Ty1 = 'twoParticleDeltaPhiToMEt({object1_idx}, {object2_idx}, "type1")',
)

svfit = PSet(
    #object1_object2_SVfitMass = 'SVfit({object1_idx},{object2_idx}).at(0)',
    #object1_object2_SVfitPt = 'SVfit({object1_idx},{object2_idx}).at(1)',
    #object1_object2_SVfitEta = 'SVfit({object1_idx},{object2_idx}).at(2)',
    #object1_object2_SVfitPhi = 'SVfit({object1_idx},{object2_idx}).at(3)',
    #object1_object2_SVfitMET = 'SVfit({object1_idx},{object2_idx}).at(4)',
)

finalstate = PSet(
    LT = 'ht',
    charge = 'charge',
    Pt = 'pt',
    Eta = 'eta',
    Phi = 'phi',
    Mass = 'mass',
    Mt = 'mt',
    Ht = 'jetHt("pt>30 && abs(eta)<2.5")',
    MassError = '? hasUserFloat("cand_dM") ? userFloat("cand_dM") : -999',
    MassErrord1 = '? hasUserFloat("cand_dM_0") ? userFloat("cand_dM_0") : -999',
    MassErrord2 = '? hasUserFloat("cand_dM_1") ? userFloat("cand_dM_1") : -999',
    MassErrord3 = '? hasUserFloat("cand_dM_2") ? userFloat("cand_dM_2") : -999',
    MassErrord4 = '? hasUserFloat("cand_dM_3") ? userFloat("cand_dM_3") : -999',
)


vbf = PSet(
   vbfNJets20 = 'vbfVariables("pt > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | pt>50)", 0.5).nJets',
   vbfNJets30 = 'vbfVariables("pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | pt>50)", 0.5).nJets',
   vbfJetVeto30 = 'vbfVariables("pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | pt>50)", 0.5).jets30',
   vbfJetVeto20 = 'vbfVariables("pt > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | pt>50)", 0.5).jets20',
   vbfMass = 'vbfVariables("pt > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | pt>50)", 0.5).mass',
   vbfMassWoNoisyJets = 'vbfVariables("(pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & pt > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | pt>50)", 0.5).mass',
   vbfDeta = 'vbfVariables("pt > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | pt>50)", 0.5).deta',
   vbfj1eta = 'vbfVariables("pt > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | pt>50)", 0.5).eta1',
   vbfj2eta = 'vbfVariables("pt > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | pt>50)", 0.5).eta2',
   vbfj1pt = 'vbfVariables("pt > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | pt>50)", 0.5).pt1',
   vbfj2pt = 'vbfVariables("pt > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | pt>50)", 0.5).pt2',

)


extraJet = PSet(
    objectPt = '? evt.jets.size()>{object_idx} ? {object}.pt() : -999',
    objectPtJESTotal_Up = '? evt.jets.size()>{object_idx} ? {object}.userCand(\'jesTotal+\').pt() : -999',
    objectPtJESTotal_Down = '? evt.jets.size()>{object_idx} ? {object}.userCand(\'jesTotal-\').pt() : -999',
    objectPtJESClosureNew_Up = '? evt.jets.size()>{object_idx} ? {object}.userCand(\'jesClosureNew+\').pt() : -999',
    objectPtJESClosureNew_Down = '? evt.jets.size()>{object_idx} ? {object}.userCand(\'jesClosureNew-\').pt() : -999',
    objectEta = '? evt.jets.size()>{object_idx} ? {object}.eta() : -999',
    objectPhi = '? evt.jets.size()>{object_idx} ? {object}.phi() : -999',
    objectIDTight = '? evt.jets.size()>{object_idx} ? {object}.userFloat("idTight") : -999',
    objectIDTightLepVeto = '? evt.jets.size()>{object_idx} ? {object}.userFloat("idTightLepVeto") : -999',
    objectIDLoose = '? evt.jets.size()>{object_idx} ? {object}.userFloat("idLoose") : -999',
    objectPUMVA = '? evt.jets.size()>{object_idx} & {object}.pt()>20 & abs({object}.eta())<2.5 ? {object}.userFloat("pileupJetId:fullDiscriminant") : -999',
    objectBJetCISV = '? evt.jets.size()>{object_idx} & {object}.pt()>20 & abs({object}.eta())<2.5 ? {object}.bDiscriminator(\'pfCombinedInclusiveSecondaryVertexV2BJetTags\') : -999',
)


# Temporary variables for JES study
fullJES = PSet(
        jetVeto30_JERUp = 'vetoJets(0.5, "userCand(\'jer+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jer+\').pt > 50)").size()',
        jetVeto30_JERDown = 'vetoJets(0.5, "userCand(\'jer-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jer-\').pt > 50)").size()',
        vbfMass_JERUp = 'vbfVariables("userCand(\'jer+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jer+\').pt() > 50)", 0.5).mass',
        vbfMass_JERDown = 'vbfVariables("userCand(\'jer-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jer-\').pt() > 50)", 0.5).mass',
        vbfMassWoNoisyJets_JERUp = 'vbfVariables("(userCand(\'jer+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jer+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jer+\').pt() > 50)", 0.5).mass',
        vbfMassWoNoisyJets_JERDown = 'vbfVariables("(userCand(\'jer-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jer-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jer-\').pt() > 50)", 0.5).mass',
        jetVeto30WoNoisyJets_JERUp = 'vetoJets(0.5, "(userCand(\'jer+\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jer+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jer+\').pt > 50)").size()',
        jetVeto30WoNoisyJets_JERDown = 'vetoJets(0.5, "(userCand(\'jer-\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jer-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jer-\').pt > 50)").size()',
        j1pt_JERDown = 'jetVariables("userCand(\'jer-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jer-\').pt() > 50)", 0.5).at(0)',
        j2pt_JERDown = 'jetVariables("userCand(\'jer-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jer-\').pt() > 50)", 0.5).at(10)',
        j1pt_JERUp = 'jetVariables("userCand(\'jer+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jer+\').pt() > 50)", 0.5).at(0)',
        j2pt_JERUp = 'jetVariables("userCand(\'jer+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jer+\').pt() > 50)", 0.5).at(10)',
        j1ptWoNoisyJets_JERDown = 'jetVariables("(userCand(\'jer-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jer-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jer-\').pt() > 50)", 0.5).at(0)',
        j2ptWoNoisyJets_JERDown = 'jetVariables("(userCand(\'jer-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jer-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jer-\').pt() > 50)", 0.5).at(10)',
        j1ptWoNoisyJets_JERUp = 'jetVariables("(userCand(\'jer+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jer+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jer-\').pt() > 50)", 0.5).at(0)',
        j2ptWoNoisyJets_JERUp = 'jetVariables("(userCand(\'jer+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jer+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jer-\').pt() > 50)", 0.5).at(10)',

        vbfMass_JetTotalUp = 'vbfVariables("userCand(\'jesTotal+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesTotal+\').pt() > 50)", 0.5).mass',
        vbfMass_JetTotalDown = 'vbfVariables("userCand(\'jesTotal-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesTotal-\').pt() > 50)", 0.5).mass',
        jetVeto30_JetTotalUp = 'vetoJets(0.5, "userCand(\'jesTotal+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesTotal+\').pt > 50)").size()',
        jetVeto30_JetTotalDown = 'vetoJets(0.5, "userCand(\'jesTotal-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesTotal-\').pt > 50)").size()',
        vbfMass_JetEC2Up = 'vbfVariables("userCand(\'jesEC2+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesEC2+\').pt() > 50)", 0.5).mass',
        vbfMass_JetEC2Down = 'vbfVariables("userCand(\'jesEC2-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesEC2-\').pt() > 50)", 0.5).mass',
        jetVeto30_JetEC2Up = 'vetoJets(0.5, "userCand(\'jesEC2+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesEC2+\').pt > 50)").size()',
        jetVeto30_JetEC2Down = 'vetoJets(0.5, "userCand(\'jesEC2-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesEC2-\').pt > 50)").size()',
        vbfMass_JetAbsoluteUp = 'vbfVariables("userCand(\'jesAbsolute+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesAbsolute+\').pt() > 50)", 0.5).mass',
        vbfMass_JetAbsoluteDown = 'vbfVariables("userCand(\'jesAbsolute-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesAbsolute-\').pt() > 50)", 0.5).mass',
        jetVeto30_JetAbsoluteUp = 'vetoJets(0.5, "userCand(\'jesAbsolute+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesAbsolute+\').pt > 50)").size()',
        jetVeto30_JetAbsoluteDown = 'vetoJets(0.5, "userCand(\'jesAbsolute-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesAbsolute-\').pt > 50)").size()',
        vbfMass_JetAbsoluteyearUp = 'vbfVariables("userCand(\'jesAbsoluteyear+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesAbsoluteyear+\').pt() > 50)", 0.5).mass',
        vbfMass_JetAbsoluteyearDown = 'vbfVariables("userCand(\'jesAbsoluteyear-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesAbsoluteyear-\').pt() > 50)", 0.5).mass',
        jetVeto30_JetAbsoluteyearUp = 'vetoJets(0.5, "userCand(\'jesAbsoluteyear+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesAbsoluteyear+\').pt > 50)").size()',
        jetVeto30_JetAbsoluteyearDown = 'vetoJets(0.5, "userCand(\'jesAbsoluteyear-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesAbsoluteyear-\').pt > 50)").size()',
        vbfMass_JetFlavorQCDUp = 'vbfVariables("userCand(\'jesFlavorQCD+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesFlavorQCD+\').pt() > 50)", 0.5).mass',
        vbfMass_JetFlavorQCDDown = 'vbfVariables("userCand(\'jesFlavorQCD-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesFlavorQCD-\').pt() > 50)", 0.5).mass',
        jetVeto30_JetFlavorQCDUp = 'vetoJets(0.5, "userCand(\'jesFlavorQCD+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesFlavorQCD+\').pt > 50)").size()',
        jetVeto30_JetFlavorQCDDown = 'vetoJets(0.5, "userCand(\'jesFlavorQCD-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesFlavorQCD-\').pt > 50)").size()',
        vbfMass_JetBBEC1Up = 'vbfVariables("userCand(\'jesBBEC1+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesBBEC1+\').pt() > 50)", 0.5).mass',
        vbfMass_JetBBEC1Down = 'vbfVariables("userCand(\'jesBBEC1-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesBBEC1-\').pt() > 50)", 0.5).mass',
        jetVeto30_JetBBEC1Up = 'vetoJets(0.5, "userCand(\'jesBBEC1+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesBBEC1+\').pt > 50)").size()',
        jetVeto30_JetBBEC1Down = 'vetoJets(0.5, "userCand(\'jesBBEC1-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesBBEC1-\').pt > 50)").size()',
        vbfMass_JetHFUp = 'vbfVariables("userCand(\'jesHF+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesHF+\').pt() > 50)", 0.5).mass',
        vbfMass_JetHFDown = 'vbfVariables("userCand(\'jesHF-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesHF-\').pt() > 50)", 0.5).mass',
        jetVeto30_JetHFUp = 'vetoJets(0.5, "userCand(\'jesHF+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesHF+\').pt > 50)").size()',
        jetVeto30_JetHFDown = 'vetoJets(0.5, "userCand(\'jesHF-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesHF-\').pt > 50)").size()',
        vbfMass_JetBBEC1yearUp = 'vbfVariables("userCand(\'jesBBEC1year+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesBBEC1year+\').pt() > 50)", 0.5).mass',
        vbfMass_JetBBEC1yearDown = 'vbfVariables("userCand(\'jesBBEC1year-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesBBEC1year-\').pt() > 50)", 0.5).mass',
        jetVeto30_JetBBEC1yearUp = 'vetoJets(0.5, "userCand(\'jesBBEC1year+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesBBEC1year+\').pt > 50)").size()',
        jetVeto30_JetBBEC1yearDown = 'vetoJets(0.5, "userCand(\'jesBBEC1year-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesBBEC1year-\').pt > 50)").size()',
        vbfMass_JetEC2yearUp = 'vbfVariables("userCand(\'jesEC2year+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesEC2year+\').pt() > 50)", 0.5).mass',
        vbfMass_JetEC2yearDown = 'vbfVariables("userCand(\'jesEC2year-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesEC2year-\').pt() > 50)", 0.5).mass',
        jetVeto30_JetEC2yearUp = 'vetoJets(0.5, "userCand(\'jesEC2year+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesEC2year+\').pt > 50)").size()',
        jetVeto30_JetEC2yearDown = 'vetoJets(0.5, "userCand(\'jesEC2year-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesEC2year-\').pt > 50)").size()',
        vbfMass_JetHFyearUp = 'vbfVariables("userCand(\'jesHFyear+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesHFyear+\').pt() > 50)", 0.5).mass',
        vbfMass_JetHFyearDown = 'vbfVariables("userCand(\'jesHFyear-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesHFyear-\').pt() > 50)", 0.5).mass',
        jetVeto30_JetHFyearUp = 'vetoJets(0.5, "userCand(\'jesHFyear+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesHFyear+\').pt > 50)").size()',
        jetVeto30_JetHFyearDown = 'vetoJets(0.5, "userCand(\'jesHFyear-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesHFyear-\').pt > 50)").size()',
        vbfMass_JetRelativeSampleUp = 'vbfVariables("userCand(\'jesRelativeSample+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeSample+\').pt() > 50)", 0.5).mass',
        vbfMass_JetRelativeSampleDown = 'vbfVariables("userCand(\'jesRelativeSample-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeSample-\').pt() > 50)", 0.5).mass',
        jetVeto30_JetRelativeSampleUp = 'vetoJets(0.5, "userCand(\'jesRelativeSample+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeSample+\').pt > 50)").size()',
        jetVeto30_JetRelativeSampleDown = 'vetoJets(0.5, "userCand(\'jesRelativeSample-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeSample-\').pt > 50)").size()',
        vbfMass_JetRelativeBalUp = 'vbfVariables("userCand(\'jesRelativeBal+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeBal+\').pt() > 50)", 0.5).mass',
        vbfMass_JetRelativeBalDown = 'vbfVariables("userCand(\'jesRelativeBal-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeBal-\').pt() > 50)", 0.5).mass',
        jetVeto30_JetRelativeBalUp = 'vetoJets(0.5, "userCand(\'jesRelativeBal+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeBal+\').pt > 50)").size()',
        jetVeto30_JetRelativeBalDown = 'vetoJets(0.5, "userCand(\'jesRelativeBal-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeBal-\').pt > 50)").size()',

        vbfMassWoNoisyJets_JetRelativeBalUp = 'vbfVariables("(userCand(\'jesRelativeBal+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeBal+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeBal+\').pt() > 50)", 0.5).mass',
        vbfMassWoNoisyJets_JetRelativeBalDown = 'vbfVariables("(userCand(\'jesRelativeBal-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeBal-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeBal-\').pt() > 50)", 0.5).mass',
        jetVeto30WoNoisyJets_JetRelativeBalUpWoNoisyJets = 'vetoJets(0.5, "(userCand(\'jesRelativeBal+\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeBal+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeBal+\').pt > 50)").size()',
        jetVeto30WoNoisyJets_JetRelativeBalDownWoNoisyJets = 'vetoJets(0.5, "(userCand(\'jesRelativeBal-\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeBal-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeBal-\').pt > 50)").size()',
        vbfMassWoNoisyJets_JetTotalUp = 'vbfVariables("(userCand(\'jesTotal+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesTotal+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesTotal+\').pt() > 50)", 0.5).mass',
        vbfMassWoNoisyJets_JetTotalDown = 'vbfVariables("(userCand(\'jesTotal-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesTotal-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesTotal-\').pt() > 50)", 0.5).mass',
        jetVeto30WoNoisyJets_JetTotalUp = 'vetoJets(0.5, "(userCand(\'jesTotal+\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesTotal+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesTotal+\').pt > 50)").size()',
        jetVeto30WoNoisyJets_JetTotalDown = 'vetoJets(0.5, "(userCand(\'jesTotal-\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesTotal-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesTotal-\').pt > 50)").size()',
        vbfMassWoNoisyJets_JetEC2Up = 'vbfVariables("(userCand(\'jesEC2+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesEC2+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesEC2+\').pt() > 50)", 0.5).mass',
        vbfMassWoNoisyJets_JetEC2Down = 'vbfVariables("(userCand(\'jesEC2-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesEC2-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesEC2-\').pt() > 50)", 0.5).mass',
        jetVeto30WoNoisyJets_JetEC2Up = 'vetoJets(0.5, "(userCand(\'jesEC2+\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesEC2+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesEC2+\').pt > 50)").size()',
        jetVeto30WoNoisyJets_JetEC2Down = 'vetoJets(0.5, "(userCand(\'jesEC2-\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesEC2-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesEC2-\').pt > 50)").size()',
        vbfMassWoNoisyJets_JetAbsoluteUp = 'vbfVariables("(userCand(\'jesAbsolute+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesAbsolute+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesAbsolute+\').pt() > 50)", 0.5).mass',
        vbfMassWoNoisyJets_JetAbsoluteDown = 'vbfVariables("(userCand(\'jesAbsolute-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesAbsolute-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesAbsolute-\').pt() > 50)", 0.5).mass',
        jetVeto30WoNoisyJets_JetAbsoluteUp = 'vetoJets(0.5, "(userCand(\'jesAbsolute+\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesAbsolute+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesAbsolute+\').pt > 50)").size()',
        jetVeto30WoNoisyJets_JetAbsoluteDown = 'vetoJets(0.5, "(userCand(\'jesAbsolute-\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesAbsolute-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesAbsolute-\').pt > 50)").size()',
        vbfMassWoNoisyJets_JetAbsoluteyearUp = 'vbfVariables("(userCand(\'jesAbsoluteyear+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesAbsoluteyear+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesAbsoluteyear+\').pt() > 50)", 0.5).mass',
        vbfMassWoNoisyJets_JetAbsoluteyearDown = 'vbfVariables("(userCand(\'jesAbsoluteyear-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesAbsoluteyear-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesAbsoluteyear-\').pt() > 50)", 0.5).mass',
        jetVeto30WoNoisyJets_JetAbsoluteyearUp = 'vetoJets(0.5, "(userCand(\'jesAbsoluteyear+\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesAbsoluteyear+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesAbsoluteyear+\').pt > 50)").size()',
        jetVeto30WoNoisyJets_JetAbsoluteyearDown = 'vetoJets(0.5, "(userCand(\'jesAbsoluteyear-\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesAbsoluteyear-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesAbsoluteyear-\').pt > 50)").size()',
        vbfMassWoNoisyJets_JetFlavorQCDUp = 'vbfVariables("(userCand(\'jesFlavorQCD+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesFlavorQCD+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesFlavorQCD+\').pt() > 50)", 0.5).mass',
        vbfMassWoNoisyJets_JetFlavorQCDDown = 'vbfVariables("(userCand(\'jesFlavorQCD-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesFlavorQCD-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesFlavorQCD-\').pt() > 50)", 0.5).mass',
        jetVeto30WoNoisyJets_JetFlavorQCDUp = 'vetoJets(0.5, "(userCand(\'jesFlavorQCD+\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesFlavorQCD+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesFlavorQCD+\').pt > 50)").size()',
        jetVeto30WoNoisyJets_JetFlavorQCDDown = 'vetoJets(0.5, "(userCand(\'jesFlavorQCD-\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesFlavorQCD-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesFlavorQCD-\').pt > 50)").size()',
        vbfMassWoNoisyJets_JetBBEC1Up = 'vbfVariables("(userCand(\'jesBBEC1+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesBBEC1+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesBBEC1+\').pt() > 50)", 0.5).mass',
        vbfMassWoNoisyJets_JetBBEC1Down = 'vbfVariables("(userCand(\'jesBBEC1-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesBBEC1-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesBBEC1-\').pt() > 50)", 0.5).mass',
        jetVeto30WoNoisyJets_JetBBEC1Up = 'vetoJets(0.5, "(userCand(\'jesBBEC1+\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesBBEC1+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesBBEC1+\').pt > 50)").size()',
        jetVeto30WoNoisyJets_JetBBEC1Down = 'vetoJets(0.5, "(userCand(\'jesBBEC1-\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesBBEC1-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesBBEC1-\').pt > 50)").size()',
        vbfMassWoNoisyJets_JetHFUp = 'vbfVariables("(userCand(\'jesHF+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesHF+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesHF+\').pt() > 50)", 0.5).mass',
        vbfMassWoNoisyJets_JetHFDown = 'vbfVariables("(userCand(\'jesHF-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesHF-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesHF-\').pt() > 50)", 0.5).mass',
        jetVeto30WoNoisyJets_JetHFUp = 'vetoJets(0.5, "(userCand(\'jesHF+\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesHF+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesHF+\').pt > 50)").size()',
        jetVeto30WoNoisyJets_JetHFDown = 'vetoJets(0.5, "(userCand(\'jesHF-\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesHF-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesHF-\').pt > 50)").size()',
        vbfMassWoNoisyJets_JetBBEC1yearUp = 'vbfVariables("(userCand(\'jesBBEC1year+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesBBEC1year+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesBBEC1year+\').pt() > 50)", 0.5).mass',
        vbfMassWoNoisyJets_JetBBEC1yearDown = 'vbfVariables("(userCand(\'jesBBEC1year-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesBBEC1year-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesBBEC1year-\').pt() > 50)", 0.5).mass',
        jetVeto30WoNoisyJets_JetBBEC1yearUp = 'vetoJets(0.5, "(userCand(\'jesBBEC1year+\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesBBEC1year+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesBBEC1year+\').pt > 50)").size()',
        jetVeto30WoNoisyJets_JetBBEC1yearDown = 'vetoJets(0.5, "(userCand(\'jesBBEC1year-\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesBBEC1year-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesBBEC1year-\').pt > 50)").size()',
        vbfMassWoNoisyJets_JetEC2yearUp = 'vbfVariables("(userCand(\'jesEC2year+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesEC2year+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesEC2year+\').pt() > 50)", 0.5).mass',
        vbfMassWoNoisyJets_JetEC2yearDown = 'vbfVariables("(userCand(\'jesEC2year-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesEC2year-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesEC2year-\').pt() > 50)", 0.5).mass',
        jetVeto30WoNoisyJets_JetEC2yearUp = 'vetoJets(0.5, "(userCand(\'jesEC2year+\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesEC2year+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesEC2year+\').pt > 50)").size()',
        jetVeto30WoNoisyJets_JetEC2yearDown = 'vetoJets(0.5, "(userCand(\'jesEC2year-\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesEC2year-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesEC2year-\').pt > 50)").size()',
        vbfMassWoNoisyJets_JetHFyearUp = 'vbfVariables("(userCand(\'jesHFyear+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesHFyear+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesHFyear+\').pt() > 50)", 0.5).mass',
        vbfMassWoNoisyJets_JetHFyearDown = 'vbfVariables("(userCand(\'jesHFyear-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesHFyear-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesHFyear-\').pt() > 50)", 0.5).mass',
        jetVeto30WoNoisyJets_JetHFyearUp = 'vetoJets(0.5, "(userCand(\'jesHFyear+\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesHFyear+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesHFyear+\').pt > 50)").size()',
        jetVeto30WoNoisyJets_JetHFyearDown = 'vetoJets(0.5, "(userCand(\'jesHFyear-\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesHFyear-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesHFyear-\').pt > 50)").size()',
        vbfMassWoNoisyJets_JetRelativeSampleUp = 'vbfVariables("(userCand(\'jesRelativeSample+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeSample+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeSample+\').pt() > 50)", 0.5).mass',
        vbfMassWoNoisyJets_JetRelativeSampleDown = 'vbfVariables("(userCand(\'jesRelativeSample-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeSample-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeSample-\').pt() > 50)", 0.5).mass',
        jetVeto30WoNoisyJets_JetRelativeSampleUp = 'vetoJets(0.5, "(userCand(\'jesRelativeSample+\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeSample+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeSample+\').pt > 50)").size()',
        jetVeto30WoNoisyJets_JetRelativeSampleDown = 'vetoJets(0.5, "(userCand(\'jesRelativeSample-\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeSample-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeSample-\').pt > 50)").size()',

        j1ptWoNoisyJets_JetRelativeSampleDown = 'jetVariables("(userCand(\'jesRelativeSample-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeSample-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeSample-\').pt() > 50)", 0.5).at(0)',
        j1ptWoNoisyJets_JetRelativeBalDown = 'jetVariables("(userCand(\'jesRelativeBal-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeBal-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeBal-\').pt() > 50)", 0.5).at(0)',
        j1ptWoNoisyJets_JetRelativeSampleUp = 'jetVariables("(userCand(\'jesRelativeSample+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeSample+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeSample+\').pt() > 50)", 0.5).at(0)',
        j1ptWoNoisyJets_JetRelativeBalUp = 'jetVariables("(userCand(\'jesRelativeBal+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeBal+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeBal+\').pt() > 50)", 0.5).at(0)',
        j1ptWoNoisyJets_JetEC2Down = 'jetVariables("(userCand(\'jesJetEC2-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetEC2-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetEC2-\').pt() > 50)", 0.5).at(0)',
        j1ptWoNoisyJets_JetEC2Up = 'jetVariables("(userCand(\'jesJetEC2+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetEC2+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetEC2+\').pt() > 50)", 0.5).at(0)',
        j1ptWoNoisyJets_JetAbsoluteDown = 'jetVariables("(userCand(\'jesJetAbsolute-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetAbsolute-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetAbsolute-\').pt() > 50)", 0.5).at(0)',
        j1ptWoNoisyJets_JetAbsoluteUp = 'jetVariables("(userCand(\'jesJetAbsolute+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetAbsolute+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetAbsolute+\').pt() > 50)", 0.5).at(0)',
        j1ptWoNoisyJets_JetAbsoluteyearDown = 'jetVariables("(userCand(\'jesJetAbsoluteyear-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetAbsoluteyear-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetAbsoluteyear-\').pt() > 50)", 0.5).at(0)',
        j1ptWoNoisyJets_JetAbsoluteyearUp = 'jetVariables("(userCand(\'jesJetAbsoluteyear+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetAbsoluteyear+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetAbsoluteyear+\').pt() > 50)", 0.5).at(0)',
        j1ptWoNoisyJets_JetFlavorQCDDown = 'jetVariables("(userCand(\'jesJetFlavorQCD-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetFlavorQCD-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetFlavorQCD-\').pt() > 50)", 0.5).at(0)',
        j1ptWoNoisyJets_JetFlavorQCDUp = 'jetVariables("(userCand(\'jesJetFlavorQCD+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetFlavorQCD+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetFlavorQCD+\').pt() > 50)", 0.5).at(0)',
        j1ptWoNoisyJets_JetBBEC1Down = 'jetVariables("(userCand(\'jesJetBBEC1-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetBBEC1-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetBBEC1-\').pt() > 50)", 0.5).at(0)',
        j1ptWoNoisyJets_JetBBEC1Up = 'jetVariables("(userCand(\'jesJetBBEC1+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetBBEC1+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetBBEC1+\').pt() > 50)", 0.5).at(0)',
        j1ptWoNoisyJets_JetHFDown = 'jetVariables("(userCand(\'jesJetHF-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetHF-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetHF-\').pt() > 50)", 0.5).at(0)',
        j1ptWoNoisyJets_JetHFUp = 'jetVariables("(userCand(\'jesJetHF+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetHF+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetHF+\').pt() > 50)", 0.5).at(0)',
        j1ptWoNoisyJets_JetBBEC1yearDown = 'jetVariables("(userCand(\'jesJetBBEC1year-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetBBEC1year-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetBBEC1year-\').pt() > 50)", 0.5).at(0)',
        j1ptWoNoisyJets_JetBBEC1yearUp = 'jetVariables("(userCand(\'jesJetBBEC1year+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetBBEC1year+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetBBEC1year+\').pt() > 50)", 0.5).at(0)',
        j1ptWoNoisyJets_JetEC2yearDown = 'jetVariables("(userCand(\'jesJetEC2year-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetEC2year-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetEC2year-\').pt() > 50)", 0.5).at(0)',
        j1ptWoNoisyJets_JetEC2yearUp = 'jetVariables("(userCand(\'jesJetEC2year+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetEC2year+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetEC2year+\').pt() > 50)", 0.5).at(0)',
        j1ptWoNoisyJets_JetHFyearDown = 'jetVariables("(userCand(\'jesJetHFyear-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetHFyear-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetHFyear-\').pt() > 50)", 0.5).at(0)',
        j1ptWoNoisyJets_JetHFyearUp = 'jetVariables("(userCand(\'jesJetHFyear+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetHFyear+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetHFyear+\').pt() > 50)", 0.5).at(0)',

        j1pt_JetRelativeSampleDown = 'jetVariables("userCand(\'jesRelativeSample-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeSample-\').pt() > 50)", 0.5).at(0)',
        j1pt_JetRelativeBalDown = 'jetVariables("userCand(\'jesRelativeBal-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeBal-\').pt() > 50)", 0.5).at(0)',
        j1pt_JetRelativeSampleUp = 'jetVariables("userCand(\'jesRelativeSample+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeSample+\').pt() > 50)", 0.5).at(0)',
        j1pt_JetRelativeBalUp = 'jetVariables("userCand(\'jesRelativeBal+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeBal+\').pt() > 50)", 0.5).at(0)',
        j1pt_JetEC2Down = 'jetVariables("userCand(\'jesJetEC2-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetEC2-\').pt() > 50)", 0.5).at(0)',
        j1pt_JetEC2Up = 'jetVariables("userCand(\'jesJetEC2+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetEC2+\').pt() > 50)", 0.5).at(0)',
        j1pt_JetAbsoluteDown = 'jetVariables("userCand(\'jesJetAbsolute-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetAbsolute-\').pt() > 50)", 0.5).at(0)',
        j1pt_JetAbsoluteUp = 'jetVariables("userCand(\'jesJetAbsolute+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetAbsolute+\').pt() > 50)", 0.5).at(0)',
        j1pt_JetAbsoluteyearDown = 'jetVariables("userCand(\'jesJetAbsoluteyear-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetAbsoluteyear-\').pt() > 50)", 0.5).at(0)',
        j1pt_JetAbsoluteyearUp = 'jetVariables("userCand(\'jesJetAbsoluteyear+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetAbsoluteyear+\').pt() > 50)", 0.5).at(0)',
        j1pt_JetFlavorQCDDown = 'jetVariables("userCand(\'jesJetFlavorQCD-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetFlavorQCD-\').pt() > 50)", 0.5).at(0)',
        j1pt_JetFlavorQCDUp = 'jetVariables("userCand(\'jesJetFlavorQCD+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetFlavorQCD+\').pt() > 50)", 0.5).at(0)',
        j1pt_JetBBEC1Down = 'jetVariables("userCand(\'jesJetBBEC1-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetBBEC1-\').pt() > 50)", 0.5).at(0)',
        j1pt_JetBBEC1Up = 'jetVariables("userCand(\'jesJetBBEC1+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetBBEC1+\').pt() > 50)", 0.5).at(0)',
        j1pt_JetHFDown = 'jetVariables("userCand(\'jesJetHF-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetHF-\').pt() > 50)", 0.5).at(0)',
        j1pt_JetHFUp = 'jetVariables("userCand(\'jesJetHF+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetHF+\').pt() > 50)", 0.5).at(0)',
        j1pt_JetBBEC1yearDown = 'jetVariables("userCand(\'jesJetBBEC1year-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetBBEC1year-\').pt() > 50)", 0.5).at(0)',
        j1pt_JetBBEC1yearUp = 'jetVariables("userCand(\'jesJetBBEC1year+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetBBEC1year+\').pt() > 50)", 0.5).at(0)',
        j1pt_JetEC2yearDown = 'jetVariables("userCand(\'jesJetEC2year-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetEC2year-\').pt() > 50)", 0.5).at(0)',
        j1pt_JetEC2yearUp = 'jetVariables("userCand(\'jesJetEC2year+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetEC2year+\').pt() > 50)", 0.5).at(0)',
        j1pt_JetHFyearDown = 'jetVariables("userCand(\'jesJetHFyear-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetHFyear-\').pt() > 50)", 0.5).at(0)',
        j1pt_JetHFyearUp = 'jetVariables("userCand(\'jesJetHFyear+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetHFyear+\').pt() > 50)", 0.5).at(0)',

        j2ptWoNoisyJets_JetRelativeSampleDown = 'jetVariables("(userCand(\'jesRelativeSample-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeSample-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeSample-\').pt() > 50)", 0.5).at(10)',
        j2ptWoNoisyJets_JetRelativeBalDown = 'jetVariables("(userCand(\'jesRelativeBal-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeBal-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeBal-\').pt() > 50)", 0.5).at(10)',
        j2ptWoNoisyJets_JetRelativeSampleUp = 'jetVariables("(userCand(\'jesRelativeSample+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeSample+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeSample+\').pt() > 50)", 0.5).at(10)',
        j2ptWoNoisyJets_JetRelativeBalUp = 'jetVariables("(userCand(\'jesRelativeBal+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeBal+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeBal+\').pt() > 50)", 0.5).at(10)',
        j2ptWoNoisyJets_JetEC2Down = 'jetVariables("(userCand(\'jesJetEC2-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetEC2-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetEC2-\').pt() > 50)", 0.5).at(10)',
        j2ptWoNoisyJets_JetEC2Up = 'jetVariables("(userCand(\'jesJetEC2+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetEC2+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetEC2+\').pt() > 50)", 0.5).at(10)',
        j2ptWoNoisyJets_JetAbsoluteDown = 'jetVariables("(userCand(\'jesJetAbsolute-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetAbsolute-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetAbsolute-\').pt() > 50)", 0.5).at(10)',
        j2ptWoNoisyJets_JetAbsoluteUp = 'jetVariables("(userCand(\'jesJetAbsolute+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetAbsolute+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetAbsolute+\').pt() > 50)", 0.5).at(10)',
        j2ptWoNoisyJets_JetAbsoluteyearDown = 'jetVariables("(userCand(\'jesJetAbsoluteyear-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetAbsoluteyear-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetAbsoluteyear-\').pt() > 50)", 0.5).at(10)',
        j2ptWoNoisyJets_JetAbsoluteyearUp = 'jetVariables("(userCand(\'jesJetAbsoluteyear+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetAbsoluteyear+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetAbsoluteyear+\').pt() > 50)", 0.5).at(10)',
        j2ptWoNoisyJets_JetFlavorQCDDown = 'jetVariables("(userCand(\'jesJetFlavorQCD-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetFlavorQCD-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetFlavorQCD-\').pt() > 50)", 0.5).at(10)',
        j2ptWoNoisyJets_JetFlavorQCDUp = 'jetVariables("(userCand(\'jesJetFlavorQCD+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetFlavorQCD+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetFlavorQCD+\').pt() > 50)", 0.5).at(10)',
        j2ptWoNoisyJets_JetBBEC1Down = 'jetVariables("(userCand(\'jesJetBBEC1-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetBBEC1-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetBBEC1-\').pt() > 50)", 0.5).at(10)',
        j2ptWoNoisyJets_JetBBEC1Up = 'jetVariables("(userCand(\'jesJetBBEC1+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetBBEC1+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetBBEC1+\').pt() > 50)", 0.5).at(10)',
        j2ptWoNoisyJets_JetHFDown = 'jetVariables("(userCand(\'jesJetHF-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetHF-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetHF-\').pt() > 50)", 0.5).at(10)',
        j2ptWoNoisyJets_JetHFUp = 'jetVariables("(userCand(\'jesJetHF+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetHF+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetHF+\').pt() > 50)", 0.5).at(10)',
        j2ptWoNoisyJets_JetBBEC1yearDown = 'jetVariables("(userCand(\'jesJetBBEC1year-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetBBEC1year-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetBBEC1year-\').pt() > 50)", 0.5).at(10)',
        j2ptWoNoisyJets_JetBBEC1yearUp = 'jetVariables("(userCand(\'jesJetBBEC1year+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetBBEC1year+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetBBEC1year+\').pt() > 50)", 0.5).at(10)',
        j2ptWoNoisyJets_JetEC2yearDown = 'jetVariables("(userCand(\'jesJetEC2year-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetEC2year-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetEC2year-\').pt() > 50)", 0.5).at(10)',
        j2ptWoNoisyJets_JetEC2yearUp = 'jetVariables("(userCand(\'jesJetEC2year+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetEC2year+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetEC2year+\').pt() > 50)", 0.5).at(10)',
        j2ptWoNoisyJets_JetHFyearDown = 'jetVariables("(userCand(\'jesJetHFyear-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetHFyear-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetHFyear-\').pt() > 50)", 0.5).at(10)',
        j2ptWoNoisyJets_JetHFyearUp = 'jetVariables("(userCand(\'jesJetHFyear+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetHFyear+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetHFyear+\').pt() > 50)", 0.5).at(10)',

        j2pt_JetRelativeSampleDown = 'jetVariables("userCand(\'jesRelativeSample-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeSample-\').pt() > 50)", 0.5).at(10)',
        j2pt_JetRelativeBalDown = 'jetVariables("userCand(\'jesRelativeBal-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeBal-\').pt() > 50)", 0.5).at(10)',
        j2pt_JetRelativeSampleUp = 'jetVariables("userCand(\'jesRelativeSample+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeSample+\').pt() > 50)", 0.5).at(10)',
        j2pt_JetRelativeBalUp = 'jetVariables("userCand(\'jesRelativeBal+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesRelativeBal+\').pt() > 50)", 0.5).at(10)',
        j2pt_JetEC2Down = 'jetVariables("userCand(\'jesJetEC2-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetEC2-\').pt() > 50)", 0.5).at(10)',
        j2pt_JetEC2Up = 'jetVariables("userCand(\'jesJetEC2+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetEC2+\').pt() > 50)", 0.5).at(10)',
        j2pt_JetAbsoluteDown = 'jetVariables("userCand(\'jesJetAbsolute-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetAbsolute-\').pt() > 50)", 0.5).at(10)',
        j2pt_JetAbsoluteUp = 'jetVariables("userCand(\'jesJetAbsolute+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetAbsolute+\').pt() > 50)", 0.5).at(10)',
        j2pt_JetAbsoluteyearDown = 'jetVariables("userCand(\'jesJetAbsoluteyear-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetAbsoluteyear-\').pt() > 50)", 0.5).at(10)',
        j2pt_JetAbsoluteyearUp = 'jetVariables("userCand(\'jesJetAbsoluteyear+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetAbsoluteyear+\').pt() > 50)", 0.5).at(10)',
        j2pt_JetFlavorQCDDown = 'jetVariables("userCand(\'jesJetFlavorQCD-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetFlavorQCD-\').pt() > 50)", 0.5).at(10)',
        j2pt_JetFlavorQCDUp = 'jetVariables("userCand(\'jesJetFlavorQCD+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetFlavorQCD+\').pt() > 50)", 0.5).at(10)',
        j2pt_JetBBEC1Down = 'jetVariables("userCand(\'jesJetBBEC1-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetBBEC1-\').pt() > 50)", 0.5).at(10)',
        j2pt_JetBBEC1Up = 'jetVariables("userCand(\'jesJetBBEC1+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetBBEC1+\').pt() > 50)", 0.5).at(10)',
        j2pt_JetHFDown = 'jetVariables("userCand(\'jesJetHF-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetHF-\').pt() > 50)", 0.5).at(10)',
        j2pt_JetHFUp = 'jetVariables("userCand(\'jesJetHF+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetHF+\').pt() > 50)", 0.5).at(10)',
        j2pt_JetBBEC1yearDown = 'jetVariables("userCand(\'jesJetBBEC1year-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetBBEC1year-\').pt() > 50)", 0.5).at(10)',
        j2pt_JetBBEC1yearUp = 'jetVariables("userCand(\'jesJetBBEC1year+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetBBEC1year+\').pt() > 50)", 0.5).at(10)',
        j2pt_JetEC2yearDown = 'jetVariables("userCand(\'jesJetEC2year-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetEC2year-\').pt() > 50)", 0.5).at(10)',
        j2pt_JetEC2yearUp = 'jetVariables("userCand(\'jesJetEC2year+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetEC2year+\').pt() > 50)", 0.5).at(10)',
        j2pt_JetHFyearDown = 'jetVariables("userCand(\'jesJetHFyear-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetHFyear-\').pt() > 50)", 0.5).at(10)',
        j2pt_JetHFyearUp = 'jetVariables("userCand(\'jesJetHFyear+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userCand(\'jesJetHFyear+\').pt() > 50)", 0.5).at(10)',


        deepcsvb1_pt_JetRelativeSampleDown = 'deepCSVJetVariables("userCand(\'jesRelativeSample-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetRelativeBalDown = 'deepCSVJetVariables("userCand(\'jesRelativeBal-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetEC2Down = 'deepCSVJetVariables("userCand(\'jesJetEC2-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetAbsoluteDown = 'deepCSVJetVariables("userCand(\'jesJetAbsolute-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetAbsoluteyearDown = 'deepCSVJetVariables("userCand(\'jesJetAbsoluteyear-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetFlavorQCDDown = 'deepCSVJetVariables("userCand(\'jesJetFlavorQCD-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetBBEC1Down = 'deepCSVJetVariables("userCand(\'jesJetBBEC1-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetHFDown = 'deepCSVJetVariables("userCand(\'jesJetHF-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetBBEC1yearDown = 'deepCSVJetVariables("userCand(\'jesJetBBEC1year-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetEC2yearDown = 'deepCSVJetVariables("userCand(\'jesJetEC2year-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetHFyearDown = 'deepCSVJetVariables("userCand(\'jesJetHFyear-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetTotalDown = 'deepCSVJetVariables("userCand(\'jesJetTotal-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JERDown = 'deepCSVJetVariables("userCand(\'jer-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetRelativeSampleUp = 'deepCSVJetVariables("userCand(\'jesRelativeSample+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetRelativeBalUp = 'deepCSVJetVariables("userCand(\'jesRelativeBal+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetEC2Up = 'deepCSVJetVariables("userCand(\'jesJetEC2+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetAbsoluteUp = 'deepCSVJetVariables("userCand(\'jesJetAbsolute+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetAbsoluteyearUp = 'deepCSVJetVariables("userCand(\'jesJetAbsoluteyear+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetFlavorQCDUp = 'deepCSVJetVariables("userCand(\'jesJetFlavorQCD+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetBBEC1Up = 'deepCSVJetVariables("userCand(\'jesJetBBEC1+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetHFUp = 'deepCSVJetVariables("userCand(\'jesJetHF+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetBBEC1yearUp = 'deepCSVJetVariables("userCand(\'jesJetBBEC1year+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetEC2yearUp = 'deepCSVJetVariables("userCand(\'jesJetEC2year+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetHFyearUp = 'deepCSVJetVariables("userCand(\'jesJetHFyear+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetTotalUp = 'deepCSVJetVariables("userCand(\'jesJetTotal+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JERUp = 'deepCSVJetVariables("userCand(\'jer+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',

        deepcsvb2_pt_JetRelativeSampleDown = 'deepCSVJetVariables("userCand(\'jesRelativeSample-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetRelativeBalDown = 'deepCSVJetVariables("userCand(\'jesRelativeBal-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetEC2Down = 'deepCSVJetVariables("userCand(\'jesJetEC2-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetAbsoluteDown = 'deepCSVJetVariables("userCand(\'jesJetAbsolute-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetAbsoluteyearDown = 'deepCSVJetVariables("userCand(\'jesJetAbsoluteyear-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetFlavorQCDDown = 'deepCSVJetVariables("userCand(\'jesJetFlavorQCD-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetBBEC1Down = 'deepCSVJetVariables("userCand(\'jesJetBBEC1-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetHFDown = 'deepCSVJetVariables("userCand(\'jesJetHF-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetBBEC1yearDown = 'deepCSVJetVariables("userCand(\'jesJetBBEC1year-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetEC2yearDown = 'deepCSVJetVariables("userCand(\'jesJetEC2year-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetHFyearDown = 'deepCSVJetVariables("userCand(\'jesJetHFyear-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetTotalDown = 'deepCSVJetVariables("userCand(\'jesJetTotal-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JERDown = 'deepCSVJetVariables("userCand(\'jer-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetRelativeSampleUp = 'deepCSVJetVariables("userCand(\'jesRelativeSample+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetRelativeBalUp = 'deepCSVJetVariables("userCand(\'jesRelativeBal+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetEC2Up = 'deepCSVJetVariables("userCand(\'jesJetEC2+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetAbsoluteUp = 'deepCSVJetVariables("userCand(\'jesJetAbsolute+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetAbsoluteyearUp = 'deepCSVJetVariables("userCand(\'jesJetAbsoluteyear+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetFlavorQCDUp = 'deepCSVJetVariables("userCand(\'jesJetFlavorQCD+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetBBEC1Up = 'deepCSVJetVariables("userCand(\'jesJetBBEC1+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetHFUp = 'deepCSVJetVariables("userCand(\'jesJetHF+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetBBEC1yearUp = 'deepCSVJetVariables("userCand(\'jesJetBBEC1year+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetEC2yearUp = 'deepCSVJetVariables("userCand(\'jesJetEC2year+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetHFyearUp = 'deepCSVJetVariables("userCand(\'jesJetHFyear+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetTotalUp = 'deepCSVJetVariables("userCand(\'jesJetTotal+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JERUp = 'deepCSVJetVariables("userCand(\'jer+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',

        #deepflavourb1_pt_JetRelativeSampleDown = 'deepFlavourJetVariables("userCand(\'jesRelativeSample-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetRelativeBalDown = 'deepFlavourJetVariables("userCand(\'jesRelativeBal-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetEC2Down = 'deepFlavourJetVariables("userCand(\'jesJetEC2-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetAbsoluteDown = 'deepFlavourJetVariables("userCand(\'jesJetAbsolute-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetAbsoluteyearDown = 'deepFlavourJetVariables("userCand(\'jesJetAbsoluteyear-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetFlavorQCDDown = 'deepFlavourJetVariables("userCand(\'jesJetFlavorQCD-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetBBEC1Down = 'deepFlavourJetVariables("userCand(\'jesJetBBEC1-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetHFDown = 'deepFlavourJetVariables("userCand(\'jesJetHF-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetBBEC1yearDown = 'deepFlavourJetVariables("userCand(\'jesJetBBEC1year-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetEC2yearDown = 'deepFlavourJetVariables("userCand(\'jesJetEC2year-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetHFyearDown = 'deepFlavourJetVariables("userCand(\'jesJetHFyear-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetTotalDown = 'deepFlavourJetVariables("userCand(\'jesJetTotal-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JERDown = 'deepFlavourJetVariables("userCand(\'jer-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetRelativeSampleUp = 'deepFlavourJetVariables("userCand(\'jesRelativeSample+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetRelativeBalUp = 'deepFlavourJetVariables("userCand(\'jesRelativeBal+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetEC2Up = 'deepFlavourJetVariables("userCand(\'jesJetEC2+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetAbsoluteUp = 'deepFlavourJetVariables("userCand(\'jesJetAbsolute+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetAbsoluteyearUp = 'deepFlavourJetVariables("userCand(\'jesJetAbsoluteyear+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetFlavorQCDUp = 'deepFlavourJetVariables("userCand(\'jesJetFlavorQCD+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetBBEC1Up = 'deepFlavourJetVariables("userCand(\'jesJetBBEC1+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetHFUp = 'deepFlavourJetVariables("userCand(\'jesJetHF+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetBBEC1yearUp = 'deepFlavourJetVariables("userCand(\'jesJetBBEC1year+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetEC2yearUp = 'deepFlavourJetVariables("userCand(\'jesJetEC2year+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetHFyearUp = 'deepFlavourJetVariables("userCand(\'jesJetHFyear+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetTotalUp = 'deepFlavourJetVariables("userCand(\'jesJetTotal+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JERUp = 'deepFlavourJetVariables("userCand(\'jer+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',

        #deepflavourb2_pt_JetRelativeSampleDown = 'deepFlavourJetVariables("userCand(\'jesRelativeSample-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetRelativeBalDown = 'deepFlavourJetVariables("userCand(\'jesRelativeBal-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetEC2Down = 'deepFlavourJetVariables("userCand(\'jesJetEC2-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetAbsoluteDown = 'deepFlavourJetVariables("userCand(\'jesJetAbsolute-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetAbsoluteyearDown = 'deepFlavourJetVariables("userCand(\'jesJetAbsoluteyear-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetFlavorQCDDown = 'deepFlavourJetVariables("userCand(\'jesJetFlavorQCD-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetBBEC1Down = 'deepFlavourJetVariables("userCand(\'jesJetBBEC1-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetHFDown = 'deepFlavourJetVariables("userCand(\'jesJetHF-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetBBEC1yearDown = 'deepFlavourJetVariables("userCand(\'jesJetBBEC1year-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetEC2yearDown = 'deepFlavourJetVariables("userCand(\'jesJetEC2year-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetHFyearDown = 'deepFlavourJetVariables("userCand(\'jesJetHFyear-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetTotalDown = 'deepFlavourJetVariables("userCand(\'jesJetTotal-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JERDown = 'deepFlavourJetVariables("userCand(\'jer-\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetRelativeSampleUp = 'deepFlavourJetVariables("userCand(\'jesRelativeSample+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetRelativeBalUp = 'deepFlavourJetVariables("userCand(\'jesRelativeBal+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetEC2Up = 'deepFlavourJetVariables("userCand(\'jesJetEC2+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetAbsoluteUp = 'deepFlavourJetVariables("userCand(\'jesJetAbsolute+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetAbsoluteyearUp = 'deepFlavourJetVariables("userCand(\'jesJetAbsoluteyear+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetFlavorQCDUp = 'deepFlavourJetVariables("userCand(\'jesJetFlavorQCD+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetBBEC1Up = 'deepFlavourJetVariables("userCand(\'jesJetBBEC1+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetHFUp = 'deepFlavourJetVariables("userCand(\'jesJetHF+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetBBEC1yearUp = 'deepFlavourJetVariables("userCand(\'jesJetBBEC1year+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetEC2yearUp = 'deepFlavourJetVariables("userCand(\'jesJetEC2year+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetHFyearUp = 'deepFlavourJetVariables("userCand(\'jesJetHFyear+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetTotalUp = 'deepFlavourJetVariables("userCand(\'jesJetTotal+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JERUp = 'deepFlavourJetVariables("userCand(\'jer+\').pt() > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',

)

