
'''

Ntuple branch template sets for topological variables (MT, etc)

Each string is transformed into an expression on a FinalStateEvent object.

Author: Evan K. Friis

'''

from FinalStateAnalysis.Utilities.cfgtools import PSet

mtToMET = PSet(
    #objectMtToPfMet_type1   = 'mtMET({object_idx}, "", ""     )',
    #objectDPhiToPfMet_type1 = 'deltaPhiToMEt({object_idx}, "", ""     )',
    ##MVA MET
    #objectMtToMVAMET     = 'mtMET({object_idx}, "", "mvamet", "", 0)',
)

# these things break if you pass a shifted met
shiftedMtToMET = PSet(
    ## Raw means no MET corrections
    #objectMtToPfMet_Raw = 'mtMET({object_idx}, "", "raw")',

    ##PF Type1 MET (and systematics)
    #objectMtToPfMet_JetResUp          = 'mtMET({object_idx}, "", "jres+")',
    #objectMtToPfMet_JetEnUp           = 'mtMET({object_idx}, "", "jes+" )',
    #objectMtToPfMet_MuonEnUp          = 'mtMET({object_idx}, "", "mes+" )',
    #objectMtToPfMet_ElectronEnUp      = 'mtMET({object_idx}, "", "ees+" )',
    #objectMtToPfMet_TauEnUp           = 'mtMET({object_idx}, "tesUpTaus", "tes+" )',
    #objectMtToPfMet_UnclusteredEnUp   = 'mtMET({object_idx}, "", "ues+" )',
    #objectMtToPfMet_PhotonEnUp        = 'mtMET({object_idx}, "", "pes+" )',

    #objectMtToPfMet_JetResDown        = 'mtMET({object_idx}, "", "jres-")',
    #objectMtToPfMet_JetEnDown         = 'mtMET({object_idx}, "", "jes-" )',
    #objectMtToPfMet_MuonEnDown        = 'mtMET({object_idx}, "", "mes-" )',
    #objectMtToPfMet_ElectronEnDown    = 'mtMET({object_idx}, "", "ees-" )',
    #objectMtToPfMet_TauEnDown         = 'mtMET({object_idx}, "tesDownTaus", "tes-" )',
    #objectMtToPfMet_UnclusteredEnDown = 'mtMET({object_idx}, "", "ues-" )',
    #objectMtToPfMet_PhotonEnDown      = 'mtMET({object_idx}, "", "pes-" )',

    #objectDPhiToPfMet_JetResUp          = 'deltaPhiToMEt({object_idx}, "", "jres+")',
    #objectDPhiToPfMet_JetEnUp           = 'deltaPhiToMEt({object_idx}, "", "jes+" )',
    #objectDPhiToPfMet_MuonEnUp          = 'deltaPhiToMEt({object_idx}, "", "mes+" )',
    #objectDPhiToPfMet_ElectronEnUp      = 'deltaPhiToMEt({object_idx}, "", "ees+" )',
    #objectDPhiToPfMet_TauEnUp           = 'deltaPhiToMEt({object_idx}, "", "tes+" )',
    #objectDPhiToPfMet_UnclusteredEnUp   = 'deltaPhiToMEt({object_idx}, "", "ues+" )',
    #objectDPhiToPfMet_PhotonEnUp        = 'deltaPhiToMEt({object_idx}, "", "pes+" )',

    #objectDPhiToPfMet_JetResDown        = 'deltaPhiToMEt({object_idx}, "", "jres-")',
    #objectDPhiToPfMet_JetEnDown         = 'deltaPhiToMEt({object_idx}, "", "jes-" )',
    #objectDPhiToPfMet_MuonEnDown        = 'deltaPhiToMEt({object_idx}, "", "mes-" )',
    #objectDPhiToPfMet_ElectronEnDown    = 'deltaPhiToMEt({object_idx}, "", "ees-" )',
    #objectDPhiToPfMet_TauEnDown         = 'deltaPhiToMEt({object_idx}, "", "tes-" )',
    #objectDPhiToPfMet_UnclusteredEnDown = 'deltaPhiToMEt({object_idx}, "", "ues-" )',
    #objectDPhiToPfMet_PhotonEnDown      = 'deltaPhiToMEt({object_idx}, "", "pes-" )',
)

# Variables based on pairs of objects
pairs = PSet(
    object1_object2_Mass = 'subcand({object1_idx}, {object2_idx}).get.mass',
    #object1_object2_Mt = 'subcand({object1_idx}, {object2_idx}).get.mt',
    #object1_object2_collinearmass = 'collinearMassMET({object1_idx}, "", {object2_idx},"","")',
    #object2_object1_collinearmass = 'collinearMassMET({object2_idx}, "", {object1_idx},"","")',
   
    #object1_object2_Mass_TauEnUp = 'subcand({object1_idx}, "",{object2_idx},"tesUpTaus").get.mass',
    #object1_object2_Mass_TauEnDown = 'subcand({object1_idx}, "",{object2_idx},"tesDownTaus").get.mass',
    #object1_object2_Mt_TauEnUp = 'subcand({object1_idx}, "",{object2_idx},"tesUpTaus").get.mt',
    #object1_object2_Mt_TauEnDown = 'subcand({object1_idx}, "",{object2_idx},"tesDownTaus").get.mt',
 
    #object1_object2_Pt = 'subcand({object1_idx}, {object2_idx}).get.pt',
    #object1_object2_Eta = 'subcand({object1_idx}, {object2_idx}).get.eta',
    #object1_object2_Phi = 'subcand({object1_idx}, {object2_idx}).get.phi',
    object1_object2_DR = 'dR({object1_idx}, {object2_idx})',
    #object1_object2_DPhi = 'dPhi({object1_idx}, {object2_idx})',
    #object1_object2_SS = 'likeSigned({object1_idx}, {object2_idx})',
    object1_object2_PZeta = 'pZeta({object1_idx}, {object2_idx})',
    object1_object2_PZetaVis = 'pZetaVis({object1_idx}, {object2_idx})',
    #object1_object2_CosThetaStar = 'abs(subcand({object1_idx}, {object2_idx}).get.daughterCosThetaStar(0))',

    #object1_object2_collinearmass_JetEnUp = 'collinearMassMET({object1_idx}, "", {object2_idx},"","jes+")',
    #object2_object1_collinearmass_JetEnUp = 'collinearMassMET({object2_idx}, "", {object1_idx},"","jes+")', # for now we only need m_t_coll
    #object1_object2_collinearmass_JetEnDown = 'collinearMassMET({object1_idx}, "", {object2_idx},"","jes-")',
    #object2_object1_collinearmass_JetEnDown = 'collinearMassMET({object2_idx}, "", {object1_idx},"","jes-")',
    #object1_object2_collinearmass_UnclusteredEnUp = 'collinearMassMET({object1_idx}, "", {object2_idx},"","ues+")',
    #object2_object1_collinearmass_UnclusteredEnUp = 'collinearMassMET({object2_idx}, "", {object1_idx},"","ues+")',
    #object1_object2_collinearmass_UnclusteredEnDown = 'collinearMassMET({object1_idx}, "", {object2_idx},"","ues-")',
    #object2_object1_collinearmass_UnclusteredEnDown = 'collinearMassMET({object2_idx}, "", {object1_idx},"","ues-")',
    #object1_object2_collinearmass_TauEnUp = 'collinearMassMET({object1_idx}, "", {object2_idx},"tesUpTaus","tes+")',
    #object1_object2_collinearmass_TauEnDown = 'collinearMassMET({object1_idx}, "", {object2_idx},"tesDownTaus","tes-")',
    #object1_object2_collinearmass_EleEnUp = 'collinearMassMET({object1_idx}, "", {object2_idx},"","ees+")',
    #object1_object2_collinearmass_EleEnDown = 'collinearMassMET({object1_idx}, "", {object2_idx},"","ees-")',
    #object1_object2_collinearmass_MuEnUp = 'collinearMassMET({object1_idx}, "", {object2_idx},"","mes+")',
    #object1_object2_collinearmass_MuEnDown = 'collinearMassMET({object1_idx}, "", {object2_idx},"","mes-")',

    #object1_object2_collinearmass_JetCheckTotalUp = 'collinearMassMET({object1_idx}, "", {object2_idx},"","jesTotal+")',
    #object2_object1_collinearmass_JetCheckTotalUp = 'collinearMassMET({object2_idx}, "", {object1_idx},"","jesTotal+")', # for now we only need m_t_coll
    #object1_object2_collinearmass_JetCheckTotalDown = 'collinearMassMET({object1_idx}, "", {object2_idx},"","jesTotal-")',
    #object2_object1_collinearmass_JetCheckTotalDown = 'collinearMassMET({object2_idx}, "", {object1_idx},"","jesTotal-")',
    #object1_object2_collinearmass_CheckUESUp = 'collinearMassMET({object1_idx}, "", {object2_idx},"","checkUES+")',
    #object2_object1_collinearmass_CheckUESUp = 'collinearMassMET({object2_idx}, "", {object1_idx},"","checkUES+")',
    #object1_object2_collinearmass_CheckUESDown = 'collinearMassMET({object1_idx}, "", {object2_idx},"","checkUES-")',
    #object2_object1_collinearmass_CheckUESDown = 'collinearMassMET({object2_idx}, "", {object1_idx},"","checkUES-")',

    ##Pairs + MET
    #object1_object2_ToMETDPhi_Ty1 = 'twoParticleDeltaPhiToMEt({object1_idx}, {object2_idx}, "type1")',
)

svfit = PSet(
    #object1_object2_SVfitMass = 'SVfit({object1_idx},{object2_idx}).at(0)',
    #object1_object2_SVfitPt = 'SVfit({object1_idx},{object2_idx}).at(1)',
    #object1_object2_SVfitEta = 'SVfit({object1_idx},{object2_idx}).at(2)',
    #object1_object2_SVfitPhi = 'SVfit({object1_idx},{object2_idx}).at(3)',
    #object1_object2_SVfitMET = 'SVfit({object1_idx},{object2_idx}).at(4)',
)

finalstate = PSet(
    LT = 'ht',
    charge = 'charge',
    Pt = 'pt',
    Eta = 'eta',
    Phi = 'phi',
    Mass = 'mass',
    Mt = 'mt',
    Ht = 'jetHt("pt>30 && abs(eta)<2.5")',
    MassError = '? hasUserFloat("cand_dM") ? userFloat("cand_dM") : -999',
    MassErrord1 = '? hasUserFloat("cand_dM_0") ? userFloat("cand_dM_0") : -999',
    MassErrord2 = '? hasUserFloat("cand_dM_1") ? userFloat("cand_dM_1") : -999',
    MassErrord3 = '? hasUserFloat("cand_dM_2") ? userFloat("cand_dM_2") : -999',
    MassErrord4 = '? hasUserFloat("cand_dM_3") ? userFloat("cand_dM_3") : -999',
)


vbf = PSet(
   vbfNJets20 = 'vbfVariables("pt > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).nJets',
   vbfNJets30 = 'vbfVariables("pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).nJets',
   vbfJetVeto30 = 'vbfVariables("pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).jets30',
   vbfJetVeto20 = 'vbfVariables("pt > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).jets20',
   vbfMass = 'vbfVariables("pt > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
   vbfMassWoNoisyJets = 'vbfVariables("(pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & pt > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
   vbfDeta = 'vbfVariables("pt > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).deta',
   vbfj1eta = 'vbfVariables("pt > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).eta1',
   vbfj2eta = 'vbfVariables("pt > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).eta2',
   vbfj1pt = 'vbfVariables("pt > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).pt1',
   vbfj2pt = 'vbfVariables("pt > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).pt2',

)


extraJet = PSet(
    objectPt = '? evt.jets.size()>{object_idx} ? {object}.pt() : -999',
    # objectPtJESTotal_Up = '? evt.jets.size()>{object_idx} ? {object}.userCand(\'jesTotal+\').pt() : -999',
    # objectPtJESTotal_Down = '? evt.jets.size()>{object_idx} ? {object}.userCand(\'jesTotal-\').pt() : -999',
    # objectPtJESEta0to5_Up = '? evt.jets.size()>{object_idx} ? {object}.userCand(\'jesEta0to5+\').pt() : -999',
    # objectPtJESEta0to5_Down = '? evt.jets.size()>{object_idx} ? {object}.userCand(\'jesEta0to5-\').pt() : -999',
    # objectPtJESEta0to3_Up = '? evt.jets.size()>{object_idx} ? {object}.userCand(\'jesEta0to3+\').pt() : -999',
    # objectPtJESEta0to3_Down = '? evt.jets.size()>{object_idx} ? {object}.userCand(\'jesEta0to3-\').pt() : -999',
    # objectPtJESEta3to5_Up = '? evt.jets.size()>{object_idx} ? {object}.userCand(\'jesEta3to5+\').pt() : -999',
    # objectPtJESEta3to5_Down = '? evt.jets.size()>{object_idx} ? {object}.userCand(\'jesEta3to5-\').pt() : -999',
    # objectPtJESRelativeSample_Up = '? evt.jets.size()>{object_idx} ? {object}.userCand(\'jesRelativeSample+\').pt() : -999',
    # objectPtJESRelativeSample_Down = '? evt.jets.size()>{object_idx} ? {object}.userCand(\'jesRelativeSample-\').pt() : -999',
    # objectPtJESRelativeBal_Up = '? evt.jets.size()>{object_idx} ? {object}.userCand(\'jesRelativeBal+\').pt() : -999',
    # objectPtJESRelativeBal_Down = '? evt.jets.size()>{object_idx} ? {object}.userCand(\'jesRelativeBal-\').pt() : -999',
    # objectPtJESClosure_Up = '? evt.jets.size()>{object_idx} ? {object}.userCand(\'jesClosure+\').pt() : -999',
    # objectPtJESClosure_Down = '? evt.jets.size()>{object_idx} ? {object}.userCand(\'jesClosure-\').pt() : -999',
    # objectPtJESClosureNew_Up = '? evt.jets.size()>{object_idx} ? {object}.userCand(\'jesClosureNew+\').pt() : -999',
    # objectPtJESClosureNew_Down = '? evt.jets.size()>{object_idx} ? {object}.userCand(\'jesClosureNew-\').pt() : -999',
    objectEta = '? evt.jets.size()>{object_idx} ? {object}.eta() : -999',
    objectPhi = '? evt.jets.size()>{object_idx} ? {object}.phi() : -999',
    objectIDTight = '? evt.jets.size()>{object_idx} ? {object}.userFloat("idTight") : -999',
    objectIDTightLepVeto = '? evt.jets.size()>{object_idx} ? {object}.userFloat("idTightLepVeto") : -999',
    objectIDLoose = '? evt.jets.size()>{object_idx} ? {object}.userFloat("idLoose") : -999',
    objectPUMVA = '? evt.jets.size()>{object_idx} & {object}.pt()>20 & abs({object}.eta())<2.5 ? {object}.userFloat("pileupJetId:fullDiscriminant") : -999',
    objectBJetCISV = '? evt.jets.size()>{object_idx} & {object}.pt()>20 & abs({object}.eta())<2.5 ? {object}.bDiscriminator(\'pfCombinedInclusiveSecondaryVertexV2BJetTags\') : -999',
)


# Temporary variables for JES study
fullJES = PSet(
        # vbfMass_JetTotalUp = 'vbfVariables("userCand(\'jesTotal+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        # vbfMass_JetTotalDown = 'vbfVariables("userCand(\'jesTotal-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        # jetVeto30_JetTotalUp = 'vetoJets(0.5, "userCand(\'jesTotal+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        # jetVeto30_JetTotalDown = 'vetoJets(0.5, "userCand(\'jesTotal-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        # vbfMass_JetEta0to5Up = 'vbfVariables("userCand(\'jesEta0to5+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        # vbfMass_JetEta0to5Down = 'vbfVariables("userCand(\'jesEta0to5-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        # jetVeto30_JetEta0to5Up = 'vetoJets(0.5, "userCand(\'jesEta0to5+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        # jetVeto30_JetEta0to5Down = 'vetoJets(0.5, "userCand(\'jesEta0to5-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        # vbfMass_JetEta0to3Up = 'vbfVariables("userCand(\'jesEta0to3+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        # vbfMass_JetEta0to3Down = 'vbfVariables("userCand(\'jesEta0to3-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        # jetVeto30_JetEta0to3Up = 'vetoJets(0.5, "userCand(\'jesEta0to3+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        # jetVeto30_JetEta0to3Down = 'vetoJets(0.5, "userCand(\'jesEta0to3-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        # vbfMass_JetEta3to5Up = 'vbfVariables("userCand(\'jesEta3to5+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        # vbfMass_JetEta3to5Down = 'vbfVariables("userCand(\'jesEta3to5-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        # jetVeto30_JetEta3to5Up = 'vetoJets(0.5, "userCand(\'jesEta3to5+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        # jetVeto30_JetEta3to5Down = 'vetoJets(0.5, "userCand(\'jesEta3to5-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        # vbfMass_JetEC2Up = 'vbfVariables("userCand(\'jesEC2+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        # vbfMass_JetEC2Down = 'vbfVariables("userCand(\'jesEC2-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        # jetVeto30_JetEC2Up = 'vetoJets(0.5, "userCand(\'jesEC2+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        # jetVeto30_JetEC2Down = 'vetoJets(0.5, "userCand(\'jesEC2-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        # vbfMass_JetRelativeSampleUp = 'vbfVariables("userCand(\'jesRelativeSample+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        # vbfMass_JetRelativeSampleDown = 'vbfVariables("userCand(\'jesRelativeSample-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        # jetVeto30_JetRelativeSampleUp = 'vetoJets(0.5, "userCand(\'jesRelativeSample+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        # jetVeto30_JetRelativeSampleDown = 'vetoJets(0.5, "userCand(\'jesRelativeSample-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        # vbfMass_JetRelativeBalUp = 'vbfVariables("userCand(\'jesRelativeBal+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        # vbfMass_JetRelativeBalDown = 'vbfVariables("userCand(\'jesRelativeBal-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        # jetVeto30_JetRelativeBalUp = 'vetoJets(0.5, "userCand(\'jesRelativeBal+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        # jetVeto30_JetRelativeBalDown = 'vetoJets(0.5, "userCand(\'jesRelativeBal-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',

        # vbfMassWoNoisyJets_JetRelativeBalUp = 'vbfVariables("(userCand(\'jesRelativeBal+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeBal+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        # vbfMassWoNoisyJets_JetRelativeBalDown = 'vbfVariables("(userCand(\'jesRelativeBal-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeBal-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        # jetVeto30WoNoisyJets_JetRelativeBalUpWoNoisyJets = 'vetoJets(0.5, "(userCand(\'jesRelativeBal+\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeBal+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        # jetVeto30WoNoisyJets_JetRelativeBalDownWoNoisyJets = 'vetoJets(0.5, "(userCand(\'jesRelativeBal-\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeBal-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        # vbfMassWoNoisyJets_JetTotalUp = 'vbfVariables("(userCand(\'jesTotal+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesTotal+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        # vbfMassWoNoisyJets_JetTotalDown = 'vbfVariables("(userCand(\'jesTotal-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesTotal-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        # jetVeto30WoNoisyJets_JetTotalUp = 'vetoJets(0.5, "(userCand(\'jesTotal+\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesTotal+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        # jetVeto30WoNoisyJets_JetTotalDown = 'vetoJets(0.5, "(userCand(\'jesTotal-\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesTotal-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        # vbfMassWoNoisyJets_JetEta0to5Up = 'vbfVariables("(userCand(\'jesEta0to5+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesEta0to5+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        # vbfMassWoNoisyJets_JetEta0to5Down = 'vbfVariables("(userCand(\'jesEta0to5-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesEta0to5-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        # jetVeto30WoNoisyJets_JetEta0to5Up = 'vetoJets(0.5, "(userCand(\'jesEta0to5+\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesEta0to5+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        # jetVeto30WoNoisyJets_JetEta0to5Down = 'vetoJets(0.5, "(userCand(\'jesEta0to5-\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesEta0to5-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        # vbfMassWoNoisyJets_JetEta0to3Up = 'vbfVariables("(userCand(\'jesEta0to3+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesEta0to3+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        # vbfMassWoNoisyJets_JetEta0to3Down = 'vbfVariables("(userCand(\'jesEta0to3-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesEta0to3-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        # jetVeto30WoNoisyJets_JetEta0to3Up = 'vetoJets(0.5, "(userCand(\'jesEta0to3+\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesEta0to3+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        # jetVeto30WoNoisyJets_JetEta0to3Down = 'vetoJets(0.5, "(userCand(\'jesEta0to3-\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesEta0to3-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        # vbfMassWoNoisyJets_JetEta3to5Up = 'vbfVariables("(userCand(\'jesEta3to5+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesEta3to5+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        # vbfMassWoNoisyJets_JetEta3to5Down = 'vbfVariables("(userCand(\'jesEta3to5-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesEta3to5-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        # jetVeto30WoNoisyJets_JetEta3to5Up = 'vetoJets(0.5, "(userCand(\'jesEta3to5+\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesEta3to5+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        # jetVeto30WoNoisyJets_JetEta3to5Down = 'vetoJets(0.5, "(userCand(\'jesEta3to5-\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesEta3to5-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        # vbfMassWoNoisyJets_JetEC2Up = 'vbfVariables("(userCand(\'jesEC2+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesEC2+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        # vbfMassWoNoisyJets_JetEC2Down = 'vbfVariables("(userCand(\'jesEC2-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesEC2-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        # jetVeto30WoNoisyJets_JetEC2Up = 'vetoJets(0.5, "(userCand(\'jesEC2+\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesEC2+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        # jetVeto30WoNoisyJets_JetEC2Down = 'vetoJets(0.5, "(userCand(\'jesEC2-\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesEC2-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        # vbfMassWoNoisyJets_JetRelativeSampleUp = 'vbfVariables("(userCand(\'jesRelativeSample+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeSample+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        # vbfMassWoNoisyJets_JetRelativeSampleDown = 'vbfVariables("(userCand(\'jesRelativeSample-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeSample-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        # jetVeto30WoNoisyJets_JetRelativeSampleUp = 'vetoJets(0.5, "(userCand(\'jesRelativeSample+\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeSample+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        # jetVeto30WoNoisyJets_JetRelativeSampleDown = 'vetoJets(0.5, "(userCand(\'jesRelativeSample-\').pt > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeSample-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',

        # j1ptWoNoisyJets_JetRelativeSampleDown = 'jetVariables("(userCand(\'jesRelativeSample-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeSample-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(0)',
        # j1ptWoNoisyJets_JetRelativeBalDown = 'jetVariables("(userCand(\'jesRelativeBal-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeBal-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(0)',
        # j1ptWoNoisyJets_JetEta0to3Down = 'jetVariables("(userCand(\'jesJetEta0to3-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetEta0to3-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(0)',
        # j1ptWoNoisyJets_JetEta3to5Down = 'jetVariables("(userCand(\'jesJetEta3to5-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetEta3to5-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(0)',
        # j1ptWoNoisyJets_JetEta0to5Down = 'jetVariables("(userCand(\'jesEta0to5-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetEta0to5-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(0)',
        # j1ptWoNoisyJets_JetRelativeSampleUp = 'jetVariables("(userCand(\'jesRelativeSample+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeSample+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(0)',
        # j1ptWoNoisyJets_JetRelativeBalUp = 'jetVariables("(userCand(\'jesRelativeBal+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeBal+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(0)',
        # j1ptWoNoisyJets_JetEta0to3Up = 'jetVariables("(userCand(\'jesJetEta0to3+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetEta0to3+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(0)',
        # j1ptWoNoisyJets_JetEta3to5Up = 'jetVariables("(userCand(\'jesJetEta3to5+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetEta3to5+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(0)',
        # j1ptWoNoisyJets_JetEta0to5Up = 'jetVariables("(userCand(\'jesEta0to5+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetEta0to5+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(0)',
        # j1ptWoNoisyJets_JetEC2Down = 'jetVariables("(userCand(\'jesJetEC2-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetEC2-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(0)',
        # j1ptWoNoisyJets_JetEC2Up = 'jetVariables("(userCand(\'jesJetEC2+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetEC2+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(0)',

        # j1pt_JetRelativeSampleDown = 'jetVariables("userCand(\'jesRelativeSample-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(0)',
        # j1pt_JetRelativeBalDown = 'jetVariables("userCand(\'jesRelativeBal-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(0)',
        # j1pt_JetEta0to3Down = 'jetVariables("userCand(\'jesJetEta0to3-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(0)',
        # j1pt_JetEta3to5Down = 'jetVariables("userCand(\'jesJetEta3to5-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(0)',
        # j1pt_JetEta0to5Down = 'jetVariables("userCand(\'jesJetEta0to5-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(0)',
        # j1pt_JetRelativeSampleUp = 'jetVariables("userCand(\'jesRelativeSample+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(0)',
        # j1pt_JetRelativeBalUp = 'jetVariables("userCand(\'jesRelativeBal+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(0)',
        # j1pt_JetEta0to3Up = 'jetVariables("userCand(\'jesJetEta0to3+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(0)',
        # j1pt_JetEta3to5Up = 'jetVariables("userCand(\'jesJetEta3to5+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(0)',
        # j1pt_JetEta0to5Up = 'jetVariables("userCand(\'jesJetEta0to5+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(0)',
        # j1pt_JetEC2Down = 'jetVariables("userCand(\'jesJetEC2-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(0)',
        # j1pt_JetEC2Up = 'jetVariables("userCand(\'jesJetEC2+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(0)',

        # j2ptWoNoisyJets_JetRelativeSampleDown = 'jetVariables("(userCand(\'jesRelativeSample-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeSample-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(10)',
        # j2ptWoNoisyJets_JetRelativeBalDown = 'jetVariables("(userCand(\'jesRelativeBal-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeBal-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(10)',
        # j2ptWoNoisyJets_JetEta0to3Down = 'jetVariables("(userCand(\'jesJetEta0to3-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetEta0to3-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(10)',
        # j2ptWoNoisyJets_JetEta3to5Down = 'jetVariables("(userCand(\'jesJetEta3to5-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetEta3to5-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(10)',
        # j2ptWoNoisyJets_JetEta0to5Down = 'jetVariables("(userCand(\'jesEta0to5-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetEta0to5-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(10)',
        # j2ptWoNoisyJets_JetRelativeSampleUp = 'jetVariables("(userCand(\'jesRelativeSample+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeSample+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(10)',
        # j2ptWoNoisyJets_JetRelativeBalUp = 'jetVariables("(userCand(\'jesRelativeBal+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesRelativeBal+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(10)',
        # j2ptWoNoisyJets_JetEta0to3Up = 'jetVariables("(userCand(\'jesJetEta0to3+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetEta0to3+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(10)',
        # j2ptWoNoisyJets_JetEta3to5Up = 'jetVariables("(userCand(\'jesJetEta3to5+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetEta3to5+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(10)',
        # j2ptWoNoisyJets_JetEta0to5Up = 'jetVariables("(userCand(\'jesEta0to5+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetEta0to5+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(10)',
        # j2ptWoNoisyJets_JetEC2Down = 'jetVariables("(userCand(\'jesJetEC2-\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetEC2-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(10)',
        # j2ptWoNoisyJets_JetEC2Up = 'jetVariables("(userCand(\'jesJetEC2+\').pt() > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userCand(\'jesJetEC2+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(10)',

        # j2pt_JetRelativeSampleDown = 'jetVariables("userCand(\'jesRelativeSample-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(10)',
        # j2pt_JetRelativeBalDown = 'jetVariables("userCand(\'jesRelativeBal-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(10)',
        # j2pt_JetEta0to3Down = 'jetVariables("userCand(\'jesJetEta0to3-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(10)',
        # j2pt_JetEta3to5Down = 'jetVariables("userCand(\'jesJetEta3to5-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(10)',
        # j2pt_JetEta0to5Down = 'jetVariables("userCand(\'jesJetEta0to5-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(10)',
        # j2pt_JetRelativeSampleUp = 'jetVariables("userCand(\'jesRelativeSample+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(10)',
        # j2pt_JetRelativeBalUp = 'jetVariables("userCand(\'jesRelativeBal+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(10)',
        # j2pt_JetEta0to3Up = 'jetVariables("userCand(\'jesJetEta0to3+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(10)',
        # j2pt_JetEta3to5Up = 'jetVariables("userCand(\'jesJetEta3to5+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(10)',
        # j2pt_JetEta0to5Up = 'jetVariables("userCand(\'jesJetEta0to5+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(10)',
        # j2pt_JetEC2Down = 'jetVariables("userCand(\'jesJetEC2-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(10)',
        # j2pt_JetEC2Up = 'jetVariables("userCand(\'jesJetEC2+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).at(10)',

        #vbfMass_JetAbsoluteFlavMapUp = 'vbfVariables("userCand(\'jesAbsoluteFlavMap+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetAbsoluteFlavMapDown = 'vbfVariables("userCand(\'jesAbsoluteFlavMap-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetAbsoluteFlavMapUp = 'vetoJets(0.5, "userCand(\'jesAbsoluteFlavMap+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetAbsoluteFlavMapDown = 'vetoJets(0.5, "userCand(\'jesAbsoluteFlavMap-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetAbsoluteMPFBiasUp = 'vbfVariables("userCand(\'jesAbsoluteMPFBias+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetAbsoluteMPFBiasDown = 'vbfVariables("userCand(\'jesAbsoluteMPFBias-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetAbsoluteMPFBiasUp = 'vetoJets(0.5, "userCand(\'jesAbsoluteMPFBias+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetAbsoluteMPFBiasDown = 'vetoJets(0.5, "userCand(\'jesAbsoluteMPFBias-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetAbsoluteScaleUp = 'vbfVariables("userCand(\'jesAbsoluteScale+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetAbsoluteScaleDown = 'vbfVariables("userCand(\'jesAbsoluteScale-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetAbsoluteScaleUp = 'vetoJets(0.5, "userCand(\'jesAbsoluteScale+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetAbsoluteScaleDown = 'vetoJets(0.5, "userCand(\'jesAbsoluteScale-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetAbsoluteStatUp = 'vbfVariables("userCand(\'jesAbsoluteStat+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetAbsoluteStatDown = 'vbfVariables("userCand(\'jesAbsoluteStat-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetAbsoluteStatUp = 'vetoJets(0.5, "userCand(\'jesAbsoluteStat+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetAbsoluteStatDown = 'vetoJets(0.5, "userCand(\'jesAbsoluteStat-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##vbfMass_JetCorrelationGroupFlavorUp = 'vbfVariables("userCand(\'jesCorrelationGroupFlavor+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##vbfMass_JetCorrelationGroupFlavorDown = 'vbfVariables("userCand(\'jesCorrelationGroupFlavor-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##jetVeto30_JetCorrelationGroupFlavorUp = 'vetoJets(0.5, "userCand(\'jesCorrelationGroupFlavor+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##jetVeto30_JetCorrelationGroupFlavorDown = 'vetoJets(0.5, "userCand(\'jesCorrelationGroupFlavor-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##vbfMass_JetCorrelationGroupIntercalibrationUp = 'vbfVariables("userCand(\'jesCorrelationGroupIntercalibration+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##vbfMass_JetCorrelationGroupIntercalibrationDown = 'vbfVariables("userCand(\'jesCorrelationGroupIntercalibration-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##jetVeto30_JetCorrelationGroupIntercalibrationUp = 'vetoJets(0.5, "userCand(\'jesCorrelationGroupIntercalibration+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##jetVeto30_JetCorrelationGroupIntercalibrationDown = 'vetoJets(0.5, "userCand(\'jesCorrelationGroupIntercalibration-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##vbfMass_JetCorrelationGroupMPFInSituUp = 'vbfVariables("userCand(\'jesCorrelationGroupMPFInSitu+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##vbfMass_JetCorrelationGroupMPFInSituDown = 'vbfVariables("userCand(\'jesCorrelationGroupMPFInSitu-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##jetVeto30_JetCorrelationGroupMPFInSituUp = 'vetoJets(0.5, "userCand(\'jesCorrelationGroupMPFInSitu+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##jetVeto30_JetCorrelationGroupMPFInSituDown = 'vetoJets(0.5, "userCand(\'jesCorrelationGroupMPFInSitu-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##vbfMass_JetCorrelationGroupUncorrelatedUp = 'vbfVariables("userCand(\'jesCorrelationGroupUncorrelated+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##vbfMass_JetCorrelationGroupUncorrelatedDown = 'vbfVariables("userCand(\'jesCorrelationGroupUncorrelated-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##jetVeto30_JetCorrelationGroupUncorrelatedUp = 'vetoJets(0.5, "userCand(\'jesCorrelationGroupUncorrelated+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##jetVeto30_JetCorrelationGroupUncorrelatedDown = 'vetoJets(0.5, "userCand(\'jesCorrelationGroupUncorrelated-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##vbfMass_JetCorrelationGroupbJESUp = 'vbfVariables("userCand(\'jesCorrelationGroupbJES+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##vbfMass_JetCorrelationGroupbJESDown = 'vbfVariables("userCand(\'jesCorrelationGroupbJES-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##jetVeto30_JetCorrelationGroupbJESUp = 'vetoJets(0.5, "userCand(\'jesCorrelationGroupbJES+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##jetVeto30_JetCorrelationGroupbJESDown = 'vetoJets(0.5, "userCand(\'jesCorrelationGroupbJES-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##vbfMass_JetFlavorPhotonJetUp = 'vbfVariables("userCand(\'jesFlavorPhotonJet+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##vbfMass_JetFlavorPhotonJetDown = 'vbfVariables("userCand(\'jesFlavorPhotonJet-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##jetVeto30_JetFlavorPhotonJetUp = 'vetoJets(0.5, "userCand(\'jesFlavorPhotonJet+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##jetVeto30_JetFlavorPhotonJetDown = 'vetoJets(0.5, "userCand(\'jesFlavorPhotonJet-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##vbfMass_JetFlavorPureBottomUp = 'vbfVariables("userCand(\'jesFlavorPureBottom+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##vbfMass_JetFlavorPureBottomDown = 'vbfVariables("userCand(\'jesFlavorPureBottom-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##jetVeto30_JetFlavorPureBottomUp = 'vetoJets(0.5, "userCand(\'jesFlavorPureBottom+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##jetVeto30_JetFlavorPureBottomDown = 'vetoJets(0.5, "userCand(\'jesFlavorPureBottom-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##vbfMass_JetFlavorPureCharmUp = 'vbfVariables("userCand(\'jesFlavorPureCharm+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##vbfMass_JetFlavorPureCharmDown = 'vbfVariables("userCand(\'jesFlavorPureCharm-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##jetVeto30_JetFlavorPureCharmUp = 'vetoJets(0.5, "userCand(\'jesFlavorPureCharm+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##jetVeto30_JetFlavorPureCharmDown = 'vetoJets(0.5, "userCand(\'jesFlavorPureCharm-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##vbfMass_JetFlavorPureGluonUp = 'vbfVariables("userCand(\'jesFlavorPureGluon+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##vbfMass_JetFlavorPureGluonDown = 'vbfVariables("userCand(\'jesFlavorPureGluon-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##jetVeto30_JetFlavorPureGluonUp = 'vetoJets(0.5, "userCand(\'jesFlavorPureGluon+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##jetVeto30_JetFlavorPureGluonDown = 'vetoJets(0.5, "userCand(\'jesFlavorPureGluon-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##vbfMass_JetFlavorPureQuarkUp = 'vbfVariables("userCand(\'jesFlavorPureQuark+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##vbfMass_JetFlavorPureQuarkDown = 'vbfVariables("userCand(\'jesFlavorPureQuark-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##jetVeto30_JetFlavorPureQuarkUp = 'vetoJets(0.5, "userCand(\'jesFlavorPureQuark+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##jetVeto30_JetFlavorPureQuarkDown = 'vetoJets(0.5, "userCand(\'jesFlavorPureQuark-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetFlavorQCDUp = 'vbfVariables("userCand(\'jesFlavorQCD+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetFlavorQCDDown = 'vbfVariables("userCand(\'jesFlavorQCD-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetFlavorQCDUp = 'vetoJets(0.5, "userCand(\'jesFlavorQCD+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetFlavorQCDDown = 'vetoJets(0.5, "userCand(\'jesFlavorQCD-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##vbfMass_JetFlavorZJetUp = 'vbfVariables("userCand(\'jesFlavorZJet+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##vbfMass_JetFlavorZJetDown = 'vbfVariables("userCand(\'jesFlavorZJet-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##jetVeto30_JetFlavorZJetUp = 'vetoJets(0.5, "userCand(\'jesFlavorZJet+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##jetVeto30_JetFlavorZJetDown = 'vetoJets(0.5, "userCand(\'jesFlavorZJet-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetFragmentationUp = 'vbfVariables("userCand(\'jesFragmentation+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetFragmentationDown = 'vbfVariables("userCand(\'jesFragmentation-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetFragmentationUp = 'vetoJets(0.5, "userCand(\'jesFragmentation+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetFragmentationDown = 'vetoJets(0.5, "userCand(\'jesFragmentation-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetPileUpDataMCUp = 'vbfVariables("userCand(\'jesPileUpDataMC+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetPileUpDataMCDown = 'vbfVariables("userCand(\'jesPileUpDataMC-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetPileUpDataMCUp = 'vetoJets(0.5, "userCand(\'jesPileUpDataMC+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetPileUpDataMCDown = 'vetoJets(0.5, "userCand(\'jesPileUpDataMC-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##vbfMass_JetPileUpEnvelopeUp = 'vbfVariables("userCand(\'jesPileUpEnvelope+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##vbfMass_JetPileUpEnvelopeDown = 'vbfVariables("userCand(\'jesPileUpEnvelope-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##jetVeto30_JetPileUpEnvelopeUp = 'vetoJets(0.5, "userCand(\'jesPileUpEnvelope+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##jetVeto30_JetPileUpEnvelopeDown = 'vetoJets(0.5, "userCand(\'jesPileUpEnvelope-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##vbfMass_JetPileUpMuZeroUp = 'vbfVariables("userCand(\'jesPileUpMuZero+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##vbfMass_JetPileUpMuZeroDown = 'vbfVariables("userCand(\'jesPileUpMuZero-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##jetVeto30_JetPileUpMuZeroUp = 'vetoJets(0.5, "userCand(\'jesPileUpMuZero+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##jetVeto30_JetPileUpMuZeroDown = 'vetoJets(0.5, "userCand(\'jesPileUpMuZero-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetPileUpPtBBUp = 'vbfVariables("userCand(\'jesPileUpPtBB+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetPileUpPtBBDown = 'vbfVariables("userCand(\'jesPileUpPtBB-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetPileUpPtBBUp = 'vetoJets(0.5, "userCand(\'jesPileUpPtBB+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetPileUpPtBBDown = 'vetoJets(0.5, "userCand(\'jesPileUpPtBB-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetPileUpPtEC1Up = 'vbfVariables("userCand(\'jesPileUpPtEC1+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetPileUpPtEC1Down = 'vbfVariables("userCand(\'jesPileUpPtEC1-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetPileUpPtEC1Up = 'vetoJets(0.5, "userCand(\'jesPileUpPtEC1+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetPileUpPtEC1Down = 'vetoJets(0.5, "userCand(\'jesPileUpPtEC1-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetPileUpPtEC2Up = 'vbfVariables("userCand(\'jesPileUpPtEC2+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetPileUpPtEC2Down = 'vbfVariables("userCand(\'jesPileUpPtEC2-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetPileUpPtEC2Up = 'vetoJets(0.5, "userCand(\'jesPileUpPtEC2+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetPileUpPtEC2Down = 'vetoJets(0.5, "userCand(\'jesPileUpPtEC2-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetPileUpPtHFUp = 'vbfVariables("userCand(\'jesPileUpPtHF+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetPileUpPtHFDown = 'vbfVariables("userCand(\'jesPileUpPtHF-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetPileUpPtHFUp = 'vetoJets(0.5, "userCand(\'jesPileUpPtHF+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetPileUpPtHFDown = 'vetoJets(0.5, "userCand(\'jesPileUpPtHF-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetPileUpPtRefUp = 'vbfVariables("userCand(\'jesPileUpPtRef+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetPileUpPtRefDown = 'vbfVariables("userCand(\'jesPileUpPtRef-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetPileUpPtRefUp = 'vetoJets(0.5, "userCand(\'jesPileUpPtRef+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetPileUpPtRefDown = 'vetoJets(0.5, "userCand(\'jesPileUpPtRef-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetRelativeBalUp = 'vbfVariables("userCand(\'jesRelativeBal+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetRelativeBalDown = 'vbfVariables("userCand(\'jesRelativeBal-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetRelativeBalUp = 'vetoJets(0.5, "userCand(\'jesRelativeBal+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetRelativeBalDown = 'vetoJets(0.5, "userCand(\'jesRelativeBal-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetRelativeFSRUp = 'vbfVariables("userCand(\'jesRelativeFSR+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetRelativeFSRDown = 'vbfVariables("userCand(\'jesRelativeFSR-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetRelativeFSRUp = 'vetoJets(0.5, "userCand(\'jesRelativeFSR+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetRelativeFSRDown = 'vetoJets(0.5, "userCand(\'jesRelativeFSR-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetRelativeJEREC1Up = 'vbfVariables("userCand(\'jesRelativeJEREC1+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetRelativeJEREC1Down = 'vbfVariables("userCand(\'jesRelativeJEREC1-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetRelativeJEREC1Up = 'vetoJets(0.5, "userCand(\'jesRelativeJEREC1+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetRelativeJEREC1Down = 'vetoJets(0.5, "userCand(\'jesRelativeJEREC1-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetRelativeJEREC2Up = 'vbfVariables("userCand(\'jesRelativeJEREC2+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetRelativeJEREC2Down = 'vbfVariables("userCand(\'jesRelativeJEREC2-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetRelativeJEREC2Up = 'vetoJets(0.5, "userCand(\'jesRelativeJEREC2+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetRelativeJEREC2Down = 'vetoJets(0.5, "userCand(\'jesRelativeJEREC2-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetRelativeJERHFUp = 'vbfVariables("userCand(\'jesRelativeJERHF+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetRelativeJERHFDown = 'vbfVariables("userCand(\'jesRelativeJERHF-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetRelativeJERHFUp = 'vetoJets(0.5, "userCand(\'jesRelativeJERHF+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetRelativeJERHFDown = 'vetoJets(0.5, "userCand(\'jesRelativeJERHF-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetRelativePtBBUp = 'vbfVariables("userCand(\'jesRelativePtBB+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetRelativePtBBDown = 'vbfVariables("userCand(\'jesRelativePtBB-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetRelativePtBBUp = 'vetoJets(0.5, "userCand(\'jesRelativePtBB+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetRelativePtBBDown = 'vetoJets(0.5, "userCand(\'jesRelativePtBB-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetRelativePtEC1Up = 'vbfVariables("userCand(\'jesRelativePtEC1+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetRelativePtEC1Down = 'vbfVariables("userCand(\'jesRelativePtEC1-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetRelativePtEC1Up = 'vetoJets(0.5, "userCand(\'jesRelativePtEC1+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetRelativePtEC1Down = 'vetoJets(0.5, "userCand(\'jesRelativePtEC1-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetRelativePtEC2Up = 'vbfVariables("userCand(\'jesRelativePtEC2+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetRelativePtEC2Down = 'vbfVariables("userCand(\'jesRelativePtEC2-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetRelativePtEC2Up = 'vetoJets(0.5, "userCand(\'jesRelativePtEC2+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetRelativePtEC2Down = 'vetoJets(0.5, "userCand(\'jesRelativePtEC2-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetRelativePtHFUp = 'vbfVariables("userCand(\'jesRelativePtHF+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetRelativePtHFDown = 'vbfVariables("userCand(\'jesRelativePtHF-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetRelativePtHFUp = 'vetoJets(0.5, "userCand(\'jesRelativePtHF+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetRelativePtHFDown = 'vetoJets(0.5, "userCand(\'jesRelativePtHF-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetRelativeStatECUp = 'vbfVariables("userCand(\'jesRelativeStatEC+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetRelativeStatECDown = 'vbfVariables("userCand(\'jesRelativeStatEC-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetRelativeStatECUp = 'vetoJets(0.5, "userCand(\'jesRelativeStatEC+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetRelativeStatECDown = 'vetoJets(0.5, "userCand(\'jesRelativeStatEC-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetRelativeStatFSRUp = 'vbfVariables("userCand(\'jesRelativeStatFSR+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetRelativeStatFSRDown = 'vbfVariables("userCand(\'jesRelativeStatFSR-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetRelativeStatFSRUp = 'vetoJets(0.5, "userCand(\'jesRelativeStatFSR+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetRelativeStatFSRDown = 'vetoJets(0.5, "userCand(\'jesRelativeStatFSR-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetRelativeStatHFUp = 'vbfVariables("userCand(\'jesRelativeStatHF+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetRelativeStatHFDown = 'vbfVariables("userCand(\'jesRelativeStatHF-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetRelativeStatHFUp = 'vetoJets(0.5, "userCand(\'jesRelativeStatHF+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetRelativeStatHFDown = 'vetoJets(0.5, "userCand(\'jesRelativeStatHF-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetSinglePionECALUp = 'vbfVariables("userCand(\'jesSinglePionECAL+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetSinglePionECALDown = 'vbfVariables("userCand(\'jesSinglePionECAL-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetSinglePionECALUp = 'vetoJets(0.5, "userCand(\'jesSinglePionECAL+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetSinglePionECALDown = 'vetoJets(0.5, "userCand(\'jesSinglePionECAL-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetSinglePionHCALUp = 'vbfVariables("userCand(\'jesSinglePionHCAL+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetSinglePionHCALDown = 'vbfVariables("userCand(\'jesSinglePionHCAL-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetSinglePionHCALUp = 'vetoJets(0.5, "userCand(\'jesSinglePionHCAL+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetSinglePionHCALDown = 'vetoJets(0.5, "userCand(\'jesSinglePionHCAL-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##vbfMass_JetSubTotalAbsoluteUp = 'vbfVariables("userCand(\'jesSubTotalAbsolute+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##vbfMass_JetSubTotalAbsoluteDown = 'vbfVariables("userCand(\'jesSubTotalAbsolute-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##jetVeto30_JetSubTotalAbsoluteUp = 'vetoJets(0.5, "userCand(\'jesSubTotalAbsolute+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##jetVeto30_JetSubTotalAbsoluteDown = 'vetoJets(0.5, "userCand(\'jesSubTotalAbsolute-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##vbfMass_JetSubTotalMCUp = 'vbfVariables("userCand(\'jesSubTotalMC+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##vbfMass_JetSubTotalMCDown = 'vbfVariables("userCand(\'jesSubTotalMC-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##jetVeto30_JetSubTotalMCUp = 'vetoJets(0.5, "userCand(\'jesSubTotalMC+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##jetVeto30_JetSubTotalMCDown = 'vetoJets(0.5, "userCand(\'jesSubTotalMC-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##vbfMass_JetSubTotalPileUpUp = 'vbfVariables("userCand(\'jesSubTotalPileUp+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##vbfMass_JetSubTotalPileUpDown = 'vbfVariables("userCand(\'jesSubTotalPileUp-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##jetVeto30_JetSubTotalPileUpUp = 'vetoJets(0.5, "userCand(\'jesSubTotalPileUp+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##jetVeto30_JetSubTotalPileUpDown = 'vetoJets(0.5, "userCand(\'jesSubTotalPileUp-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##vbfMass_JetSubTotalPtUp = 'vbfVariables("userCand(\'jesSubTotalPt+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##vbfMass_JetSubTotalPtDown = 'vbfVariables("userCand(\'jesSubTotalPt-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##jetVeto30_JetSubTotalPtUp = 'vetoJets(0.5, "userCand(\'jesSubTotalPt+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##jetVeto30_JetSubTotalPtDown = 'vetoJets(0.5, "userCand(\'jesSubTotalPt-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##vbfMass_JetSubTotalRelativeUp = 'vbfVariables("userCand(\'jesSubTotalRelative+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##vbfMass_JetSubTotalRelativeDown = 'vbfVariables("userCand(\'jesSubTotalRelative-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##jetVeto30_JetSubTotalRelativeUp = 'vetoJets(0.5, "userCand(\'jesSubTotalRelative+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##jetVeto30_JetSubTotalRelativeDown = 'vetoJets(0.5, "userCand(\'jesSubTotalRelative-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##vbfMass_JetSubTotalScaleUp = 'vbfVariables("userCand(\'jesSubTotalScale+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##vbfMass_JetSubTotalScaleDown = 'vbfVariables("userCand(\'jesSubTotalScale-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##jetVeto30_JetSubTotalScaleUp = 'vetoJets(0.5, "userCand(\'jesSubTotalScale+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##jetVeto30_JetSubTotalScaleDown = 'vetoJets(0.5, "userCand(\'jesSubTotalScale-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetTimePtEtaUp = 'vbfVariables("userCand(\'jesTimePtEta+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetTimePtEtaDown = 'vbfVariables("userCand(\'jesTimePtEta-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetTimePtEtaUp = 'vetoJets(0.5, "userCand(\'jesTimePtEta+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetTimePtEtaDown = 'vetoJets(0.5, "userCand(\'jesTimePtEta-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##vbfMass_JetTimeRunBCDUp = 'vbfVariables("userCand(\'jesTimeRunBCD+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##vbfMass_JetTimeRunBCDDown = 'vbfVariables("userCand(\'jesTimeRunBCD-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##jetVeto30_JetTimeRunBCDUp = 'vetoJets(0.5, "userCand(\'jesTimeRunBCD+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##jetVeto30_JetTimeRunBCDDown = 'vetoJets(0.5, "userCand(\'jesTimeRunBCD-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##vbfMass_JetTimeRunEUp = 'vbfVariables("userCand(\'jesTimeRunE+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##vbfMass_JetTimeRunEDown = 'vbfVariables("userCand(\'jesTimeRunE-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##jetVeto30_JetTimeRunEUp = 'vetoJets(0.5, "userCand(\'jesTimeRunE+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##jetVeto30_JetTimeRunEDown = 'vetoJets(0.5, "userCand(\'jesTimeRunE-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##vbfMass_JetTimeRunFUp = 'vbfVariables("userCand(\'jesTimeRunF+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##vbfMass_JetTimeRunFDown = 'vbfVariables("userCand(\'jesTimeRunF-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##jetVeto30_JetTimeRunFUp = 'vetoJets(0.5, "userCand(\'jesTimeRunF+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##jetVeto30_JetTimeRunFDown = 'vetoJets(0.5, "userCand(\'jesTimeRunF-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##vbfMass_JetTimeRunGHUp = 'vbfVariables("userCand(\'jesTimeRunGH+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##vbfMass_JetTimeRunGHDown = 'vbfVariables("userCand(\'jesTimeRunGH-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##jetVeto30_JetTimeRunGHUp = 'vetoJets(0.5, "userCand(\'jesTimeRunGH+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##jetVeto30_JetTimeRunGHDown = 'vetoJets(0.5, "userCand(\'jesTimeRunGH-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##vbfMass_JetTotalNoFlavorNoTimeUp = 'vbfVariables("userCand(\'jesTotalNoFlavorNoTime+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##vbfMass_JetTotalNoFlavorNoTimeDown = 'vbfVariables("userCand(\'jesTotalNoFlavorNoTime-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##jetVeto30_JetTotalNoFlavorNoTimeUp = 'vetoJets(0.5, "userCand(\'jesTotalNoFlavorNoTime+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##jetVeto30_JetTotalNoFlavorNoTimeDown = 'vetoJets(0.5, "userCand(\'jesTotalNoFlavorNoTime-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##vbfMass_JetTotalNoFlavorUp = 'vbfVariables("userCand(\'jesTotalNoFlavor+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##vbfMass_JetTotalNoFlavorDown = 'vbfVariables("userCand(\'jesTotalNoFlavor-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##jetVeto30_JetTotalNoFlavorUp = 'vetoJets(0.5, "userCand(\'jesTotalNoFlavor+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##jetVeto30_JetTotalNoFlavorDown = 'vetoJets(0.5, "userCand(\'jesTotalNoFlavor-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##vbfMass_JetTotalNoTimeUp = 'vbfVariables("userCand(\'jesTotalNoTime+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##vbfMass_JetTotalNoTimeDown = 'vbfVariables("userCand(\'jesTotalNoTime-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        ##jetVeto30_JetTotalNoTimeUp = 'vetoJets(0.5, "userCand(\'jesTotalNoTime+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        ##jetVeto30_JetTotalNoTimeDown = 'vetoJets(0.5, "userCand(\'jesTotalNoTime-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetTotalUp = 'vbfVariables("userCand(\'jesTotal+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetTotalDown = 'vbfVariables("userCand(\'jesTotal-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetTotalUp = 'vetoJets(0.5, "userCand(\'jesTotal+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetTotalDown = 'vetoJets(0.5, "userCand(\'jesTotal-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetEta0to5Up = 'vbfVariables("userCand(\'jesEta0to5+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetEta0to5Down = 'vbfVariables("userCand(\'jesEta0to5-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetEta0to5Up = 'vetoJets(0.5, "userCand(\'jesEta0to5+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetEta0to5Down = 'vetoJets(0.5, "userCand(\'jesEta0to5-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetEta0to3Up = 'vbfVariables("userCand(\'jesEta0to3+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetEta0to3Down = 'vbfVariables("userCand(\'jesEta0to3-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetEta0to3Up = 'vetoJets(0.5, "userCand(\'jesEta0to3+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetEta0to3Down = 'vetoJets(0.5, "userCand(\'jesEta0to3-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetEta3to5Up = 'vbfVariables("userCand(\'jesEta3to5+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetEta3to5Down = 'vbfVariables("userCand(\'jesEta3to5-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetEta3to5Up = 'vetoJets(0.5, "userCand(\'jesEta3to5+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetEta3to5Down = 'vetoJets(0.5, "userCand(\'jesEta3to5-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetRelativeSampleUp = 'vbfVariables("userCand(\'jesRelativeSample+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetRelativeSampleDown = 'vbfVariables("userCand(\'jesRelativeSample-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetRelativeSampleUp = 'vetoJets(0.5, "userCand(\'jesRelativeSample+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetRelativeSampleDown = 'vetoJets(0.5, "userCand(\'jesRelativeSample-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #vbfMass_JetClosureUp = 'vbfVariables("userCand(\'jesClosure+\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #vbfMass_JetClosureDown = 'vbfVariables("userCand(\'jesClosure-\').pt() > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5", 0.5).mass',
        #jetVeto30_JetClosureUp = 'vetoJets(0.5, "userCand(\'jesClosure+\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',
        #jetVeto30_JetClosureDown = 'vetoJets(0.5, "userCand(\'jesClosure-\').pt > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5").size()',


)

