
'''

Ntuple branch template sets for topological variables (MT, etc)

Each string is transformed into an expression on a FinalStateEvent object.

Author: Evan K. Friis

'''

from FinalStateAnalysis.Utilities.cfgtools import PSet

mtToMET = PSet(
    #objectMtToPfMet_type1   = 'mtMET({object_idx}, "", ""     )',
    #objectDPhiToPfMet_type1 = 'deltaPhiToMEt({object_idx}, "", ""     )',
    ##MVA MET
    #objectMtToMVAMET     = 'mtMET({object_idx}, "", "mvamet", "", 0)',
)

# these things break if you pass a shifted met
shiftedMtToMET = PSet(
    ## Raw means no MET corrections
    #objectMtToPfMet_Raw = 'mtMET({object_idx}, "", "raw")',

    ##PF Type1 MET (and systematics)
    #objectMtToPfMet_JetResUp          = 'mtMET({object_idx}, "", "jres+")',
    #objectMtToPfMet_JetEnUp           = 'mtMET({object_idx}, "", "jes+" )',
    #objectMtToPfMet_MuonEnUp          = 'mtMET({object_idx}, "", "mes+" )',
    #objectMtToPfMet_ElectronEnUp      = 'mtMET({object_idx}, "", "ees+" )',
    #objectMtToPfMet_TauEnUp           = 'mtMET({object_idx}, "tesUpTaus", "tes+" )',
    #objectMtToPfMet_UnclusteredEnUp   = 'mtMET({object_idx}, "", "ues+" )',
    #objectMtToPfMet_PhotonEnUp        = 'mtMET({object_idx}, "", "pes+" )',

    #objectMtToPfMet_JetResDown        = 'mtMET({object_idx}, "", "jres-")',
    #objectMtToPfMet_JetEnDown         = 'mtMET({object_idx}, "", "jes-" )',
    #objectMtToPfMet_MuonEnDown        = 'mtMET({object_idx}, "", "mes-" )',
    #objectMtToPfMet_ElectronEnDown    = 'mtMET({object_idx}, "", "ees-" )',
    #objectMtToPfMet_TauEnDown         = 'mtMET({object_idx}, "tesDownTaus", "tes-" )',
    #objectMtToPfMet_UnclusteredEnDown = 'mtMET({object_idx}, "", "ues-" )',
    #objectMtToPfMet_PhotonEnDown      = 'mtMET({object_idx}, "", "pes-" )',

    #objectDPhiToPfMet_JetResUp          = 'deltaPhiToMEt({object_idx}, "", "jres+")',
    #objectDPhiToPfMet_JetEnUp           = 'deltaPhiToMEt({object_idx}, "", "jes+" )',
    #objectDPhiToPfMet_MuonEnUp          = 'deltaPhiToMEt({object_idx}, "", "mes+" )',
    #objectDPhiToPfMet_ElectronEnUp      = 'deltaPhiToMEt({object_idx}, "", "ees+" )',
    #objectDPhiToPfMet_TauEnUp           = 'deltaPhiToMEt({object_idx}, "", "tes+" )',
    #objectDPhiToPfMet_UnclusteredEnUp   = 'deltaPhiToMEt({object_idx}, "", "ues+" )',
    #objectDPhiToPfMet_PhotonEnUp        = 'deltaPhiToMEt({object_idx}, "", "pes+" )',

    #objectDPhiToPfMet_JetResDown        = 'deltaPhiToMEt({object_idx}, "", "jres-")',
    #objectDPhiToPfMet_JetEnDown         = 'deltaPhiToMEt({object_idx}, "", "jes-" )',
    #objectDPhiToPfMet_MuonEnDown        = 'deltaPhiToMEt({object_idx}, "", "mes-" )',
    #objectDPhiToPfMet_ElectronEnDown    = 'deltaPhiToMEt({object_idx}, "", "ees-" )',
    #objectDPhiToPfMet_TauEnDown         = 'deltaPhiToMEt({object_idx}, "", "tes-" )',
    #objectDPhiToPfMet_UnclusteredEnDown = 'deltaPhiToMEt({object_idx}, "", "ues-" )',
    #objectDPhiToPfMet_PhotonEnDown      = 'deltaPhiToMEt({object_idx}, "", "pes-" )',
)

# Variables based on pairs of objects
pairs = PSet(
    object1_object2_Mass = 'subcand({object1_idx}, {object2_idx}).get.mass',
    #object1_object2_Mt = 'subcand({object1_idx}, {object2_idx}).get.mt',
    #object1_object2_collinearmass = 'collinearMassMET({object1_idx}, "", {object2_idx},"","")',
    #object2_object1_collinearmass = 'collinearMassMET({object2_idx}, "", {object1_idx},"","")',
   
    #object1_object2_Mass_TauEnUp = 'subcand({object1_idx}, "",{object2_idx},"tesUpTaus").get.mass',
    #object1_object2_Mass_TauEnDown = 'subcand({object1_idx}, "",{object2_idx},"tesDownTaus").get.mass',
    #object1_object2_Mt_TauEnUp = 'subcand({object1_idx}, "",{object2_idx},"tesUpTaus").get.mt',
    #object1_object2_Mt_TauEnDown = 'subcand({object1_idx}, "",{object2_idx},"tesDownTaus").get.mt',
 
    #object1_object2_Pt = 'subcand({object1_idx}, {object2_idx}).get.pt',
    #object1_object2_Eta = 'subcand({object1_idx}, {object2_idx}).get.eta',
    #object1_object2_Phi = 'subcand({object1_idx}, {object2_idx}).get.phi',
    object1_object2_DR = 'dR({object1_idx}, {object2_idx})',
    #object1_object2_DPhi = 'dPhi({object1_idx}, {object2_idx})',
    #object1_object2_SS = 'likeSigned({object1_idx}, {object2_idx})',
    #object1_object2_PZeta = 'pZeta({object1_idx}, {object2_idx})',
    #object1_object2_PZetaVis = 'pZetaVis({object1_idx}, {object2_idx})',
    #object1_object2_CosThetaStar = 'abs(subcand({object1_idx}, {object2_idx}).get.daughterCosThetaStar(0))',

    #object1_object2_collinearmass_JetEnUp = 'collinearMassMET({object1_idx}, "", {object2_idx},"","jes+")',
    #object2_object1_collinearmass_JetEnUp = 'collinearMassMET({object2_idx}, "", {object1_idx},"","jes+")', # for now we only need m_t_coll
    #object1_object2_collinearmass_JetEnDown = 'collinearMassMET({object1_idx}, "", {object2_idx},"","jes-")',
    #object2_object1_collinearmass_JetEnDown = 'collinearMassMET({object2_idx}, "", {object1_idx},"","jes-")',
    #object1_object2_collinearmass_UnclusteredEnUp = 'collinearMassMET({object1_idx}, "", {object2_idx},"","ues+")',
    #object2_object1_collinearmass_UnclusteredEnUp = 'collinearMassMET({object2_idx}, "", {object1_idx},"","ues+")',
    #object1_object2_collinearmass_UnclusteredEnDown = 'collinearMassMET({object1_idx}, "", {object2_idx},"","ues-")',
    #object2_object1_collinearmass_UnclusteredEnDown = 'collinearMassMET({object2_idx}, "", {object1_idx},"","ues-")',
    #object1_object2_collinearmass_TauEnUp = 'collinearMassMET({object1_idx}, "", {object2_idx},"tesUpTaus","tes+")',
    #object1_object2_collinearmass_TauEnDown = 'collinearMassMET({object1_idx}, "", {object2_idx},"tesDownTaus","tes-")',
    #object1_object2_collinearmass_EleEnUp = 'collinearMassMET({object1_idx}, "", {object2_idx},"","ees+")',
    #object1_object2_collinearmass_EleEnDown = 'collinearMassMET({object1_idx}, "", {object2_idx},"","ees-")',
    #object1_object2_collinearmass_MuEnUp = 'collinearMassMET({object1_idx}, "", {object2_idx},"","mes+")',
    #object1_object2_collinearmass_MuEnDown = 'collinearMassMET({object1_idx}, "", {object2_idx},"","mes-")',

    #object1_object2_collinearmass_JetCheckTotalUp = 'collinearMassMET({object1_idx}, "", {object2_idx},"","jesTotal+")',
    #object2_object1_collinearmass_JetCheckTotalUp = 'collinearMassMET({object2_idx}, "", {object1_idx},"","jesTotal+")', # for now we only need m_t_coll
    #object1_object2_collinearmass_JetCheckTotalDown = 'collinearMassMET({object1_idx}, "", {object2_idx},"","jesTotal-")',
    #object2_object1_collinearmass_JetCheckTotalDown = 'collinearMassMET({object2_idx}, "", {object1_idx},"","jesTotal-")',
    #object1_object2_collinearmass_CheckUESUp = 'collinearMassMET({object1_idx}, "", {object2_idx},"","checkUES+")',
    #object2_object1_collinearmass_CheckUESUp = 'collinearMassMET({object2_idx}, "", {object1_idx},"","checkUES+")',
    #object1_object2_collinearmass_CheckUESDown = 'collinearMassMET({object1_idx}, "", {object2_idx},"","checkUES-")',
    #object2_object1_collinearmass_CheckUESDown = 'collinearMassMET({object2_idx}, "", {object1_idx},"","checkUES-")',

    ##Pairs + MET
    #object1_object2_ToMETDPhi_Ty1 = 'twoParticleDeltaPhiToMEt({object1_idx}, {object2_idx}, "type1")',
)

svfit = PSet(
    #object1_object2_SVfitMass = 'SVfit({object1_idx},{object2_idx}).at(0)',
    #object1_object2_SVfitPt = 'SVfit({object1_idx},{object2_idx}).at(1)',
    #object1_object2_SVfitEta = 'SVfit({object1_idx},{object2_idx}).at(2)',
    #object1_object2_SVfitPhi = 'SVfit({object1_idx},{object2_idx}).at(3)',
    #object1_object2_SVfitMET = 'SVfit({object1_idx},{object2_idx}).at(4)',
)

finalstate = PSet(
)


vbf = PSet(

)


extraJet = PSet(
)


# Temporary variables for JES study
fullJES = PSet(
        deepcsvb1_pt_JetRelativeSampleDown = 'deepCSVJetVariables("userFloat(\'jesRelativeSample-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetRelativeBalDown = 'deepCSVJetVariables("userFloat(\'jesRelativeBal-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetEC2Down = 'deepCSVJetVariables("userFloat(\'jesEC2-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetAbsoluteDown = 'deepCSVJetVariables("userFloat(\'jesAbsolute-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetAbsoluteyearDown = 'deepCSVJetVariables("userFloat(\'jesAbsoluteyear-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetFlavorQCDDown = 'deepCSVJetVariables("userFloat(\'jesFlavorQCD-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetBBEC1Down = 'deepCSVJetVariables("userFloat(\'jesBBEC1-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetHFDown = 'deepCSVJetVariables("userFloat(\'jesHF-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetBBEC1yearDown = 'deepCSVJetVariables("userFloat(\'jesBBEC1year-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetEC2yearDown = 'deepCSVJetVariables("userFloat(\'jesEC2year-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetHFyearDown = 'deepCSVJetVariables("userFloat(\'jesHFyear-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetTotalDown = 'deepCSVJetVariables("userFloat(\'jesTotal-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JERDown = 'deepCSVJetVariables("userFloat(\'jer-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetRelativeSampleUp = 'deepCSVJetVariables("userFloat(\'jesRelativeSample+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetRelativeBalUp = 'deepCSVJetVariables("userFloat(\'jesRelativeBal+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetEC2Up = 'deepCSVJetVariables("userFloat(\'jesEC2+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetAbsoluteUp = 'deepCSVJetVariables("userFloat(\'jesAbsolute+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetAbsoluteyearUp = 'deepCSVJetVariables("userFloat(\'jesAbsoluteyear+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetFlavorQCDUp = 'deepCSVJetVariables("userFloat(\'jesFlavorQCD+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetBBEC1Up = 'deepCSVJetVariables("userFloat(\'jesBBEC1+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetHFUp = 'deepCSVJetVariables("userFloat(\'jesHF+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetBBEC1yearUp = 'deepCSVJetVariables("userFloat(\'jesBBEC1year+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetEC2yearUp = 'deepCSVJetVariables("userFloat(\'jesEC2year+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetHFyearUp = 'deepCSVJetVariables("userFloat(\'jesHFyear+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JetTotalUp = 'deepCSVJetVariables("userFloat(\'jesTotal+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',
        deepcsvb1_pt_JERUp = 'deepCSVJetVariables("userFloat(\'jer+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(0)',

        deepcsvb2_pt_JetRelativeSampleDown = 'deepCSVJetVariables("userFloat(\'jesRelativeSample-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetRelativeBalDown = 'deepCSVJetVariables("userFloat(\'jesRelativeBal-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetEC2Down = 'deepCSVJetVariables("userFloat(\'jesEC2-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetAbsoluteDown = 'deepCSVJetVariables("userFloat(\'jesAbsolute-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetAbsoluteyearDown = 'deepCSVJetVariables("userFloat(\'jesAbsoluteyear-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetFlavorQCDDown = 'deepCSVJetVariables("userFloat(\'jesFlavorQCD-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetBBEC1Down = 'deepCSVJetVariables("userFloat(\'jesBBEC1-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetHFDown = 'deepCSVJetVariables("userFloat(\'jesHF-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetBBEC1yearDown = 'deepCSVJetVariables("userFloat(\'jesBBEC1year-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetEC2yearDown = 'deepCSVJetVariables("userFloat(\'jesEC2year-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetHFyearDown = 'deepCSVJetVariables("userFloat(\'jesHFyear-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetTotalDown = 'deepCSVJetVariables("userFloat(\'jesTotal-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JERDown = 'deepCSVJetVariables("userFloat(\'jer-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetRelativeSampleUp = 'deepCSVJetVariables("userFloat(\'jesRelativeSample+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetRelativeBalUp = 'deepCSVJetVariables("userFloat(\'jesRelativeBal+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetEC2Up = 'deepCSVJetVariables("userFloat(\'jesEC2+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetAbsoluteUp = 'deepCSVJetVariables("userFloat(\'jesAbsolute+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetAbsoluteyearUp = 'deepCSVJetVariables("userFloat(\'jesAbsoluteyear+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetFlavorQCDUp = 'deepCSVJetVariables("userFloat(\'jesFlavorQCD+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetBBEC1Up = 'deepCSVJetVariables("userFloat(\'jesBBEC1+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetHFUp = 'deepCSVJetVariables("userFloat(\'jesHF+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetBBEC1yearUp = 'deepCSVJetVariables("userFloat(\'jesBBEC1year+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetEC2yearUp = 'deepCSVJetVariables("userFloat(\'jesEC2year+\')  > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetHFyearUp = 'deepCSVJetVariables("userFloat(\'jesHFyear+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JetTotalUp = 'deepCSVJetVariables("userFloat(\'jesTotal+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',
        deepcsvb2_pt_JERUp = 'deepCSVJetVariables("userFloat(\'jer+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepCSVJetTags:probb\') + bDiscriminator(\'pfDeepCSVJetTags:probbb\')) > 0.1241", 0.5).at(6)',

        #deepflavourb1_pt_JetRelativeSampleDown = 'deepFlavourJetVariables("userFloat(\'jesRelativeSample-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetRelativeBalDown = 'deepFlavourJetVariables("userFloat(\'jesRelativeBal-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetEC2Down = 'deepFlavourJetVariables("userFloat(\'jesEC2-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetAbsoluteDown = 'deepFlavourJetVariables("userFloat(\'jesAbsolute-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetAbsoluteyearDown = 'deepFlavourJetVariables("userFloat(\'jesAbsoluteyear-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetFlavorQCDDown = 'deepFlavourJetVariables("userFloat(\'jesFlavorQCD-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetBBEC1Down = 'deepFlavourJetVariables("userFloat(\'jesBBEC1-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetHFDown = 'deepFlavourJetVariables("userFloat(\'jesHF-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetBBEC1yearDown = 'deepFlavourJetVariables("userFloat(\'jesBBEC1year-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetEC2yearDown = 'deepFlavourJetVariables("userFloat(\'jesEC2year-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetHFyearDown = 'deepFlavourJetVariables("userFloat(\'jesHFyear-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetTotalDown = 'deepFlavourJetVariables("userFloat(\'jesTotal-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JERDown = 'deepFlavourJetVariables("userFloat(\'jer-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetRelativeSampleUp = 'deepFlavourJetVariables("userFloat(\'jesRelativeSample+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetRelativeBalUp = 'deepFlavourJetVariables("userFloat(\'jesRelativeBal+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetEC2Up = 'deepFlavourJetVariables("userFloat(\'jesEC2+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetAbsoluteUp = 'deepFlavourJetVariables("userFloat(\'jesAbsolute+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetAbsoluteyearUp = 'deepFlavourJetVariables("userFloat(\'jesAbsoluteyear+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetFlavorQCDUp = 'deepFlavourJetVariables("userFloat(\'jesFlavorQCD+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetBBEC1Up = 'deepFlavourJetVariables("userFloat(\'jesBBEC1+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetHFUp = 'deepFlavourJetVariables("userFloat(\'jesHF+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetBBEC1yearUp = 'deepFlavourJetVariables("userFloat(\'jesBBEC1year+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetEC2yearUp = 'deepFlavourJetVariables("userFloat(\'jesEC2year+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetHFyearUp = 'deepFlavourJetVariables("userFloat(\'jesHFyear+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JetTotalUp = 'deepFlavourJetVariables("userFloat(\'jesTotal+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',
        #deepflavourb1_pt_JERUp = 'deepFlavourJetVariables("userFloat(\'jer+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(0)',

        #deepflavourb2_pt_JetRelativeSampleDown = 'deepFlavourJetVariables("userFloat(\'jesRelativeSample-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetRelativeBalDown = 'deepFlavourJetVariables("userFloat(\'jesRelativeBal-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetEC2Down = 'deepFlavourJetVariables("userFloat(\'jesEC2-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetAbsoluteDown = 'deepFlavourJetVariables("userFloat(\'jesAbsolute-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetAbsoluteyearDown = 'deepFlavourJetVariables("userFloat(\'jesAbsoluteyear-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetFlavorQCDDown = 'deepFlavourJetVariables("userFloat(\'jesFlavorQCD-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetBBEC1Down = 'deepFlavourJetVariables("userFloat(\'jesBBEC1-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetHFDown = 'deepFlavourJetVariables("userFloat(\'jesHF-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetBBEC1yearDown = 'deepFlavourJetVariables("userFloat(\'jesBBEC1year-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetEC2yearDown = 'deepFlavourJetVariables("userFloat(\'jesEC2year-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetHFyearDown = 'deepFlavourJetVariables("userFloat(\'jesHFyear-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetTotalDown = 'deepFlavourJetVariables("userFloat(\'jesTotal-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JERDown = 'deepFlavourJetVariables("userFloat(\'jer-\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetRelativeSampleUp = 'deepFlavourJetVariables("userFloat(\'jesRelativeSample+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetRelativeBalUp = 'deepFlavourJetVariables("userFloat(\'jesRelativeBal+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetEC2Up = 'deepFlavourJetVariables("userFloat(\'jesEC2+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetAbsoluteUp = 'deepFlavourJetVariables("userFloat(\'jesAbsolute+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetAbsoluteyearUp = 'deepFlavourJetVariables("userFloat(\'jesAbsoluteyear+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetFlavorQCDUp = 'deepFlavourJetVariables("userFloat(\'jesFlavorQCD+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetBBEC1Up = 'deepFlavourJetVariables("userFloat(\'jesBBEC1+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetHFUp = 'deepFlavourJetVariables("userFloat(\'jesHF+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetBBEC1yearUp = 'deepFlavourJetVariables("userFloat(\'jesBBEC1year+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetEC2yearUp = 'deepFlavourJetVariables("userFloat(\'jesEC2year+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetHFyearUp = 'deepFlavourJetVariables("userFloat(\'jesHFyear+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JetTotalUp = 'deepFlavourJetVariables("userFloat(\'jesTotal+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',
        #deepflavourb2_pt_JERUp = 'deepFlavourJetVariables("userFloat(\'jer+\') > 20 & userFloat(\'idTight\') > 0.5 & abs(eta) < 2.4 & (bDiscriminator(\'pfDeepFlavourJetTags:probb\') + bDiscriminator(\'pfDeepFlavourJetTags:probbb\') + bDiscriminator(\'pfDeepFlavourJetTags:problepb\')) > 0.0494", 0.5).at(6)',


	## Comment for 2017
        jetVeto30_JERUp = 'vetoJets(0.5, "userFloat(\'jer+\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jer+\') > 50)").size()',
        jetVeto30_JERDown = 'vetoJets(0.5, "userFloat(\'jer-\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jer-\') > 50)").size()',
        vbfMass_JERUp = 'vbfVariables("userFloat(\'jer+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jer+\') > 50)", 0.5).mass',
        vbfMass_JERDown = 'vbfVariables("userFloat(\'jer-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jer-\') > 50)", 0.5).mass',
        j1pt_JERDown = 'jetVariables("userFloat(\'jer-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jer-\') > 50)", 0.5).at(0)',
        j2pt_JERDown = 'jetVariables("userFloat(\'jer-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jer-\') > 50)", 0.5).at(6)',
        j1pt_JERUp = 'jetVariables("userFloat(\'jer+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jer+\') > 50)", 0.5).at(0)',
        j2pt_JERUp = 'jetVariables("userFloat(\'jer+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jer+\') > 50)", 0.5).at(6)',

        vbfMass_JetTotalUp = 'vbfVariables("userFloat(\'jesTotal+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesTotal+\') > 50)", 0.5).mass',
        vbfMass_JetTotalDown = 'vbfVariables("userFloat(\'jesTotal-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesTotal-\') > 50)", 0.5).mass',
        jetVeto30_JetTotalUp = 'vetoJets(0.5, "userFloat(\'jesTotal+\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesTotal+\') > 50)").size()',
        jetVeto30_JetTotalDown = 'vetoJets(0.5, "userFloat(\'jesTotal-\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesTotal-\') > 50)").size()',
        vbfMass_JetEC2Up = 'vbfVariables("userFloat(\'jesEC2+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2+\') > 50)", 0.5).mass',
        vbfMass_JetEC2Down = 'vbfVariables("userFloat(\'jesEC2-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2-\') > 50)", 0.5).mass',
        jetVeto30_JetEC2Up = 'vetoJets(0.5, "userFloat(\'jesEC2+\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2+\') > 50)").size()',
        jetVeto30_JetEC2Down = 'vetoJets(0.5, "userFloat(\'jesEC2-\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2-\') > 50)").size()',
        vbfMass_JetAbsoluteUp = 'vbfVariables("userFloat(\'jesAbsolute+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsolute+\') > 50)", 0.5).mass',
        vbfMass_JetAbsoluteDown = 'vbfVariables("userFloat(\'jesAbsolute-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsolute-\') > 50)", 0.5).mass',
        jetVeto30_JetAbsoluteUp = 'vetoJets(0.5, "userFloat(\'jesAbsolute+\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsolute+\') > 50)").size()',
        jetVeto30_JetAbsoluteDown = 'vetoJets(0.5, "userFloat(\'jesAbsolute-\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsolute-\') > 50)").size()',
        vbfMass_JetAbsoluteyearUp = 'vbfVariables("userFloat(\'jesAbsoluteyear+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsoluteyear+\') > 50)", 0.5).mass',
        vbfMass_JetAbsoluteyearDown = 'vbfVariables("userFloat(\'jesAbsoluteyear-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsoluteyear-\') > 50)", 0.5).mass',
        jetVeto30_JetAbsoluteyearUp = 'vetoJets(0.5, "userFloat(\'jesAbsoluteyear+\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsoluteyear+\') > 50)").size()',
        jetVeto30_JetAbsoluteyearDown = 'vetoJets(0.5, "userFloat(\'jesAbsoluteyear-\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsoluteyear-\') > 50)").size()',
        vbfMass_JetFlavorQCDUp = 'vbfVariables("userFloat(\'jesFlavorQCD+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesFlavorQCD+\') > 50)", 0.5).mass',
        vbfMass_JetFlavorQCDDown = 'vbfVariables("userFloat(\'jesFlavorQCD-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesFlavorQCD-\') > 50)", 0.5).mass',
        jetVeto30_JetFlavorQCDUp = 'vetoJets(0.5, "userFloat(\'jesFlavorQCD+\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesFlavorQCD+\') > 50)").size()',
        jetVeto30_JetFlavorQCDDown = 'vetoJets(0.5, "userFloat(\'jesFlavorQCD-\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesFlavorQCD-\') > 50)").size()',
        vbfMass_JetBBEC1Up = 'vbfVariables("userFloat(\'jesBBEC1+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1+\') > 50)", 0.5).mass',
        vbfMass_JetBBEC1Down = 'vbfVariables("userFloat(\'jesBBEC1-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1-\') > 50)", 0.5).mass',
        jetVeto30_JetBBEC1Up = 'vetoJets(0.5, "userFloat(\'jesBBEC1+\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1+\') > 50)").size()',
        jetVeto30_JetBBEC1Down = 'vetoJets(0.5, "userFloat(\'jesBBEC1-\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1-\') > 50)").size()',
        vbfMass_JetHFUp = 'vbfVariables("userFloat(\'jesHF+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHF+\') > 50)", 0.5).mass',
        vbfMass_JetHFDown = 'vbfVariables("userFloat(\'jesHF-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHF-\') > 50)", 0.5).mass',
        jetVeto30_JetHFUp = 'vetoJets(0.5, "userFloat(\'jesHF+\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHF+\') > 50)").size()',
        jetVeto30_JetHFDown = 'vetoJets(0.5, "userFloat(\'jesHF-\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHF-\') > 50)").size()',
        vbfMass_JetBBEC1yearUp = 'vbfVariables("userFloat(\'jesBBEC1year+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1year+\') > 50)", 0.5).mass',
        vbfMass_JetBBEC1yearDown = 'vbfVariables("userFloat(\'jesBBEC1year-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1year-\') > 50)", 0.5).mass',
        jetVeto30_JetBBEC1yearUp = 'vetoJets(0.5, "userFloat(\'jesBBEC1year+\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1year+\') > 50)").size()',
        jetVeto30_JetBBEC1yearDown = 'vetoJets(0.5, "userFloat(\'jesBBEC1year-\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1year-\') > 50)").size()',
        vbfMass_JetEC2yearUp = 'vbfVariables("userFloat(\'jesEC2year+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2year+\') > 50)", 0.5).mass',
        vbfMass_JetEC2yearDown = 'vbfVariables("userFloat(\'jesEC2year-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2year-\') > 50)", 0.5).mass',
        jetVeto30_JetEC2yearUp = 'vetoJets(0.5, "userFloat(\'jesEC2year+\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2year+\') > 50)").size()',
        jetVeto30_JetEC2yearDown = 'vetoJets(0.5, "userFloat(\'jesEC2year-\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2year-\') > 50)").size()',
        vbfMass_JetHFyearUp = 'vbfVariables("userFloat(\'jesHFyear+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHFyear+\') > 50)", 0.5).mass',
        vbfMass_JetHFyearDown = 'vbfVariables("userFloat(\'jesHFyear-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHFyear-\') > 50)", 0.5).mass',
        jetVeto30_JetHFyearUp = 'vetoJets(0.5, "userFloat(\'jesHFyear+\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHFyear+\') > 50)").size()',
        jetVeto30_JetHFyearDown = 'vetoJets(0.5, "userFloat(\'jesHFyear-\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHFyear-\') > 50)").size()',
        vbfMass_JetRelativeSampleUp = 'vbfVariables("userFloat(\'jesRelativeSample+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeSample+\') > 50)", 0.5).mass',
        vbfMass_JetRelativeSampleDown = 'vbfVariables("userFloat(\'jesRelativeSample-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeSample-\') > 50)", 0.5).mass',
        jetVeto30_JetRelativeSampleUp = 'vetoJets(0.5, "userFloat(\'jesRelativeSample+\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeSample+\') > 50)").size()',
        jetVeto30_JetRelativeSampleDown = 'vetoJets(0.5, "userFloat(\'jesRelativeSample-\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeSample-\') > 50)").size()',
        vbfMass_JetRelativeBalUp = 'vbfVariables("userFloat(\'jesRelativeBal+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeBal+\') > 50)", 0.5).mass',
        vbfMass_JetRelativeBalDown = 'vbfVariables("userFloat(\'jesRelativeBal-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeBal-\') > 50)", 0.5).mass',
        jetVeto30_JetRelativeBalUp = 'vetoJets(0.5, "userFloat(\'jesRelativeBal+\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeBal+\') > 50)").size()',
        jetVeto30_JetRelativeBalDown = 'vetoJets(0.5, "userFloat(\'jesRelativeBal-\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeBal-\') > 50)").size()',

        j1pt_JetRelativeSampleDown = 'jetVariables("userFloat(\'jesRelativeSample-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeSample-\') > 50)", 0.5).at(0)',
        j1pt_JetRelativeBalDown = 'jetVariables("userFloat(\'jesRelativeBal-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeBal-\') > 50)", 0.5).at(0)',
        j1pt_JetRelativeSampleUp = 'jetVariables("userFloat(\'jesRelativeSample+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeSample+\') > 50)", 0.5).at(0)',
        j1pt_JetRelativeBalUp = 'jetVariables("userFloat(\'jesRelativeBal+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeBal+\') > 50)", 0.5).at(0)',
        j1pt_JetEC2Down = 'jetVariables("userFloat(\'jesEC2-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2-\') > 50)", 0.5).at(0)',
        j1pt_JetEC2Up = 'jetVariables("userFloat(\'jesEC2+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2+\') > 50)", 0.5).at(0)',
        j1pt_JetAbsoluteDown = 'jetVariables("userFloat(\'jesAbsolute-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsolute-\') > 50)", 0.5).at(0)',
        j1pt_JetAbsoluteUp = 'jetVariables("userFloat(\'jesAbsolute+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsolute+\') > 50)", 0.5).at(0)',
        j1pt_JetAbsoluteyearDown = 'jetVariables("userFloat(\'jesAbsoluteyear-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsoluteyear-\') > 50)", 0.5).at(0)',
        j1pt_JetAbsoluteyearUp = 'jetVariables("userFloat(\'jesAbsoluteyear+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsoluteyear+\') > 50)", 0.5).at(0)',
        j1pt_JetFlavorQCDDown = 'jetVariables("userFloat(\'jesFlavorQCD-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesFlavorQCD-\') > 50)", 0.5).at(0)',
        j1pt_JetFlavorQCDUp = 'jetVariables("userFloat(\'jesFlavorQCD+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesFlavorQCD+\') > 50)", 0.5).at(0)',
        j1pt_JetBBEC1Down = 'jetVariables("userFloat(\'jesBBEC1-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1-\') > 50)", 0.5).at(0)',
        j1pt_JetBBEC1Up = 'jetVariables("userFloat(\'jesBBEC1+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1+\') > 50)", 0.5).at(0)',
        j1pt_JetHFDown = 'jetVariables("userFloat(\'jesHF-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHF-\') > 50)", 0.5).at(0)',
        j1pt_JetHFUp = 'jetVariables("userFloat(\'jesHF+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHF+\') > 50)", 0.5).at(0)',
        j1pt_JetBBEC1yearDown = 'jetVariables("userFloat(\'jesBBEC1year-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1year-\') > 50)", 0.5).at(0)',
        j1pt_JetBBEC1yearUp = 'jetVariables("userFloat(\'jesBBEC1year+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1year+\') > 50)", 0.5).at(0)',
        j1pt_JetEC2yearDown = 'jetVariables("userFloat(\'jesEC2year-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2year-\') > 50)", 0.5).at(0)',
        j1pt_JetEC2yearUp = 'jetVariables("userFloat(\'jesEC2year+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2year+\') > 50)", 0.5).at(0)',
        j1pt_JetHFyearDown = 'jetVariables("userFloat(\'jesHFyear-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHFyear-\') > 50)", 0.5).at(0)',
        j1pt_JetHFyearUp = 'jetVariables("userFloat(\'jesHFyear+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHFyear+\') > 50)", 0.5).at(0)',

        j2pt_JetRelativeSampleDown = 'jetVariables("userFloat(\'jesRelativeSample-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeSample-\') > 50)", 0.5).at(6)',
        j2pt_JetRelativeBalDown = 'jetVariables("userFloat(\'jesRelativeBal-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeBal-\') > 50)", 0.5).at(6)',
        j2pt_JetRelativeSampleUp = 'jetVariables("userFloat(\'jesRelativeSample+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeSample+\') > 50)", 0.5).at(6)',
        j2pt_JetRelativeBalUp = 'jetVariables("userFloat(\'jesRelativeBal+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeBal+\') > 50)", 0.5).at(6)',
        j2pt_JetEC2Down = 'jetVariables("userFloat(\'jesEC2-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2-\') > 50)", 0.5).at(6)',
        j2pt_JetEC2Up = 'jetVariables("userFloat(\'jesEC2+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2+\') > 50)", 0.5).at(6)',
        j2pt_JetAbsoluteDown = 'jetVariables("userFloat(\'jesAbsolute-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsolute-\') > 50)", 0.5).at(6)',
        j2pt_JetAbsoluteUp = 'jetVariables("userFloat(\'jesAbsolute+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsolute+\') > 50)", 0.5).at(6)',
        j2pt_JetAbsoluteyearDown = 'jetVariables("userFloat(\'jesAbsoluteyear-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsoluteyear-\') > 50)", 0.5).at(6)',
        j2pt_JetAbsoluteyearUp = 'jetVariables("userFloat(\'jesAbsoluteyear+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsoluteyear+\') > 50)", 0.5).at(6)',
        j2pt_JetFlavorQCDDown = 'jetVariables("userFloat(\'jesFlavorQCD-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesFlavorQCD-\') > 50)", 0.5).at(6)',
        j2pt_JetFlavorQCDUp = 'jetVariables("userFloat(\'jesFlavorQCD+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesFlavorQCD+\') > 50)", 0.5).at(6)',
        j2pt_JetBBEC1Down = 'jetVariables("userFloat(\'jesBBEC1-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1-\') > 50)", 0.5).at(6)',
        j2pt_JetBBEC1Up = 'jetVariables("userFloat(\'jesBBEC1+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1+\') > 50)", 0.5).at(6)',
        j2pt_JetHFDown = 'jetVariables("userFloat(\'jesHF-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHF-\') > 50)", 0.5).at(6)',
        j2pt_JetHFUp = 'jetVariables("userFloat(\'jesHF+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHF+\') > 50)", 0.5).at(6)',
        j2pt_JetBBEC1yearDown = 'jetVariables("userFloat(\'jesBBEC1year-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1year-\') > 50)", 0.5).at(6)',
        j2pt_JetBBEC1yearUp = 'jetVariables("userFloat(\'jesBBEC1year+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1year+\') > 50)", 0.5).at(6)',
        j2pt_JetEC2yearDown = 'jetVariables("userFloat(\'jesEC2year-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2year-\') > 50)", 0.5).at(6)',
        j2pt_JetEC2yearUp = 'jetVariables("userFloat(\'jesEC2year+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2year+\') > 50)", 0.5).at(6)',
        j2pt_JetHFyearDown = 'jetVariables("userFloat(\'jesHFyear-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHFyear-\') > 50)", 0.5).at(6)',
        j2pt_JetHFyearUp = 'jetVariables("userFloat(\'jesHFyear+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHFyear+\') > 50)", 0.5).at(6)',


        ##Uncomment for 2017 Noisy jets

        #vbfMass_JERUp = 'vbfVariables("(userFloat(\'jer+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jer+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jer+\') > 50)", 0.5).mass',
        #vbfMass_JERDown = 'vbfVariables("(userFloat(\'jer-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jer-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jer-\') > 50)", 0.5).mass',
        #jetVeto30_JERUp = 'vetoJets(0.5, "(userFloat(\'jer+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jer+\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jer+\') > 50)").size()',
        #jetVeto30_JERDown = 'vetoJets(0.5, "(userFloat(\'jer-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jer-\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jer-\') > 50)").size()',
        #j1pt_JERDown = 'jetVariables("(userFloat(\'jer-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jer-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jer-\') > 50)", 0.5).at(0)',
        #j2pt_JERDown = 'jetVariables("(userFloat(\'jer-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jer-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jer-\') > 50)", 0.5).at(6)',
        #j1pt_JERUp = 'jetVariables("(userFloat(\'jer+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jer+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jer-\') > 50)", 0.5).at(0)',
        #j2pt_JERUp = 'jetVariables("(userFloat(\'jer+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jer+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jer-\') > 50)", 0.5).at(6)',

        #vbfMass_JetRelativeBalUp = 'vbfVariables("(userFloat(\'jesRelativeBal+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesRelativeBal+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeBal+\') > 50)", 0.5).mass',
        #vbfMass_JetRelativeBalDown = 'vbfVariables("(userFloat(\'jesRelativeBal-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesRelativeBal-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeBal-\') > 50)", 0.5).mass',
        #jetVeto30_JetRelativeBalUp = 'vetoJets(0.5, "(userFloat(\'jesRelativeBal+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesRelativeBal+\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeBal+\') > 50)").size()',
        #jetVeto30_JetRelativeBalDown = 'vetoJets(0.5, "(userFloat(\'jesRelativeBal-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesRelativeBal-\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeBal-\') > 50)").size()',
        #vbfMass_JetTotalUp = 'vbfVariables("(userFloat(\'jesTotal+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesTotal+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesTotal+\') > 50)", 0.5).mass',
        #vbfMass_JetTotalDown = 'vbfVariables("(userFloat(\'jesTotal-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesTotal-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesTotal-\') > 50)", 0.5).mass',
        #jetVeto30_JetTotalUp = 'vetoJets(0.5, "(userFloat(\'jesTotal+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesTotal+\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesTotal+\') > 50)").size()',
        #jetVeto30_JetTotalDown = 'vetoJets(0.5, "(userFloat(\'jesTotal-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesTotal-\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesTotal-\') > 50)").size()',
        #vbfMass_JetEC2Up = 'vbfVariables("(userFloat(\'jesEC2+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesEC2+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2+\') > 50)", 0.5).mass',
        #vbfMass_JetEC2Down = 'vbfVariables("(userFloat(\'jesEC2-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesEC2-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2-\') > 50)", 0.5).mass',
        #jetVeto30_JetEC2Up = 'vetoJets(0.5, "(userFloat(\'jesEC2+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesEC2+\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2+\') > 50)").size()',
        #jetVeto30_JetEC2Down = 'vetoJets(0.5, "(userFloat(\'jesEC2-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesEC2-\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2-\') > 50)").size()',
        #vbfMass_JetAbsoluteUp = 'vbfVariables("(userFloat(\'jesAbsolute+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesAbsolute+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsolute+\') > 50)", 0.5).mass',
        #vbfMass_JetAbsoluteDown = 'vbfVariables("(userFloat(\'jesAbsolute-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesAbsolute-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsolute-\') > 50)", 0.5).mass',
        #jetVeto30_JetAbsoluteUp = 'vetoJets(0.5, "(userFloat(\'jesAbsolute+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesAbsolute+\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsolute+\') > 50)").size()',
        #jetVeto30_JetAbsoluteDown = 'vetoJets(0.5, "(userFloat(\'jesAbsolute-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesAbsolute-\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsolute-\') > 50)").size()',
        #vbfMass_JetAbsoluteyearUp = 'vbfVariables("(userFloat(\'jesAbsoluteyear+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesAbsoluteyear+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsoluteyear+\') > 50)", 0.5).mass',
        #vbfMass_JetAbsoluteyearDown = 'vbfVariables("(userFloat(\'jesAbsoluteyear-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesAbsoluteyear-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsoluteyear-\') > 50)", 0.5).mass',
        #jetVeto30_JetAbsoluteyearUp = 'vetoJets(0.5, "(userFloat(\'jesAbsoluteyear+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesAbsoluteyear+\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsoluteyear+\') > 50)").size()',
        #jetVeto30_JetAbsoluteyearDown = 'vetoJets(0.5, "(userFloat(\'jesAbsoluteyear-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesAbsoluteyear-\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsoluteyear-\') > 50)").size()',
        #vbfMass_JetFlavorQCDUp = 'vbfVariables("(userFloat(\'jesFlavorQCD+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesFlavorQCD+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesFlavorQCD+\') > 50)", 0.5).mass',
        #vbfMass_JetFlavorQCDDown = 'vbfVariables("(userFloat(\'jesFlavorQCD-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesFlavorQCD-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesFlavorQCD-\') > 50)", 0.5).mass',
        #jetVeto30_JetFlavorQCDUp = 'vetoJets(0.5, "(userFloat(\'jesFlavorQCD+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesFlavorQCD+\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesFlavorQCD+\') > 50)").size()',
        #jetVeto30_JetFlavorQCDDown = 'vetoJets(0.5, "(userFloat(\'jesFlavorQCD-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesFlavorQCD-\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesFlavorQCD-\') > 50)").size()',
        #vbfMass_JetBBEC1Up = 'vbfVariables("(userFloat(\'jesBBEC1+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesBBEC1+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1+\') > 50)", 0.5).mass',
        #vbfMass_JetBBEC1Down = 'vbfVariables("(userFloat(\'jesBBEC1-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesBBEC1-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1-\') > 50)", 0.5).mass',
        #jetVeto30_JetBBEC1Up = 'vetoJets(0.5, "(userFloat(\'jesBBEC1+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesBBEC1+\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1+\') > 50)").size()',
        #jetVeto30_JetBBEC1Down = 'vetoJets(0.5, "(userFloat(\'jesBBEC1-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesBBEC1-\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1-\') > 50)").size()',
        #vbfMass_JetHFUp = 'vbfVariables("(userFloat(\'jesHF+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesHF+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHF+\') > 50)", 0.5).mass',
        #vbfMass_JetHFDown = 'vbfVariables("(userFloat(\'jesHF-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesHF-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHF-\') > 50)", 0.5).mass',
        #jetVeto30_JetHFUp = 'vetoJets(0.5, "(userFloat(\'jesHF+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesHF+\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHF+\') > 50)").size()',
        #jetVeto30_JetHFDown = 'vetoJets(0.5, "(userFloat(\'jesHF-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesHF-\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHF-\') > 50)").size()',
        #vbfMass_JetBBEC1yearUp = 'vbfVariables("(userFloat(\'jesBBEC1year+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesBBEC1year+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1year+\') > 50)", 0.5).mass',
        #vbfMass_JetBBEC1yearDown = 'vbfVariables("(userFloat(\'jesBBEC1year-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesBBEC1year-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1year-\') > 50)", 0.5).mass',
        #jetVeto30_JetBBEC1yearUp = 'vetoJets(0.5, "(userFloat(\'jesBBEC1year+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesBBEC1year+\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1year+\') > 50)").size()',
        #jetVeto30_JetBBEC1yearDown = 'vetoJets(0.5, "(userFloat(\'jesBBEC1year-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesBBEC1year-\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1year-\') > 50)").size()',
        #vbfMass_JetEC2yearUp = 'vbfVariables("(userFloat(\'jesEC2year+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesEC2year+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2year+\') > 50)", 0.5).mass',
        #vbfMass_JetEC2yearDown = 'vbfVariables("(userFloat(\'jesEC2year-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesEC2year-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2year-\') > 50)", 0.5).mass',
        #jetVeto30_JetEC2yearUp = 'vetoJets(0.5, "(userFloat(\'jesEC2year+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesEC2year+\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2year+\') > 50)").size()',
        #jetVeto30_JetEC2yearDown = 'vetoJets(0.5, "(userFloat(\'jesEC2year-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesEC2year-\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2year-\') > 50)").size()',
        #vbfMass_JetHFyearUp = 'vbfVariables("(userFloat(\'jesHFyear+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesHFyear+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHFyear+\') > 50)", 0.5).mass',
        #vbfMass_JetHFyearDown = 'vbfVariables("(userFloat(\'jesHFyear-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesHFyear-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHFyear-\') > 50)", 0.5).mass',
        #jetVeto30_JetHFyearUp = 'vetoJets(0.5, "(userFloat(\'jesHFyear+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesHFyear+\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHFyear+\') > 50)").size()',
        #jetVeto30_JetHFyearDown = 'vetoJets(0.5, "(userFloat(\'jesHFyear-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesHFyear-\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHFyear-\') > 50)").size()',
        #vbfMass_JetRelativeSampleUp = 'vbfVariables("(userFloat(\'jesRelativeSample+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesRelativeSample+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeSample+\') > 50)", 0.5).mass',
        #vbfMass_JetRelativeSampleDown = 'vbfVariables("(userFloat(\'jesRelativeSample-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesRelativeSample-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeSample-\') > 50)", 0.5).mass',
        #jetVeto30_JetRelativeSampleUp = 'vetoJets(0.5, "(userFloat(\'jesRelativeSample+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesRelativeSample+\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeSample+\') > 50)").size()',
        #vbfMass_JetRelativeSampleUp = 'vbfVariables("(userFloat(\'jesRelativeSample+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesRelativeSample+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeSample+\') > 50)", 0.5).mass',
        #vbfMass_JetRelativeSampleDown = 'vbfVariables("(userFloat(\'jesRelativeSample-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesRelativeSample-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeSample-\') > 50)", 0.5).mass',
        #jetVeto30_JetRelativeSampleUp = 'vetoJets(0.5, "(userFloat(\'jesRelativeSample+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesRelativeSample+\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeSample+\') > 50)").size()',
        #jetVeto30_JetRelativeSampleDown = 'vetoJets(0.5, "(userFloat(\'jesRelativeSample-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesRelativeSample-\') > 30 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeSample-\') > 50)").size()',

        #j1pt_JetRelativeSampleDown = 'jetVariables("(userFloat(\'jesRelativeSample-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesRelativeSample-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeSample-\') > 50)", 0.5).at(0)',
        #j1pt_JetRelativeBalDown = 'jetVariables("(userFloat(\'jesRelativeBal-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesRelativeBal-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeBal-\') > 50)", 0.5).at(0)',
        #j1pt_JetRelativeSampleUp = 'jetVariables("(userFloat(\'jesRelativeSample+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesRelativeSample+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeSample+\') > 50)", 0.5).at(0)',
        #j1pt_JetRelativeBalUp = 'jetVariables("(userFloat(\'jesRelativeBal+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesRelativeBal+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeBal+\') > 50)", 0.5).at(0)',
        #j1pt_JetEC2Down = 'jetVariables("(userFloat(\'jesEC2-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesEC2-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2-\') > 50)", 0.5).at(0)',
        #j1pt_JetEC2Up = 'jetVariables("(userFloat(\'jesEC2+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesEC2+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2+\') > 50)", 0.5).at(0)',
        #j1pt_JetAbsoluteDown = 'jetVariables("(userFloat(\'jesAbsolute-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesAbsolute-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsolute-\') > 50)", 0.5).at(0)',
        #j1pt_JetAbsoluteUp = 'jetVariables("(userFloat(\'jesAbsolute+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesAbsolute+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsolute+\') > 50)", 0.5).at(0)',
        #j1pt_JetAbsoluteyearDown = 'jetVariables("(userFloat(\'jesAbsoluteyear-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesAbsoluteyear-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsoluteyear-\') > 50)", 0.5).at(0)',
        #j1pt_JetAbsoluteyearUp = 'jetVariables("(userFloat(\'jesAbsoluteyear+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesAbsoluteyear+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsoluteyear+\') > 50)", 0.5).at(0)',
        #j1pt_JetFlavorQCDDown = 'jetVariables("(userFloat(\'jesFlavorQCD-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesFlavorQCD-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesFlavorQCD-\') > 50)", 0.5).at(0)',
        #j1pt_JetFlavorQCDUp = 'jetVariables("(userFloat(\'jesFlavorQCD+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesFlavorQCD+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesFlavorQCD+\') > 50)", 0.5).at(0)',
        #j1pt_JetBBEC1Down = 'jetVariables("(userFloat(\'jesBBEC1-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesBBEC1-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1-\') > 50)", 0.5).at(0)',
        #j1pt_JetBBEC1Up = 'jetVariables("(userFloat(\'jesBBEC1+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesBBEC1+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1+\') > 50)", 0.5).at(0)',
        #j1pt_JetHFDown = 'jetVariables("(userFloat(\'jesHF-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesHF-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHF-\') > 50)", 0.5).at(0)',
        #j1pt_JetHFUp = 'jetVariables("(userFloat(\'jesHF+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesHF+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHF+\') > 50)", 0.5).at(0)',
        #j1pt_JetBBEC1yearDown = 'jetVariables("(userFloat(\'jesBBEC1year-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesBBEC1year-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1year-\') > 50)", 0.5).at(0)',
        #j1pt_JetBBEC1yearUp = 'jetVariables("(userFloat(\'jesBBEC1year+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesBBEC1year+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1year+\') > 50)", 0.5).at(0)',
        #j1pt_JetEC2yearDown = 'jetVariables("(userFloat(\'jesEC2year-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesEC2year-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2year-\') > 50)", 0.5).at(0)',
        #j1pt_JetEC2yearUp = 'jetVariables("(userFloat(\'jesEC2year+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesEC2year+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2year+\') > 50)", 0.5).at(0)',
        #j1pt_JetHFyearDown = 'jetVariables("(userFloat(\'jesHFyear-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesHFyear-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHFyear-\') > 50)", 0.5).at(0)',
        #j1pt_JetHFyearUp = 'jetVariables("(userFloat(\'jesHFyear+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesHFyear+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHFyear+\') > 50)", 0.5).at(0)',


        #j2pt_JetRelativeSampleDown = 'jetVariables("(userFloat(\'jesRelativeSample-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesRelativeSample-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeSample-\') > 50)", 0.5).at(6)',
        #j2pt_JetRelativeBalDown = 'jetVariables("(userFloat(\'jesRelativeBal-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesRelativeBal-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeBal-\') > 50)", 0.5).at(6)',
        #j2pt_JetRelativeSampleUp = 'jetVariables("(userFloat(\'jesRelativeSample+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesRelativeSample+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeSample+\') > 50)", 0.5).at(6)',
        #j2pt_JetRelativeBalUp = 'jetVariables("(userFloat(\'jesRelativeBal+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesRelativeBal+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesRelativeBal+\') > 50)", 0.5).at(6)',
        #j2pt_JetEC2Down = 'jetVariables("(userFloat(\'jesEC2-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesEC2-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2-\') > 50)", 0.5).at(6)',
        #j2pt_JetEC2Up = 'jetVariables("(userFloat(\'jesEC2+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesEC2+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2+\') > 50)", 0.5).at(6)',
        #j2pt_JetAbsoluteDown = 'jetVariables("(userFloat(\'jesAbsolute-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesAbsolute-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsolute-\') > 50)", 0.5).at(6)',
        #j2pt_JetAbsoluteUp = 'jetVariables("(userFloat(\'jesAbsolute+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesAbsolute+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsolute+\') > 50)", 0.5).at(6)',
        #j2pt_JetAbsoluteyearDown = 'jetVariables("(userFloat(\'jesAbsoluteyear-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesAbsoluteyear-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsoluteyear-\') > 50)", 0.5).at(6)',
        #j2pt_JetAbsoluteyearUp = 'jetVariables("(userFloat(\'jesAbsoluteyear+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesAbsoluteyear+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesAbsoluteyear+\') > 50)", 0.5).at(6)',
        #j2pt_JetFlavorQCDDown = 'jetVariables("(userFloat(\'jesFlavorQCD-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesFlavorQCD-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesFlavorQCD-\') > 50)", 0.5).at(6)',
        #j2pt_JetFlavorQCDUp = 'jetVariables("(userFloat(\'jesFlavorQCD+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesFlavorQCD+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesFlavorQCD+\') > 50)", 0.5).at(6)',
        #j2pt_JetBBEC1Down = 'jetVariables("(userFloat(\'jesBBEC1-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesBBEC1-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1-\') > 50)", 0.5).at(6)',
        #j2pt_JetBBEC1Up = 'jetVariables("(userFloat(\'jesBBEC1+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesBBEC1+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1+\') > 50)", 0.5).at(6)',
        #j2pt_JetHFDown = 'jetVariables("(userFloat(\'jesHF-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesHF-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHF-\') > 50)", 0.5).at(6)',
        #j2pt_JetHFUp = 'jetVariables("(userFloat(\'jesHF+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesHF+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHF+\') > 50)", 0.5).at(6)',
        #j2pt_JetBBEC1yearDown = 'jetVariables("(userFloat(\'jesBBEC1year-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesBBEC1year-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1year-\') > 50)", 0.5).at(6)',
        #j2pt_JetBBEC1yearUp = 'jetVariables("(userFloat(\'jesBBEC1year+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesBBEC1year+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesBBEC1year+\') > 50)", 0.5).at(6)',
        #j2pt_JetEC2yearDown = 'jetVariables("(userFloat(\'jesEC2year-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesEC2year-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2year-\') > 50)", 0.5).at(6)',
        #j2pt_JetEC2yearUp = 'jetVariables("(userFloat(\'jesEC2year+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesEC2year+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesEC2year+\') > 50)", 0.5).at(6)',
        #j2pt_JetHFyearDown = 'jetVariables("(userFloat(\'jesHFyear-\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesHFyear-\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHFyear-\') > 50)", 0.5).at(6)',
        #j2pt_JetHFyearUp = 'jetVariables("(userFloat(\'jesHFyear+\') > 50 | (abs(eta) < 2.65 | abs(eta) > 3.139)) & userFloat(\'jesHFyear+\') > 20 & abs(eta) < 4.7 & userFloat(\'idTight\') > 0.5 & (userInt(\'pileupJetId:fullId\')>3 | userFloat(\'jesHFyear+\') > 50)", 0.5).at(6)',



)

