//This file auto-generated by make_corrections.py
#include <iostream>
#include "TMath.h"
float MuIso(float pt, float eta, float run) {
   if (run < 2) {
      if (pt >= 0 && pt < 8) {
         return 1.0;
      }
      if (pt >= 8 && pt < 10) {
         if (eta >= 0 && eta < 1.44) {
            return 0.968;
         }
         if (eta >= 1.44) {
            return 0.936;
         }
      }
      if (pt >= 10 && pt < 20) {
         if (eta >= 0 && eta < 1.44) {
            return 0.992;
         }
         if (eta >= 1.44) {
            return 0.99;
         }
      }
      if (pt >= 20 && pt < 30) {
         if (eta >= 0 && eta < 1.44) {
            return 1.0;
         }
         if (eta >= 1.44) {
            return 0.998;
         }
      }
      if (pt >= 30 && pt < 50) {
         if (eta >= 0 && eta < 1.44) {
            return 1.0;
         }
         if (eta >= 1.44) {
            return 0.998;
         }
      }
      if (pt >= 50 && pt < 100) {
         if (eta >= 0 && eta < 1.44) {
            return 1.0;
         }
         if (eta >= 1.44) {
            return 1.0;
         }
      }
      if (pt >= 100) {
         if (eta >= 0 && eta < 1.44) {
            return 1.0;
         }
         if (eta >= 1.44) {
            return 1.0;
         }
      }
   }
   if (run >= 2) {
      return 1.0;
   }
   std::cerr << "Warning out of bounds in function MuIso" << std::endl;
   return -999;
}

float EleID(float pt, float eta, float run) {
   if (run < 2) {
      if (pt >= 0 && pt < 10) {
         return 1.0;
      }
      if (pt >= 10 && pt < 20) {
         if (eta >= 0 && eta < 1.44) {
            return 1.024;
         }
         if (eta >= 1.44 && eta < 1.57) {
            return 1.161;
         }
         if (eta >= 1.57) {
            return 1.1;
         }
      }
      if (pt >= 20 && pt < 30) {
         if (eta >= 0 && eta < 1.44) {
            return 0.989;
         }
         if (eta >= 1.44 && eta < 1.57) {
            return 0.995;
         }
         if (eta >= 1.57) {
            return 1.004;
         }
      }
      if (pt >= 30 && pt < 40) {
         if (eta >= 0 && eta < 1.44) {
            return 0.994;
         }
         if (eta >= 1.44 && eta < 1.57) {
            return 1.0;
         }
         if (eta >= 1.57) {
            return 0.996;
         }
      }
      if (pt >= 40 && pt < 50) {
         if (eta >= 0 && eta < 1.44) {
            return 0.996;
         }
         if (eta >= 1.44 && eta < 1.57) {
            return 0.997;
         }
         if (eta >= 1.57) {
            return 1.004;
         }
      }
      if (pt >= 50 && pt < 60) {
         if (eta >= 0 && eta < 1.44) {
            return 0.996;
         }
         if (eta >= 1.44 && eta < 1.57) {
            return 0.982;
         }
         if (eta >= 1.57) {
            return 1.007;
         }
      }
      if (pt >= 60 && pt < 100) {
         if (eta >= 0 && eta < 1.44) {
            return 0.996;
         }
         if (eta >= 1.44 && eta < 1.57) {
            return 1.006;
         }
         if (eta >= 1.57) {
            return 0.995;
         }
      }
      if (pt >= 100) {
         if (eta >= 0 && eta < 1.44) {
            return 0.996;
         }
         if (eta >= 1.44 && eta < 1.57) {
            return 1.006;
         }
         if (eta >= 1.57) {
            return 0.995;
         }
      }
   }
   if (run >= 2) {
      return 1.0;
   }
   std::cerr << "Warning out of bounds in function EleID" << std::endl;
   return -999;
}

float MuEGTrig(float pt, float eta, float run) {
   if (run < 2) {
      if (eta >= 0 && eta < 1.44) {
         return (9.526705e-01*0.5*(1 + TMath::Erf(7.724075e-02*(pt - 1.451806e+00))))/(9.646466e-01*0.5*(1 + TMath::Erf(1.192359e-01*(pt - 1.500038e+00))));
      }
      if (eta >= 1.44 && eta < 1.57) {
         return (8.354832e-01*0.5*(1 + TMath::Erf(1.743949e-01*(pt - 7.650402e+00))))/(9.470130e-01*0.5*(1 + TMath::Erf(9.304980e-02*(pt - 4.955268e+00))));
      }
      if (eta >= 1.57) {
         return (9.421986e-01*0.5*(1 + TMath::Erf(1.704642e-01*(pt - 1.030722e+01))))/(9.565770e-01*0.5*(1 + TMath::Erf(1.422274e-01*(pt - 6.322741e+00))));
      }
   }
   if (run >= 2) {
      return 1.0;
   }
   std::cerr << "Warning out of bounds in function MuEGTrig" << std::endl;
   return -999;
}

float EleIso(float pt, float eta, float run) {
   if (run < 2) {
      if (pt >= 0 && pt < 10) {
         return 1.0;
      }
      if (pt >= 10 && pt < 20) {
         if (eta >= 0 && eta < 1.44) {
            return 1.008;
         }
         if (eta >= 1.44 && eta < 1.57) {
            return 1.029;
         }
         if (eta >= 1.57) {
            return 0.99;
         }
      }
      if (pt >= 20 && pt < 30) {
         if (eta >= 0 && eta < 1.44) {
            return 1.001;
         }
         if (eta >= 1.44 && eta < 1.57) {
            return 0.967;
         }
         if (eta >= 1.57) {
            return 0.995;
         }
      }
      if (pt >= 30 && pt < 40) {
         if (eta >= 0 && eta < 1.44) {
            return 1.0;
         }
         if (eta >= 1.44 && eta < 1.57) {
            return 1.014;
         }
         if (eta >= 1.57) {
            return 1.0;
         }
      }
      if (pt >= 40 && pt < 50) {
         if (eta >= 0 && eta < 1.44) {
            return 0.999;
         }
         if (eta >= 1.44 && eta < 1.57) {
            return 0.996;
         }
         if (eta >= 1.57) {
            return 1.001;
         }
      }
      if (pt >= 50 && pt < 60) {
         if (eta >= 0 && eta < 1.44) {
            return 0.999;
         }
         if (eta >= 1.44 && eta < 1.57) {
            return 0.99;
         }
         if (eta >= 1.57) {
            return 0.998;
         }
      }
      if (pt >= 60 && pt < 100) {
         if (eta >= 0 && eta < 1.44) {
            return 0.999;
         }
         if (eta >= 1.44 && eta < 1.57) {
            return 1.019;
         }
         if (eta >= 1.57) {
            return 0.998;
         }
      }
      if (pt >= 100) {
         if (eta >= 0 && eta < 1.44) {
            return 0.999;
         }
         if (eta >= 1.44 && eta < 1.57) {
            return 1.019;
         }
         if (eta >= 1.57) {
            return 0.998;
         }
      }
   }
   if (run >= 2) {
      return 1.0;
   }
   std::cerr << "Warning out of bounds in function EleIso" << std::endl;
   return -999;
}

float MuHLT8(float pt, float eta, float run) {
   if (run < 2) {
      if (pt >= 0 && pt < 8) {
         return 1.0;
      }
      if (pt >= 8 && pt < 10) {
         if (eta >= 0 && eta < 1.44) {
            return 0.972;
         }
         if (eta >= 1.44) {
            return 1.003;
         }
      }
      if (pt >= 10 && pt < 20) {
         if (eta >= 0 && eta < 1.44) {
            return 0.989;
         }
         if (eta >= 1.44) {
            return 0.988;
         }
      }
      if (pt >= 20 && pt < 30) {
         if (eta >= 0 && eta < 1.44) {
            return 0.987;
         }
         if (eta >= 1.44) {
            return 0.987;
         }
      }
      if (pt >= 30 && pt < 50) {
         if (eta >= 0 && eta < 1.44) {
            return 0.986;
         }
         if (eta >= 1.44) {
            return 0.984;
         }
      }
      if (pt >= 50 && pt < 100) {
         if (eta >= 0 && eta < 1.44) {
            return 0.985;
         }
         if (eta >= 1.44) {
            return 0.982;
         }
      }
      if (pt >= 100) {
         if (eta >= 0 && eta < 1.44) {
            return 0.982;
         }
         if (eta >= 1.44) {
            return 0.982;
         }
      }
   }
   if (run >= 2) {
      return 1.0;
   }
   std::cerr << "Warning out of bounds in function MuHLT8" << std::endl;
   return -999;
}

float MuID(float pt, float eta, float run) {
   if (run < 2) {
      if (pt >= 0 && pt < 8) {
         return 1.0;
      }
      if (pt >= 8 && pt < 10) {
         if (eta >= 0 && eta < 1.44) {
            return 1.005;
         }
         if (eta >= 1.44) {
            return 0.955;
         }
      }
      if (pt >= 10 && pt < 20) {
         if (eta >= 0 && eta < 1.44) {
            return 0.986;
         }
         if (eta >= 1.44) {
            return 0.979;
         }
      }
      if (pt >= 20 && pt < 30) {
         if (eta >= 0 && eta < 1.44) {
            return 0.989;
         }
         if (eta >= 1.44) {
            return 0.976;
         }
      }
      if (pt >= 30 && pt < 50) {
         if (eta >= 0 && eta < 1.44) {
            return 0.991;
         }
         if (eta >= 1.44) {
            return 0.975;
         }
      }
      if (pt >= 50 && pt < 100) {
         if (eta >= 0 && eta < 1.44) {
            return 0.99;
         }
         if (eta >= 1.44) {
            return 0.978;
         }
      }
      if (pt >= 100) {
         if (eta >= 0 && eta < 1.44) {
            return 0.99;
         }
         if (eta >= 1.44) {
            return 0.978;
         }
      }
   }
   if (run >= 2) {
      return 1.0;
   }
   std::cerr << "Warning out of bounds in function MuID" << std::endl;
   return -999;
}

