//This file auto-generated by make_corrections.py
#include <iostream>
#include "TMath.h"
float MuIso(float pt, float eta, float run) {
   if (run < 2) {
      if (pt >= 0 && pt < 8) {
         return 1.0;
      }
      if (pt >= 8 && pt < 10) {
         if (eta >= 0 && eta < 1.44) {
            return 0.968;
         }
         if (eta >= 1.44) {
            return 0.936;
         }
      }
      if (pt >= 10 && pt < 20) {
         if (eta >= 0 && eta < 1.44) {
            return 0.992;
         }
         if (eta >= 1.44) {
            return 0.99;
         }
      }
      if (pt >= 20 && pt < 30) {
         if (eta >= 0 && eta < 1.44) {
            return 1.0;
         }
         if (eta >= 1.44) {
            return 0.998;
         }
      }
      if (pt >= 30 && pt < 50) {
         if (eta >= 0 && eta < 1.44) {
            return 1.0;
         }
         if (eta >= 1.44) {
            return 0.998;
         }
      }
      if (pt >= 50 && pt < 100) {
         if (eta >= 0 && eta < 1.44) {
            return 1.0;
         }
         if (eta >= 1.44) {
            return 1.0;
         }
      }
      if (pt >= 100) {
         if (eta >= 0 && eta < 1.44) {
            return 1.0;
         }
         if (eta >= 1.44) {
            return 1.0;
         }
      }
   }
   if (run >= 2) {
      return 1.0;
   }
   std::cerr << "Warning out of bounds in function MuIso" << std::endl;
   return -999;
}

float EleID(float pt, float eta, float run) {
   if (run < 2) {
      if (pt >= 0 && pt < 10) {
         return 1.0;
      }
      if (pt >= 10 && pt < 20) {
         if (eta >= 0 && eta < 1.44) {
            return 1.024;
         }
         if (eta >= 1.44 && eta < 1.57) {
            return 1.161;
         }
         if (eta >= 1.57) {
            return 1.1;
         }
      }
      if (pt >= 20 && pt < 30) {
         if (eta >= 0 && eta < 1.44) {
            return 0.989;
         }
         if (eta >= 1.44 && eta < 1.57) {
            return 0.995;
         }
         if (eta >= 1.57) {
            return 1.004;
         }
      }
      if (pt >= 30 && pt < 40) {
         if (eta >= 0 && eta < 1.44) {
            return 0.994;
         }
         if (eta >= 1.44 && eta < 1.57) {
            return 1.0;
         }
         if (eta >= 1.57) {
            return 0.996;
         }
      }
      if (pt >= 40 && pt < 50) {
         if (eta >= 0 && eta < 1.44) {
            return 0.996;
         }
         if (eta >= 1.44 && eta < 1.57) {
            return 0.997;
         }
         if (eta >= 1.57) {
            return 1.004;
         }
      }
      if (pt >= 50 && pt < 60) {
         if (eta >= 0 && eta < 1.44) {
            return 0.996;
         }
         if (eta >= 1.44 && eta < 1.57) {
            return 0.982;
         }
         if (eta >= 1.57) {
            return 1.007;
         }
      }
      if (pt >= 60 && pt < 100) {
         if (eta >= 0 && eta < 1.44) {
            return 0.996;
         }
         if (eta >= 1.44 && eta < 1.57) {
            return 1.006;
         }
         if (eta >= 1.57) {
            return 0.995;
         }
      }
      if (pt >= 100) {
         if (eta >= 0 && eta < 1.44) {
            return 0.996;
         }
         if (eta >= 1.44 && eta < 1.57) {
            return 1.006;
         }
         if (eta >= 1.57) {
            return 0.995;
         }
      }
   }
   if (run >= 2) {
      return 1.0;
   }
   std::cerr << "Warning out of bounds in function EleID" << std::endl;
   return -999;
}

float MuEGTrig(float pt, float eta, float run) {
   if (run < 2) {
      if (eta >= 0 && eta < 1.44) {
         return (9.583812e-01*0.5*(1 + TMath::Erf(7.165773e-02*(pt - 6.765913e-09))))/(9.680085e-01*0.5*(1 + TMath::Erf(1.284686e-01*(pt - 2.218156e+00))));
      }
      if (eta >= 1.44 && eta < 1.57) {
         return (8.692322e-01*0.5*(1 + TMath::Erf(2.127596e-01*(pt - 8.745651e+00))))/(9.254809e-01*0.5*(1 + TMath::Erf(2.016003e-01*(pt - 7.146722e+00))));
      }
      if (eta >= 1.57) {
         return (9.424837e-01*0.5*(1 + TMath::Erf(1.989433e-01*(pt - 9.663580e+00))))/(9.619335e-01*0.5*(1 + TMath::Erf(1.659929e-01*(pt - 6.603788e+00))));
      }
   }
   if (run >= 2) {
      return 1.0;
   }
   std::cerr << "Warning out of bounds in function MuEGTrig" << std::endl;
   return -999;
}

float EleIso(float pt, float eta, float run) {
   if (run < 2) {
      if (pt >= 0 && pt < 10) {
         return 1.0;
      }
      if (pt >= 10 && pt < 20) {
         if (eta >= 0 && eta < 1.44) {
            return 1.008;
         }
         if (eta >= 1.44 && eta < 1.57) {
            return 1.029;
         }
         if (eta >= 1.57) {
            return 0.99;
         }
      }
      if (pt >= 20 && pt < 30) {
         if (eta >= 0 && eta < 1.44) {
            return 1.001;
         }
         if (eta >= 1.44 && eta < 1.57) {
            return 0.967;
         }
         if (eta >= 1.57) {
            return 0.995;
         }
      }
      if (pt >= 30 && pt < 40) {
         if (eta >= 0 && eta < 1.44) {
            return 1.0;
         }
         if (eta >= 1.44 && eta < 1.57) {
            return 1.014;
         }
         if (eta >= 1.57) {
            return 1.0;
         }
      }
      if (pt >= 40 && pt < 50) {
         if (eta >= 0 && eta < 1.44) {
            return 0.999;
         }
         if (eta >= 1.44 && eta < 1.57) {
            return 0.996;
         }
         if (eta >= 1.57) {
            return 1.001;
         }
      }
      if (pt >= 50 && pt < 60) {
         if (eta >= 0 && eta < 1.44) {
            return 0.999;
         }
         if (eta >= 1.44 && eta < 1.57) {
            return 0.99;
         }
         if (eta >= 1.57) {
            return 0.998;
         }
      }
      if (pt >= 60 && pt < 100) {
         if (eta >= 0 && eta < 1.44) {
            return 0.999;
         }
         if (eta >= 1.44 && eta < 1.57) {
            return 1.019;
         }
         if (eta >= 1.57) {
            return 0.998;
         }
      }
      if (pt >= 100) {
         if (eta >= 0 && eta < 1.44) {
            return 0.999;
         }
         if (eta >= 1.44 && eta < 1.57) {
            return 1.019;
         }
         if (eta >= 1.57) {
            return 0.998;
         }
      }
   }
   if (run >= 2) {
      return 1.0;
   }
   std::cerr << "Warning out of bounds in function EleIso" << std::endl;
   return -999;
}

float MuHLT8(float pt, float eta, float run) {
   if (run < 2) {
      if (pt >= 0 && pt < 8) {
         return 1.0;
      }
      if (pt >= 8 && pt < 10) {
         if (eta >= 0 && eta < 1.44) {
            return 0.972;
         }
         if (eta >= 1.44) {
            return 1.003;
         }
      }
      if (pt >= 10 && pt < 20) {
         if (eta >= 0 && eta < 1.44) {
            return 0.989;
         }
         if (eta >= 1.44) {
            return 0.988;
         }
      }
      if (pt >= 20 && pt < 30) {
         if (eta >= 0 && eta < 1.44) {
            return 0.987;
         }
         if (eta >= 1.44) {
            return 0.987;
         }
      }
      if (pt >= 30 && pt < 50) {
         if (eta >= 0 && eta < 1.44) {
            return 0.986;
         }
         if (eta >= 1.44) {
            return 0.984;
         }
      }
      if (pt >= 50 && pt < 100) {
         if (eta >= 0 && eta < 1.44) {
            return 0.985;
         }
         if (eta >= 1.44) {
            return 0.982;
         }
      }
      if (pt >= 100) {
         if (eta >= 0 && eta < 1.44) {
            return 0.982;
         }
         if (eta >= 1.44) {
            return 0.982;
         }
      }
   }
   if (run >= 2) {
      return 1.0;
   }
   std::cerr << "Warning out of bounds in function MuHLT8" << std::endl;
   return -999;
}

float MuID(float pt, float eta, float run) {
   if (run < 2) {
      if (pt >= 0 && pt < 8) {
         return 1.0;
      }
      if (pt >= 8 && pt < 10) {
         if (eta >= 0 && eta < 1.44) {
            return 1.005;
         }
         if (eta >= 1.44) {
            return 0.955;
         }
      }
      if (pt >= 10 && pt < 20) {
         if (eta >= 0 && eta < 1.44) {
            return 0.986;
         }
         if (eta >= 1.44) {
            return 0.979;
         }
      }
      if (pt >= 20 && pt < 30) {
         if (eta >= 0 && eta < 1.44) {
            return 0.989;
         }
         if (eta >= 1.44) {
            return 0.976;
         }
      }
      if (pt >= 30 && pt < 50) {
         if (eta >= 0 && eta < 1.44) {
            return 0.991;
         }
         if (eta >= 1.44) {
            return 0.975;
         }
      }
      if (pt >= 50 && pt < 100) {
         if (eta >= 0 && eta < 1.44) {
            return 0.99;
         }
         if (eta >= 1.44) {
            return 0.978;
         }
      }
      if (pt >= 100) {
         if (eta >= 0 && eta < 1.44) {
            return 0.99;
         }
         if (eta >= 1.44) {
            return 0.978;
         }
      }
   }
   if (run >= 2) {
      return 1.0;
   }
   std::cerr << "Warning out of bounds in function MuID" << std::endl;
   return -999;
}

