
// Fake rate functions used to weight events in the VH analysis.
// This file auto-generated by make_fakerates.py
#include "TMath.h"
#include <iostream>

float fakerate_tau(float pt, float /*eta*/) {
    return 4.0899e+00*TMath::Landau(pt,2.6072e+01,2.1624e+00,0)+2.4847e-10;
}

float fakerate_tau_flat(float /*pt*/, float /*eta*/) {
    return 0.033132;
}

float fakerate_muQCD(float pt, float /*eta*/) {
    return 2.8788e+00*TMath::Landau(pt,1.4800e+01,2.6021e+00,0)+2.9508e-04;
}

float fakerate_muQCD_flat(float /*pt*/, float /*eta*/) {
    return 0.049120;
}

float fakerate_eMITQCD(float pt, float /*eta*/) {
    return 1.3455e+00*TMath::Landau(pt,1.4992e+01,1.8292e+00,0)+6.9968e-03;
}

float fakerate_eMITQCD_flat(float /*pt*/, float /*eta*/) {
    return 0.016552;
}

float fakerate_muHighPt(float pt, float /*eta*/) {
    return 4.6983e+00*TMath::Landau(pt,2.8177e+01,3.5932e+00,0)+8.6458e-03;
}

float fakerate_muHighPt_flat(float /*pt*/, float /*eta*/) {
    return 0.090468;
}

float fakerate_tauQCD(float pt, float /*eta*/) {
    return 2.7573e+00*TMath::Landau(pt,2.7567e+01,2.3982e+00,0)+1.6705e-10;
}

float fakerate_tauQCD_flat(float /*pt*/, float /*eta*/) {
    return 0.016996;
}

float fakerate_mu(float pt, float /*eta*/) {
    return 4.4345e+00*TMath::Landau(pt,9.5483e+00,3.6307e+00,0)+4.2790e-10;
}

float fakerate_mu_flat(float /*pt*/, float /*eta*/) {
    return 0.070662;
}

float fakerate_tauQCDTauPt(float pt, float /*eta*/) {
    return 8.6409e+00*TMath::Landau(pt,1.8140e-05,1.0224e+00,0)+5.7602e-03;
}

float fakerate_tauQCDTauPt_flat(float /*pt*/, float /*eta*/) {
    return 0.016996;
}

float fakerate_muHighPtQCDOnly(float pt, float /*eta*/) {
    return 3.6670e+00*TMath::Landau(pt,2.8927e+01,2.8765e+00,0)+4.7947e-03;
}

float fakerate_muHighPtQCDOnly_flat(float /*pt*/, float /*eta*/) {
    return 0.053364;
}

float fakerate_tauTauPt(float pt, float /*eta*/) {
    return 6.9762e-01*TMath::Landau(pt,5.2034e-07,7.0166e+00,0)+7.3162e-03;
}

float fakerate_tauTauPt_flat(float /*pt*/, float /*eta*/) {
    return 0.042644;
}

float fakerate_eMIT(float pt, float /*eta*/) {
    return 1.7043e+00*TMath::Landau(pt,1.2355e+01,1.9980e+00,0)+1.4866e-02;
}

float fakerate_eMIT_flat(float /*pt*/, float /*eta*/) {
    return 0.024384;
}


// ############################################################################
// Corresponding weight functions #############################################
// ############################################################################
float weight_tau(float pt, float eta) {
    float fakerate = fakerate_tau(pt, eta);
    float result = fakerate/(1. - fakerate);
    return result;
}

float weight_tau_flat(float pt, float eta) {
    float fakerate = fakerate_tau_flat(pt, eta);
    float result = fakerate/(1. - fakerate);
    return result;
}

float weight_muQCD(float pt, float eta) {
    float fakerate = fakerate_muQCD(pt, eta);
    float result = fakerate/(1. - fakerate);
    return result;
}

float weight_muQCD_flat(float pt, float eta) {
    float fakerate = fakerate_muQCD_flat(pt, eta);
    float result = fakerate/(1. - fakerate);
    return result;
}

float weight_eMITQCD(float pt, float eta) {
    float fakerate = fakerate_eMITQCD(pt, eta);
    float result = fakerate/(1. - fakerate);
    return result;
}

float weight_eMITQCD_flat(float pt, float eta) {
    float fakerate = fakerate_eMITQCD_flat(pt, eta);
    float result = fakerate/(1. - fakerate);
    return result;
}

float weight_muHighPt(float pt, float eta) {
    float fakerate = fakerate_muHighPt(pt, eta);
    float result = fakerate/(1. - fakerate);
    return result;
}

float weight_muHighPt_flat(float pt, float eta) {
    float fakerate = fakerate_muHighPt_flat(pt, eta);
    float result = fakerate/(1. - fakerate);
    return result;
}

float weight_tauQCD(float pt, float eta) {
    float fakerate = fakerate_tauQCD(pt, eta);
    float result = fakerate/(1. - fakerate);
    return result;
}

float weight_tauQCD_flat(float pt, float eta) {
    float fakerate = fakerate_tauQCD_flat(pt, eta);
    float result = fakerate/(1. - fakerate);
    return result;
}

float weight_mu(float pt, float eta) {
    float fakerate = fakerate_mu(pt, eta);
    float result = fakerate/(1. - fakerate);
    return result;
}

float weight_mu_flat(float pt, float eta) {
    float fakerate = fakerate_mu_flat(pt, eta);
    float result = fakerate/(1. - fakerate);
    return result;
}

float weight_tauQCDTauPt(float pt, float eta) {
    float fakerate = fakerate_tauQCDTauPt(pt, eta);
    float result = fakerate/(1. - fakerate);
    return result;
}

float weight_tauQCDTauPt_flat(float pt, float eta) {
    float fakerate = fakerate_tauQCDTauPt_flat(pt, eta);
    float result = fakerate/(1. - fakerate);
    return result;
}

float weight_muHighPtQCDOnly(float pt, float eta) {
    float fakerate = fakerate_muHighPtQCDOnly(pt, eta);
    float result = fakerate/(1. - fakerate);
    return result;
}

float weight_muHighPtQCDOnly_flat(float pt, float eta) {
    float fakerate = fakerate_muHighPtQCDOnly_flat(pt, eta);
    float result = fakerate/(1. - fakerate);
    return result;
}

float weight_tauTauPt(float pt, float eta) {
    float fakerate = fakerate_tauTauPt(pt, eta);
    float result = fakerate/(1. - fakerate);
    return result;
}

float weight_tauTauPt_flat(float pt, float eta) {
    float fakerate = fakerate_tauTauPt_flat(pt, eta);
    float result = fakerate/(1. - fakerate);
    return result;
}

float weight_eMIT(float pt, float eta) {
    float fakerate = fakerate_eMIT(pt, eta);
    float result = fakerate/(1. - fakerate);
    return result;
}

float weight_eMIT_flat(float pt, float eta) {
    float fakerate = fakerate_eMIT_flat(pt, eta);
    float result = fakerate/(1. - fakerate);
    return result;
}

