# A limits-only make file for HIG-12-010

# Generic rules
#
.SECONDARY:

# Get the asymptotic limit
combo/%.asymp.json: combo/%.txt
	combine $< -M Asymptotic -H ProfileLikelihood --minosAlgo stepping \
	  -n $* \
	  -m `echo $* | sed "s|.*_||g"` | limit2JSON.py --mass `echo $* | sed "s|.*_||g"` > $@
	rm higgsCombine$**.root

gg_mass=$(shell seq 110 1 140) 

tt_mass=$(shell seq 110 1 140) $(shell seq 140 10 160)

bb_mass=$(shell seq 110 1 135)

gg_only=$(shell seq 136 1 150)

tt_only=150 160

high_mass=$(shell seq 170 10 200)

all_masses=$(tt_mass) $(high_mass)

# Put cards in a common ROOT format
combo/zh_%.txt: zh_cards/hzz2l2t_%.txt 
	combineCards.py -S ZH=zh_cards/hzz2l2t_$*.txt > $@

cards/combined_%.txt: vhtt_shapes.root make_data_card.py
	python make_data_card.py -o $@ -m $* -f vhtt_shapes.root \
	  --channels combined --selection final \
	  --emt_shape SubleadingMass \
	  --mmt_shape MuTauMass 

combo/whtt_%.txt: cards/combined_%.txt
	combineCards.py -S WHTT=$< > $@

combo/whww_%.txt: 3l_cards/%/vh3l_cut.txt
	combineCards.py -S WHWW=$< > $@

combo/whgg_%.txt: post-moriond12/%/hgglep.mH*.0.txt
	combineCards.py -S WHGG=$< > $@

combo/whbb_%.txt: moriond12/%/vhbb_DC_ALL_BDT.*.0.txt
	combineCards.py -S WHBB=$< > $@

# Combination of all leptonic channels
combo/leptons_%.txt: zh_cards/hzz2l2t_%.txt cards/combined_%.txt 3l_cards/%/vh3l_cut.txt
	combineCards.py -S $^ > $@

# Combination of all tau
combo/taus_%.txt: zh_cards/hzz2l2t_%.txt cards/combined_%.txt moriond12/%/htt_*txt 
	combineCards.py -S $^ > $@

# Combination of just H2Tau
combo/h2tau_%.txt: moriond12/%/htt_*.txt
	combineCards.py -S $^ > $@

# Combo with gg
combo/with_gg_%.txt: zh_cards/hzz2l2t_%.txt cards/combined_%.txt 3l_cards/%/vh3l_cut.txt post-moriond12/%/hgglep.mH*.0.txt
	combineCards.py -S $^ > $@

# Combination of everything we got
combo/with_all_%.txt: zh_cards/hzz2l2t_%.txt cards/combined_%.txt 3l_cards/%/vh3l_cut.txt post-moriond12/%/hgglep.mH*.0.txt moriond12/%/vhbb_DC_ALL_BDT.*.0.txt
	combineCards.py -S $^ > $@

# Combination of everything we got, excluding theory errors
combo/with_all_noth_%.txt: combo/with_all_%.txt
	remove_systematics.py $^ pdf_* QCDscale* > $@

combo/%.root: combo/%.txt
	text2workspace.py $< -o $@

whtt_limits=$(patsubst %, combo/whtt_%.asymp.json, $(tt_mass)) 

zh_limits=$(patsubst %, combo/zh_%.asymp.json, $(tt_mass)) 

whww_limits=$(patsubst %, combo/whww_%.asymp.json, $(all_masses)) 

whgg_limits=$(patsubst %, combo/whgg_%.asymp.json, $(gg_mass)) 

whbb_limits=$(patsubst %, combo/whbb_%.asymp.json, $(bb_mass)) 

leptons_limits=$(patsubst %, combo/leptons_%.asymp.json, $(tt_mass)) 

taus_limits=$(patsubst %, combo/taus_%.asymp.json, $(gg_mass)) 

h2tau_limits=$(patsubst %, combo/h2tau_%.asymp.json, $(gg_mass)) 

leptons_gg_limits=$(patsubst %, combo/with_gg_%.asymp.json, $(gg_mass)) 

gg_only_limits=$(patsubst %, combo/with_gg_%.asymp.json, $(gg_only)) 

tt_only_limits=$(patsubst %, combo/leptons_%.asymp.json, $(tt_only)) 

ww_only_limits=$(patsubst %, combo/whww_%.asymp.json, $(high_mass))

leptons_all_limits=$(patsubst %, combo/with_all_%.asymp.json, $(bb_mass)) 

# Asymptotic limits
all: $(whbb_limits) $(whtt_limits) $(zh_limits) $(whww_limits) $(whgg_limits) $(leptons_limits) $(leptons_gg_limits) $(leptons_all_limits) $(taus_limits)

combo/%_asymp.pdf: paper_blurb.py
	python $(fsa)/StatTools/scripts/plotlimit.py \
	  --max-y 20 \
	  --lumi 5000 \
	  --method asymp combo/$**.asymp.json -o $@ \
	  --showpoints \
	  --blurb "`./paper_blurb.py $@`" \
	  --blurbalign 13 \
	  --blurbpos "0.15, 0.8, 0.7, 0.95" \
	  --legendpos "0,0,0,0"

plots: combo/whww_asymp.pdf combo/whtt_asymp.pdf combo/whgg_asymp.pdf \
  combo/whbb_asymp.pdf combo/zh_asymp.pdf combo/leptons_asymp.pdf \
  combo/taus_asymp.pdf \
  combo/with_gg_asymp.pdf combo/with_all_asymp.pdf

combo/all_asymp.pdf: paper_blurb.py $(leptons_all_limits) $(gg_only_limits) $(tt_only_limits) $(ww_only_limits)
	python $(fsa)/StatTools/scripts/plotlimit.py \
	  --max-y 10 \
	  --max-x 150 \
	  --lumi 5000 \
	  --method asymp $(leptons_all_limits) $(gg_only_limits) $(tt_only_limits) $(ww_only_limits) -o $@ \
	  --showpoints \
	  --show-sm \
	  --blurb "VH: leptons + #gamma#gamma + bb" \
	  --blurbalign 13 \
	  --blurbpos "0.15, 0.8, 0.7, 0.95" \
	  --legendpos "0,0,0,0"


# Computing CLs grids
/scratch/efriis/paper_combo/%_cls/submit: combo/%.root
	mkdir -p `dirname $@` 
	make_grid_submission.py -submitdir `dirname $@` \
	  -i `readlink -f $<` -mass `echo $* | sed "s|.*_||g"` \
	  -min 0.2 -max 30

/scratch/efriis/paper_combo/%_cls/grid.root: /scratch/efriis/paper_combo/%_cls/point*.root
	hadd -f $@ $^

combo/%.cls.json: combo/%.txt $(scratch)/paper_combo/%_cls/grid.root 
	compute_cls.sh $^ `echo $* | sed "s|.*_||g"` > $@

whtt_cls_submits=$(patsubst %, /scratch/efriis/paper_combo/whtt_%_cls/submit, $(tt_mass))

zh_cls_submits=$(patsubst %, /scratch/efriis/paper_combo/zh_%_cls/submit, $(tt_mass))

whww_cls_submits=$(patsubst %, /scratch/efriis/paper_combo/whww_%_cls/submit, $(all_masses))

whgg_cls_submits=$(patsubst %, /scratch/efriis/paper_combo/whgg_%_cls/submit, $(gg_mass))

whbb_cls_submits=$(patsubst %, /scratch/efriis/paper_combo/whbb_%_cls/submit, $(bb_mass))

leptons_cls_submits=$(patsubst %, /scratch/efriis/paper_combo/leptons_%_cls/submit, $(tt_mass))

taus_cls_submits=$(patsubst %, /scratch/efriis/paper_combo/taus_%_cls/submit, $(gg_mass))

h2tau_cls_submits=$(patsubst %, /scratch/efriis/paper_combo/h2tau_%_cls/submit, $(gg_mass))

buh: $(taus_cls_submits) $(h2tau_cls_submits)

with_gg_cls_submits=$(patsubst %, /scratch/efriis/paper_combo/with_gg_%_cls/submit, $(gg_mass))

with_all_cls_submits=$(patsubst %, /scratch/efriis/paper_combo/with_all_%_cls/submit, $(bb_mass))

all_cls_submits: whtt_cls_submits zh_cls_submits whww_cls_submits whgg_cls_submits whbb_cls_submits leptons_cls_submits with_gg_cls_submits with_all_cls_submits

whtt_cls_grids=$(patsubst %, /scratch/efriis/paper_combo/whtt_%_cls/grid.root, $(tt_mass))

zh_cls_grids=$(patsubst %, /scratch/efriis/paper_combo/zh_%_cls/grid.root, $(tt_mass))

whww_cls_grids=$(patsubst %, /scratch/efriis/paper_combo/whww_%_cls/grid.root, $(all_masses))

whgg_cls_grids=$(patsubst %, /scratch/efriis/paper_combo/whgg_%_cls/grid.root, $(gg_mass))

whbb_cls_grids=$(patsubst %, /scratch/efriis/paper_combo/whbb_%_cls/grid.root, $(bb_mass))

leptons_cls_grids=$(patsubst %, /scratch/efriis/paper_combo/leptons_%_cls/grid.root, $(tt_mass))

with_gg_cls_grids=$(patsubst %, /scratch/efriis/paper_combo/with_gg_%_cls/grid.root, $(gg_mass))

with_all_cls_grids=$(patsubst %, /scratch/efriis/paper_combo/with_all_%_cls/grid.root, $(bb_mass))

all_cls_grids: whtt_cls_grids zh_cls_grids whww_cls_grids whgg_cls_grids whbb_cls_grids leptons_cls_grids with_gg_cls_grids with_all_cls_grids

whtt_cls_limits=$(patsubst %, combo/whtt_%.cls.json, $(tt_mass)) 

zh_cls_limits=$(patsubst %, combo/zh_%.cls.json, $(tt_mass)) 

whww_cls_limits=$(patsubst %, combo/whww_%.cls.json, $(all_masses)) 

whww_high_mass_cls_limits=$(patsubst %, combo/whww_%.cls.json, $(high_mass)) 

whgg_cls_limits=$(patsubst %, combo/whgg_%.cls.json, $(gg_mass)) 

whbb_cls_limits=$(patsubst %, combo/whbb_%.cls.json, $(bb_mass)) 

leptons_cls_limits=$(patsubst %, combo/leptons_%.cls.json, $(tt_mass)) 

leptons_gg_cls_limits=$(patsubst %, combo/with_gg_%.cls.json, $(gg_mass)) 

leptons_all_cls_limits=$(patsubst %, combo/with_all_%.cls.json, $(bb_mass)) 

# Asymptotic limits
all_cls: whbb_cls_limits whtt_cls_limits zh_cls_limits whww_cls_limits whgg_cls_limits leptons_cls_limits leptons_gg_cls_limits leptons_all_cls_limits

# Plotting CLs limits 

combo/whtt_cls.pdf: $(whtt_cls_limits)
	python $(fsa)/StatTools/scripts/plotlimit.py \
	  --max-y 20 \
	  --max-x 200 \
	  --lumi 5000 \
	  --method cls $^ -o $@ \
	  --showpoints \
	  --blurb "e#mu#tau and #mu#mu#tau" \
	  --blurbalign 33 \
	  --blurbpos "0.65, 0.15, 0.95, 0.25" \
	  --legendpos "0.55,0.60,0.80,0.90"


combo/whww_cls.pdf: $(whww_cls_limits)
	python $(fsa)/StatTools/scripts/plotlimit.py \
	  --max-y 20 \
	  --max-x 200 \
	  --lumi 5000 \
	  --method cls $^ -o $@ \
	  --showpoints \
	  --blurb "WWW channels" \
	  --blurbalign 33 \
	  --blurbpos "0.65, 0.15, 0.95, 0.25" \
	  --legendpos "0.50,0.60,0.75,0.90"

combo/whbb_cls.pdf: $(whbb_cls_limits)
	python $(fsa)/StatTools/scripts/plotlimit.py \
	  --max-y 20 \
	  --max-x 200 \
	  --lumi 5000 \
	  --method cls $^ -o $@ \
	  --showpoints \
	  --blurb "Vbb channels" \
	  --blurbalign 33 \
	  --blurbpos "0.65, 0.15, 0.95, 0.25" \
	  --legendpos "0.50,0.60,0.75,0.90"

combo/zh_cls.pdf: $(zh_cls_limits)
	python $(fsa)/StatTools/scripts/plotlimit.py \
	  --max-y 20 \
	  --max-x 200 \
	  --lumi 5000 \
	  --method cls $^ -o $@ \
	  --showpoints \
	  --blurb "Four lepton" \
	  --blurbalign 33 \
	  --blurbpos "0.65, 0.15, 0.95, 0.25" \
	  --legendpos "0.65,0.60,0.9,0.90"

combo/whgg_cls.pdf: $(whgg_cls_limits)
	python $(fsa)/StatTools/scripts/plotlimit.py \
	  --max-y 20 \
	  --max-x 200 \
	  --lumi 5000 \
	  --method cls $^ -o $@ \
	  --showpoints \
	  --blurb "V#gamma#gamma" \
	  --blurbalign 33 \
	  --blurbpos "0.65, 0.15, 0.95, 0.25" \
	  --legendpos "0.50,0.60,0.75,0.90"

combo/leptons_cls.pdf: $(leptons_cls_limits) $(whww_high_mass_cls_limits)
	python $(fsa)/StatTools/scripts/plotlimit.py \
	  --max-y 20 \
	  --max-x 200 \
	  --lumi 5000 \
	  --method cls $^ -o $@ \
	  --showpoints \
	  --blurb "Leptonic" \
	  --blurbalign 33 \
	  --blurbpos "0.65, 0.15, 0.95, 0.25" \
	  --legendpos "0.50,0.60,0.75,0.90"

combo/with_gg_cls.pdf: $(leptons_gg_cls_limits) combo/leptons_160.cls.json $(whww_high_mass_cls_limits)
	python $(fsa)/StatTools/scripts/plotlimit.py \
	  --max-y 20 \
	  --max-x 200 \
	  --lumi 5000 \
	  --method cls $^ -o $@ \
	  --showpoints \
	  --blurb "Leptonic and #gamma#gamma" \
	  --blurbalign 33 \
	  --blurbpos "0.65, 0.15, 0.95, 0.25" \
	  --legendpos "0.50,0.60,0.75,0.90"

combo/with_all_cls.pdf: $(leptons_all_cls_limits) combo/with_gg_140.cls.json combo/with_gg_150.cls.json   combo/leptons_160.cls.json $(whww_high_mass_cls_limits)
	python $(fsa)/StatTools/scripts/plotlimit.py \
	  --max-y 20 \
	  --max-x 200 \
	  --lumi 5000 \
	  --method cls $^ -o $@ \
	  --showpoints \
	  --blurb "Leptonic, #gamma#gamma, and bb" \
	  --blurbalign 33 \
	  --blurbpos "0.65, 0.15, 0.95, 0.25" \
	  --legendpos "0.50,0.60,0.75,0.90"

cls_plots: combo/zh_cls.pdf combo/whbb_cls.pdf combo/whbb_cls.pdf combo/whgg_cls.pdf combo/whtt_cls.pdf combo/whww_cls.pdf combo/leptons_cls.pdf combo/with_gg_cls.pdf combo/with_all_cls.pdf

