# Get common recipes
recipes = ENV['fsa'] + '/PlotTools/rake/recipes.rake'
import recipes

$jobid = ENV['jobid']

# Figure out what run period we are in
$period = '7TeV'
if $jobid.include? '8TeV'
  $period = '8TeV'
end

################################################################################
## Sample names ################################################################
################################################################################
#
# Get sample names containing a substring
def get_sample_names(substring)
  inputs = Dir.glob("inputs/#{$jobid}/*.txt").select {|x| x.include? substring}
  inputs = inputs.map{|x| File.basename(x).sub(".txt", "")}
  return inputs
end


samples = Hash[
  "ewk" => Array['Zjets_M50', 'WplusJets_madgraph', 
    'ZZJetsTo4L_pythia',
    'TTplusJets_madgraph'] + get_sample_names('WZ') + get_sample_names('WW'),
  "wjets" => Array['WplusJets_madgraph'],
  "zjets" => Array['Zjets_M50'],
  "diboson" => Array['ZZJetsTo4L_pythia'] + get_sample_names('WZ') + get_sample_names('WW'),
  "signal" => get_sample_names('VH') + get_sample_names('WH'),
  "data_em" => get_sample_names("data_MuEG"),
]

# Function to get the .root files for an analyzer and samples
def get_analyzer_results(analyzer, the_samples)
  output = Array.new
  analyzer_base = analyzer.sub('.py', '')
  the_samples.each do |sample|
    output << "results/#{$jobid}/#{analyzer_base}/#{sample}.root"
  end
  return output
end

################################################################################
## Recipes to analyze H2Tau
##  targets:
##     em
################################################################################

task :em => get_analyzer_results(
  "AnalyzeEM.py", samples['ewk'] + samples['data_em'] + samples['signal'])

