#include "FinalStateAnalysis/PatTools/plugins/PATQuadFinalStateBuilderT.h"
#include "FinalStateAnalysis/DataFormats/interface/PATQuadLeptonFinalStates.h"

typedef PATQuadFinalStateBuilderT<PATElecElecElecElecFinalState> PATElecElecElecElecFinalStateProducer;
typedef PATQuadFinalStateBuilderT<PATElecElecElecMuFinalState> PATElecElecElecMuFinalStateProducer;
typedef PATQuadFinalStateBuilderT<PATElecElecElecTauFinalState> PATElecElecElecTauFinalStateProducer;
typedef PATQuadFinalStateBuilderT<PATElecElecMuMuFinalState> PATElecElecMuMuFinalStateProducer;
typedef PATQuadFinalStateBuilderT<PATElecElecMuTauFinalState> PATElecElecMuTauFinalStateProducer;
typedef PATQuadFinalStateBuilderT<PATElecElecTauTauFinalState> PATElecElecTauTauFinalStateProducer;
typedef PATQuadFinalStateBuilderT<PATElecMuMuMuFinalState> PATElecMuMuMuFinalStateProducer;
typedef PATQuadFinalStateBuilderT<PATElecMuMuTauFinalState> PATElecMuMuTauFinalStateProducer;
typedef PATQuadFinalStateBuilderT<PATElecMuTauTauFinalState> PATElecMuTauTauFinalStateProducer;
typedef PATQuadFinalStateBuilderT<PATElecTauTauTauFinalState> PATElecTauTauTauFinalStateProducer;
typedef PATQuadFinalStateBuilderT<PATMuMuMuMuFinalState> PATMuMuMuMuFinalStateProducer;
typedef PATQuadFinalStateBuilderT<PATMuMuMuTauFinalState> PATMuMuMuTauFinalStateProducer;
typedef PATQuadFinalStateBuilderT<PATMuMuTauTauFinalState> PATMuMuTauTauFinalStateProducer;
typedef PATQuadFinalStateBuilderT<PATMuTauTauTauFinalState> PATMuTauTauTauFinalStateProducer;
typedef PATQuadFinalStateBuilderT<PATTauTauTauTauFinalState> PATTauTauTauTauFinalStateProducer;

#include "FWCore/Framework/interface/MakerMacros.h"

DEFINE_FWK_MODULE(PATElecElecElecElecFinalState);
DEFINE_FWK_MODULE(PATElecElecElecMuFinalState);
DEFINE_FWK_MODULE(PATElecElecElecTauFinalState);
DEFINE_FWK_MODULE(PATElecElecMuMuFinalState);
DEFINE_FWK_MODULE(PATElecElecMuTauFinalState);
DEFINE_FWK_MODULE(PATElecElecTauTauFinalState);
DEFINE_FWK_MODULE(PATElecMuMuMuFinalState);
DEFINE_FWK_MODULE(PATElecMuMuTauFinalState);
DEFINE_FWK_MODULE(PATElecMuTauTauFinalState);
DEFINE_FWK_MODULE(PATElecTauTauTauFinalState);
DEFINE_FWK_MODULE(PATMuMuMuMuFinalState);
DEFINE_FWK_MODULE(PATMuMuMuTauFinalState);
DEFINE_FWK_MODULE(PATMuMuTauTauFinalState);
DEFINE_FWK_MODULE(PATMuTauTauTauFinalState);
DEFINE_FWK_MODULE(PATTauTauTauTauFinalState);
