#include "FinalStateAnalysis/PatTools/plugins/PATTripletFinalStateBuilderT.h"
#include "FinalStateAnalysis/DataFormats/interface/PATTriLeptonFinalStates.h"

typedef PATTripletFinalStateBuilderT<PATElecElecElecFinalState> PATElecElecElecFinalStateProducer;
typedef PATTripletFinalStateBuilderT<PATElecElecMuFinalState> PATElecElecMuFinalStateProducer;
typedef PATTripletFinalStateBuilderT<PATElecElecTauFinalState> PATElecElecTauFinalStateProducer;
typedef PATTripletFinalStateBuilderT<PATElecElecPhoFinalState> PATElecElecPhoFinalStateProducer;
typedef PATTripletFinalStateBuilderT<PATElecMuMuFinalState> PATElecMuMuFinalStateProducer;
typedef PATTripletFinalStateBuilderT<PATElecMuTauFinalState> PATElecMuTauFinalStateProducer;
typedef PATTripletFinalStateBuilderT<PATElecMuPhoFinalState> PATElecMuPhoFinalStateProducer;
typedef PATTripletFinalStateBuilderT<PATElecTauTauFinalState> PATElecTauTauFinalStateProducer;
typedef PATTripletFinalStateBuilderT<PATElecPhoPhoFinalState> PATElecPhoPhoFinalStateProducer;
typedef PATTripletFinalStateBuilderT<PATMuMuMuFinalState> PATMuMuMuFinalStateProducer;
typedef PATTripletFinalStateBuilderT<PATMuMuTauFinalState> PATMuMuTauFinalStateProducer;
typedef PATTripletFinalStateBuilderT<PATMuMuPhoFinalState> PATMuMuPhoFinalStateProducer;
typedef PATTripletFinalStateBuilderT<PATMuTauTauFinalState> PATMuTauTauFinalStateProducer;
typedef PATTripletFinalStateBuilderT<PATTauTauTauFinalState> PATTauTauTauFinalStateProducer;
typedef PATTripletFinalStateBuilderT<PATMuPhoPhoFinalState> PATMuPhoPhoFinalStateProducer;
typedef PATTripletFinalStateBuilderT<PATMuJetJetFinalState> PATMuJetJetFinalStateProducer;

#include "FWCore/Framework/interface/MakerMacros.h"

DEFINE_FWK_MODULE(PATElecElecElecFinalStateProducer);
DEFINE_FWK_MODULE(PATElecElecMuFinalStateProducer);
DEFINE_FWK_MODULE(PATElecElecTauFinalStateProducer);
DEFINE_FWK_MODULE(PATElecElecPhoFinalStateProducer);
DEFINE_FWK_MODULE(PATElecMuMuFinalStateProducer);
DEFINE_FWK_MODULE(PATElecMuTauFinalStateProducer);
DEFINE_FWK_MODULE(PATElecMuPhoFinalStateProducer);
DEFINE_FWK_MODULE(PATElecTauTauFinalStateProducer);
DEFINE_FWK_MODULE(PATElecPhoPhoFinalStateProducer);
DEFINE_FWK_MODULE(PATMuMuMuFinalStateProducer);
DEFINE_FWK_MODULE(PATMuMuTauFinalStateProducer);
DEFINE_FWK_MODULE(PATMuMuPhoFinalStateProducer);
DEFINE_FWK_MODULE(PATMuTauTauFinalStateProducer);
DEFINE_FWK_MODULE(PATTauTauTauFinalStateProducer);
DEFINE_FWK_MODULE(PATMuPhoPhoFinalStateProducer);
DEFINE_FWK_MODULE(PATMuJetJetFinalStateProducer);

