#include "FinalStateAnalysis/PatTools/plugins/PATTripletFinalStateBuilderT.h"
#include "FinalStateAnalysis/DataFormats/interface/PATTriLeptonFinalStates.h"

typedef PATTripletFinalStateBuilderT<PATElecElecElecFinalState> PATElecElecElecFinalStateProducer;
typedef PATTripletFinalStateBuilderT<PATElecElecMuFinalState> PATElecElecMuFinalStateProducer;
typedef PATTripletFinalStateBuilderT<PATElecElecTauFinalState> PATElecElecTauFinalStateProducer;
typedef PATTripletFinalStateBuilderT<PATElecElecPhoFinalState> PATElecElecPhoFinalStateProducer;

typedef PATTripletFinalStateBuilderT<PATElecMuMuFinalState> PATElecMuMuFinalStateProducer;
typedef PATTripletFinalStateBuilderT<PATElecMuTauFinalState> PATElecMuTauFinalStateProducer;
typedef PATTripletFinalStateBuilderT<PATElecMuPhoFinalState> PATElecMuPhoFinalStateProducer;

typedef PATTripletFinalStateBuilderT<PATElecTauTauFinalState> PATElecTauTauFinalStateProducer;
typedef PATTripletFinalStateBuilderT<PATElecTauPhoFinalState> PATElecTauPhoFinalStateProducer;

typedef PATTripletFinalStateBuilderT<PATElecPhoPhoFinalState> PATElecPhoPhoFinalStateProducer;

typedef PATTripletFinalStateBuilderT<PATMuMuMuFinalState> PATMuMuMuFinalStateProducer;
typedef PATTripletFinalStateBuilderT<PATMuMuTauFinalState> PATMuMuTauFinalStateProducer;
typedef PATTripletFinalStateBuilderT<PATMuTauTauFinalState> PATMuTauTauFinalStateProducer;

#include "FWCore/Framework/interface/MakerMacros.h"
DEFINE_FWK_MODULE(PATElecElecElecFinalStateProducer);
DEFINE_FWK_MODULE(PATElecElecMuFinalStateProducer);
DEFINE_FWK_MODULE(PATElecElecTauFinalStateProducer);
DEFINE_FWK_MODULE(PATElecTauTauFinalStateProducer);
DEFINE_FWK_MODULE(PATElecMuMuFinalStateProducer);
DEFINE_FWK_MODULE(PATElecMuTauFinalStateProducer);
DEFINE_FWK_MODULE(PATMuMuMuFinalStateProducer);
DEFINE_FWK_MODULE(PATMuMuTauFinalStateProducer);
DEFINE_FWK_MODULE(PATMuTauTauFinalStateProducer);
