
################################################################################
### General rules ##############################################################
################################################################################

# How to generate the inputs
desc "Query lists of ntuple .root files"
task :getinputs, [:jobid, :source] do |t, args|
  sh "discover_ntuples.sh #{args.jobid} #{args.source} inputs/#{args.jobid}"
end

# Rule to map an analyzer + an MC input to a results .root file
# inputs/jobid/sample.txt => results/jobid/analyzer/sample.root
desc "Analyze a sample, producing a .root file"
#rule /^results\/.*\/.*\/.*.root$/ => [ 
rule ".root" => [ 
  # The analyzer .py file
  proc {|targ| targ.sub(%r{results/.*/(.*)/.*root}, "\\1.py")},
  # The sample file list .txt file
  proc {|targ| targ.sub(%r{results/(.*)/.*/(.*).root}, "inputs/\\1/\\2.txt")} ] do |t|
  # Make the output directory
  sh "mkdir -p `dirname #{t.name}`"
  sh "mega #{t.prerequisites[0]} #{t.prerequisites[1]} #{t.name}"
end

# Rule to build cython wrappers for the ntuples
desc "Compile a cython proxy wrapper"
rule ".so" => [proc { |targ| targ.sub('.so', '_setup.py') }] do |t|
  sh "python #{t.source} build_ext --inplace"
end

task :analyze, [:jobid, :analyzer, :sample] do |t, args|
   Rake::Task["results/#{args.jobid}/#{args.analyzer}/#{args.sample}.root"].invoke
end

################################################################################
### Analysis targets ###########################################################
################################################################################
