import os
import ROOT
from FinalStateAnalysis.TMegaSelector.megaselect import TMegaPySelector

chain = ROOT.TChain("TestTree")
# test_file.root can be generated by the CPP unit test
chain.Add('test_file.root')
print "Got tree with %i entries" % chain.GetEntries()

chain.Process("TMegaPySelector", "TestSelector")
